### ISSUE TITLE
Provider Key: microsoft/fabric

### ISSUE THREAD

**Issue by DariuszPorowski** [opentofu/registry#1004]
### Provider Namespace

microsoft

### Public Membership

- [X] I have made my membership public

### Provider GPG Key

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBGYlieQBEADMTtmdvGty4MjbtHxTtsJGx5LT1UAqpIGtgbWcMtMOdDYT/aCT
IGqEAv7Dt4rVrHhyu4mfMH51LgMckcYD1VlRJVh16aFv6hQnmWISHAUF+Bd+jFAP
vEzsnKVljZDU9q50u75vABVbVnZZTDtCByPgNzBcp4CnRqDhQ/bEdsQwBmPRwPCC
FxJ/v5H5HGmDMcP6lT0hZ8g/N47Em49vitMZm3dHlEyNu6+99Sdm4IuvAngn3obJ
9baZG6hOqxDbamXNNQj5FRiVINsdQxeX6OLULa6jub2hoiLw61p2McpHYsp2XWiX
BZPj/nmxPH+D9vDYNXkTaGo0ubQAKZXtuF1zDjfScjNp4dZxeyV+OWcc7Rhu+jcH
Pwxo9ihi5eaNMwADSkX3HubgB/Ix0zNuPpjGZDHz6R6mgLD+s45jvtWH/NiLdd2i
TsuZnF9tCdho3fztIl/dSJRAiPUU9wSQbHZ10iiRqe+VleWVAbEHGdv6hNsFi7dj
UHlvPpefnsHgjubeaXRW808ZhMGYuOu5T1rFPa0dzUhNfyYf9KLmKF8lgMJQRhBg
FhwzvRQuIBIUaGNKiW5EB8bnhCdvx6W+VY35QPXHIynj8YIs/DYwPC9MFcIaaAfo
28qwouqNri7k61fO/rY/LHYQ3EJzeAKcORSSf9CnLcybZexqnxekJ/p8TQARAQAB
tDxNaWNyb3NvZnQgRmFicmljIFRlcnJhZm9ybSBQcm92aWRlciA8ZmFicmljdGZA
bWljcm9zb2Z0LmNvbT6JAlEEEwEIADsWIQT+z8WV7cqsQIM+zNiQ9bw+4nWxWgUC
ZiWJ5AIbAwULCQgHAgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRCQ9bw+4nWxWudV
EAC2FPyCRZ7jbdm7/GYWxa1T58tE/6Wk0Jgek3BPPWKqimK23zEDEP/ZmaB5L8FL
XItoj90JDxx3bzoc1XHFygDMCi/7mbkYDPnrfDdz2eNulcu7PBLEqbU+ImamCZ8s
FXLtH9UsDtcP5KOPouRDZLRFYgGvb+mFUJhVP2ofnS6uuqRsXQ3kqfgU9uKGKzQz
RrMX2SVJtqs6dJr1A8VQT/jwbOdM9Ziu2FIUGhpvl7LXF6A1ud5K7Flg22N8ct8s
SXi+tWbDv5qfjOPYR/skMXS5JPUbglT3PBxVtKk3GqRyo6L2xFG0idtqi+rD6Ede
WU4+Q109+mj8ODxcza4ZSKckOcbWapUY0YSL6ZreF+6L9Bmnx/6IpUjHTeNgdsR2
7U8ADcTMF1XpDgSvtknNmb3ck04xdpUHATgHaYxz9xvGikm0ZVmQElBQfCyek7ub
HMKSk44mH9PRgaqFYFtlzyobBfYqifKUHA4pC5w8MCwpaM6mCTF6xt6yIsbDyPKs
mN1QFu8/QE4WVSEWXyad/3jEfMLouXGMhfZCv6jSjiVbhSFi+5882de8YC02tJf+
NEQOrGKJas7mr8Juenf2y7aHsy+yaMxTFqPLsU/mlln84GaM0q9g1Psi00En7Puv
exWeeNUYxQlh9lgKtNUsE+tKk1T6e1bM9qWzFMvFoaXP6bkCDQRmJYnkARAAr3jN
J2WMfjSI7eWCNSrtyHlMiSd0PZ0xBSUOUSdfF/I323iSyWTVB/E+2B5epIM+izwL
80mOEvdSalE8aB5GoUk83X59/uvVXK9+e1S0lM/QUtOi2jkMAZMgBtpngOtWLngI
VNM+kYzER+Mk3PH8MoJRREp4bEezzWnO0qvUBo7i0FD3C+iftnx+NwWZNRpr1aOO
TZDUe5D0gMmi3ftaiXX5rBx+UfGQTWIUl5ShUNqJW73QmdNmd8cUiCQHLO3AyFHY
N5/t0gF+YwTlELSHWVCqLV1bCDAdiVZRLXwIkxxPPOV8Af2MrN9VGgEmj8QDXgGo
0sdQdwGeb6dAnWH0ywWYXuuJuKK4umRKsyJFLZZCUW35RhF+Cb6qCDHwRyFwcyKH
Xn1nYAYb5ZFk+1LU1xGpJWQbGt5YoKxvpdOrap3VVUOR54FSOznDPfGd7zpu2zry
LGPYqgprUKqpaxMMadj2uCBUhUb6vH9+iz1SaXcIs4kwObSHL2bSFGdHKRuZ8eGQ
+0e9Jc4Bb9p1HahZMdS6jGocWvb7SZfg5CF6ZgcmUV+lKJ6LwXaROTlCny1lvJsW
mfhr58/MwKlf7lWCupkZtG3uyXUAmKpMeR6CEbJv/A3eg9JxsaRERexgzNCPlREJ
sRKE+7wvSOuvFevgF9qmtc3Ml/+1BRMSsL1sebkAEQEAAYkCNgQYAQgAIBYhBP7P
xZXtyqxAgz7M2JD1vD7idbFaBQJmJYnkAhsMAAoJEJD1vD7idbFayjsP/0QE8Djl
kuxGF352hTe64lqstQnx+gzdMZbfJje3u+R+AWFKu1qGP0aVxDMLx5MHYJVljwxe
e2LKUzjkvVRoR0+YtYu9Gj5qdPDMVGd6YIZVf7vkVjqAFAFkwYjJMjO000A17ga3
nDJJFW6/X2EOgjXTHHdwvnojiog7cIrxdiKuVgEgMUb0nVKM/Vhzd6wH7q10q8uU
QdlP3NGYyxdA0EbLrOkgAamHDhAcT28prWjcIR5RwCDMaeTm/9GHAZQhzFBIhYx0
7jSc8K7OKAaSpv3dWp+sp3OSqD05M7X6LPWj8My2Qok7L5oADTiUTQIjSNzJaaK9
Od2EkZfXUewTy7e2ZSjyEHtHmDCtexl4Q+XQiYuMf3Pd6et6qdyts7K5pjMlLroa
hK6DtxjjF701tPMfiP+3j19WMxcA+k0YYdRPRZ2j+OdSo16qUclPaa8kw3CvNzZD
N+4jt2T6bSMWzUWSw9snQJjU7DKn2ZjN1VPrAyQDF81kSZGon+LosbUruuEPNj7q
HT0PDqKwHfBxT6z0XzOPnbiN/BhVUk09nF33wwjPC1DX/K5k8xN8AlFAIojfPsuK
DbVc84/8ZjVc6BG2XjJTf01Xwj7wUY7BnpCWOHxCEJCreZV73RvmV0Dqs8zLXtvS
ud3WkO8G/7LrUtCJI/jtOy542INE/1CxhQwq
=c5x+
-----END PGP PUBLIC KEY BLOCK-----

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by cam72cam** [comment]
@DariuszPorowski It appears that the key you submitted only works for recent versions and not for legacy versions of the provider.  https://github.com/opentofu/opentofu/issues/2014

We will likely revert this change until the additional keys are provided.

**Comment by DariuszPorowski** [comment]
Hi @cam72cam 

Can you share more details about "legacy" version? Not sure how it's related to azuredevops provider? azuredevops uses a different key than this.

**Comment by ollevche** [comment]
Hey @DariuszPorowski!

We gathered more info on this issue and let me share what went wrong. We support keys on per organization (namespace) basis. It is currently not possible to include a key for the `microsoft/fabric` without affecting `microsoft/azuredevops` provider (and any other providers under `microsoft` namespace).

OpenTofu Registry supports multiple keys for each organization (namespace) so currently you need to submit keys for all the providers you have for `microsoft` namespace.

Do you think it is something you could do?

**Comment by ollevche** [comment]
BTW we have an issue to catch such types of problems before the merge: https://github.com/opentofu/registry/issues/356.

**Comment by DariuszPorowski** [comment]
Thank you @ollevche for the explanation. Now it's clear.
I will give a try to collect all, should I submit them 1 by 1 via issues?

**Comment by ollevche** [comment]
@DariuszPorowski I think 1 by 1 via issues is a preferred way of doing that unless you have too many keys. In that case, we can help and submit them manually.
