### ISSUE TITLE
Missing terraform-provider-google and terraform-provider-google-beta version

### ISSUE THREAD

**Issue by wyardley** [opentofu/registry#1009]
### Thank you for reporting an issue.

Similar to #939, #659, etc., `hashicorp/google` and `hashicorp/google-beta` releases 6.4.0 and 5.44.1 don't seem to have showed up, despite having had the bump versions job run multiple times since they were released.

```shell
% curl -s https://registry.opentofu.org/v1/providers/hashicorp/google/versions | yq '.versions[0].version' 
6.3.0
% curl -s https://registry.opentofu.org/v1/providers/hashicorp/google/versions | grep 5.44.1
```

### OpenTofu Version

```shell
OpenTofu v1.8.2
on darwin_arm64
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_version = ">= 1.8.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "6.4.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "6.4.0"
    }
  }
}
```

**Comment by cam72cam** [comment]
Taking a look now

**Comment by Yantrio** [comment]
We currently sync every 4 hours: https://github.com/opentofu/terraform-provider-google/blob/main/.github/workflows/fork_sync.yml#L5

I'll make an action to increase this frequency.

**Comment by wyardley** [comment]
Within expected tolerance, also, I hadn't realized they had to be rebuilt within opentofu/terraform-provider-google* first.
Thanks for the explanation.
