### ISSUE TITLE
Module: makandra/terraform-aws-state-storage 

### ISSUE THREAD

**Issue by ghost** [opentofu/registry#1019]
### Module Repository

makandra/terraform-aws-state-storage

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by ghost** [comment]
Im working on the version issue and release one

**Comment by ghost** [comment]
I added a version now, sorry for that hiccup

**Comment by ollevche** [comment]
@RubenMakandra no problem, thank you for the submission!
