### ISSUE TITLE
registry API and Search website reporting different versions of AVM modules

### ISSUE THREAD

**Issue by chopeen** [opentofu/registry#1024]
### Thank you for reporting an issue.

API reports `v0.3.0` is the latest version of [`avm-res-cognitiveservices-account`](https://search.opentofu.org/module/azure/avm-res-cognitiveservices-account/azurerm/latest) and that is expected:

```bash
$ curl https://registry.opentofu.org/v1/modules/azure/avm-res-cognitiveservices-account/azurerm/versions
{
  "modules": [
    {
      "versions": [
        {
          "version": "0.3.0"
        },
        {
          "version": "0.2.1"
        },
        {
          "version": "0.2.0"
        },
        {
          "version": "0.1.1"
        },
        {
          "version": "0.1.0"
        }
      ]
    }
  ]
}
```

However, the Search website is stuck on the previous version:

![image](https://github.com/user-attachments/assets/d5684d8d-cdee-4227-94f9-8b50bcbc761e)

Why is the Search website not in sync with the API?

Another module with a similar issue is [`avm-res-operationalinsights-workspace`](https://search.opentofu.org/module/azure/avm-res-operationalinsights-workspace/azurerm/latest).

### OpenTofu Version

```shell
OpenTofu v1.8.2
on linux_amd64
```

### OpenTofu Configuration Files

```hcl
module "avm_res_cognitiveservices_account" {
  source                = "Azure/avm-res-cognitiveservices-account/azurerm"
  version               = "0.3.0"
  location              = var.openai_deployment_location
  resource_group_name   = data.azurerm_resource_group.rg_mgmt.name
  name                  = local.aoai_service_name
...
```

**Comment by Yantrio** [comment]
Hi, We are currently only updating modules and providers sporadically during the beta period. I'll enable updating this module soon.
