### ISSUE TITLE
Provider request: mixpanel/multirotate

### ISSUE THREAD

**Issue by allevimi** [opentofu/registry#1027]
I don't know if I'm allowed to sign DCO, as I'm not owner of that provider; I also don't understand a lot of licenses, it is a MPL 2.0; here it is [repo url](https://github.com/mixpanel/terraform-provider-multirotate)

I can fill out the request form directly if it's allowed.

**Comment by ghost** [comment]
@allevimi we have removed the DCO requirement, please fill out the form with the provider.
