### ISSUE TITLE
Flux provider unable to handle conditional git configuration

### ISSUE THREAD

**Issue by safonas** [opentofu/registry#1028]
### Description of the feature you are looking for.

The Flux provider is unable to handle a conditional git configuration in the provider block. When attempting to use a ternary operator to set different git configurations based on conditions, the provider throws a "Value Conversion Error".

Provider Version: 1.3.0

## Code Snippet:
```hcl
provider "flux" {
  kubernetes = {
    // ... kubernetes configuration ...
  }
  git = var.use_minikube ? {
    url = "/ermine-k8s"
    ssh = {
      username    = ""
      private_key = ""
    }
    branch = var.flux_git_branch
  } : var.flux_gitlab_token != "" ? {
    url = "ssh://git@gitlab.com/${data.gitlab_project.this[0].path_with_namespace}.git"
    ssh = {
      username    = "git"
      private_key = tls_private_key.flux.private_key_pem
    }
    branch = var.flux_git_branch
  } : null
}
```

## Error Message:
```
╷
│ Error: Value Conversion Error
│
│   with provider["registry.opentofu.org/fluxcd/flux"],
│   on flux.tf line 51, in provider "flux":
│   51:     git = var.use_minikube ? {
│   52:       url = "/ermine-k8s"
│   53:       ssh = {
│   54:         username    = ""
│   55:         private_key = ""
│   56:       }
│   57:       branch = var.flux_git_branch
│   58:     } : var.flux_gitlab_token != "" ? {
│   59:       url = "ssh://git@gitlab.com/${data.gitlab_project.this[0].path_with_namespace}.git"
│   60:       ssh = {
│   61:         username    = "git"
│   62:         private_key = tls_private_key.flux.private_key_pem
│   63:       }
│   64:       branch = var.flux_git_branch
│   65:     } : null
│
│ An unexpected error was encountered trying to build a value. This is always an error in the provider. Please report the following to the provider developer:
│
│ Received unknown value, however the target type cannot handle unknown values. Use the corresponding `types` package type or a custom type that handles unknown values.
│
│ Path: git
│ Target Type: *provider.Git
│ Suggested Type: basetypes.ObjectValue
```

## Steps to Reproduce:
1. Set up a OpenTofu configuration with the Flux provider
2. Configure the `git` block in the provider to use a conditional statement (ternary operator) to set different configurations based on conditions
3. Run `tofu plan` or `tofu apply`

## Additional Context:
The error suggests that the provider is unable to handle unknown values in the `git` configuration. It seems that the provider is expecting a specific type (*provider.Git) but is receiving a different type (basetypes.ObjectValue). This issue prevents users from implementing dynamic git configurations based on runtime conditions.

## Expected Behavior:
The provider should be able to handle conditional git configurations, allowing users to set different git setups based on various conditions (e.g., using Minikube vs. GitLab).

## Actual Behavior:
The provider throws a "Value Conversion Error" and is unable to process the configuration.

Please let me know if you need any additional information or clarification on this issue.
```

This bug report provides a comprehensive overview of the issue, including the necessary technical details and context for the provider developers to understand and investigate the problem.

**Comment by ghost** [comment]
Hi @safonas thank you for the issue. Provider issues need to be addressed by their authors, the OpenTofu team can't fix them. Please open your issue on [this repository instead](https://github.com/fluxcd/terraform-provider-flux). Let us know if we can provide further assistance.
