### ISSUE TITLE
Indexing race condition

### ISSUE THREAD

**Issue by ghost** [opentofu/registry#1032]
### Thank you for reporting an issue.

The registry currently has a race condition when not all artifacts are available for a provider release yet (see #1030). The indexing should inspect the SHASUMS file and make sure that all files are present.

### OpenTofu Version

```shell
N/A
```

### OpenTofu Configuration Files

N/A

**Comment by ghost** [comment]
Question: this is a rare case. Do we solve it here or in libregistry pending a switchover?

**Comment by cam72cam** [comment]
It's a few lines of code here, whereas the libregistry switchover is a much larger change.

**Comment by cam72cam** [comment]
This is a bit of a tricky situation.  Not all projects are setup to correctly produce the checksums file, which we saw in the hydration process.  The logic we have currently is to only fail if there are zero targets provided.

I think I've got an idea for a workaround, but I don't love it.

**Comment by cam72cam** [comment]
The more I look at this, the more it looks like a checksum was uploaded early.  We generate all possible files from the checksum data and don't actually inspect the release beyond there.

**Comment by cam72cam** [comment]
Given that a release was published with a incomplete checksum file, we did the expected thing and indexed what we could.  We don't know what architectures are intended by individual provider releases vs what they actually released.

I'm going to close this as IMO it's not a bug on our end.
