### ISSUE TITLE
Provider Request: bpg/terraform-provider-proxmox

### ISSUE THREAD

**Issue by automatorz** [opentofu/registry#1060]
### Thank you for reporting an issue.

Hello,

I tried requesting a new provider, see: https://github.com/opentofu/registry/issues/1059

But the bot closed it and said it exists. If I search for this on registry.opentofu.org, though, I can only find **telmate/proxmox**, so I'm not sure if this is a bug with the bot (that it think that repository exists, when it actually doesn't) or with the registry search (that the repository actually exists, but I just can't find it).

Any help would be much appreciated.

### OpenTofu Version

```shell
OpenTofu v1.8.2
on linux_amd64
```

### OpenTofu Configuration Files

```hcl
// Snippet of HCL that can be used to help reproduce this problem
```

**Comment by ghost** [comment]
Hi @automatorz thank you for the issue. The search.opentofu.org is currently still in beta and not all providers are indexed yet. You can use the provider in OpenTofu and the search indexing will be done within the next few weeks.
