### ISSUE TITLE
Provider Key: terraform-provider-alz

### ISSUE THREAD

**Issue by matt-FFFFFF** [opentofu/registry#1065]
### Provider Namespace

Azure

### Public Membership

- [X] I have made my membership public

### Provider GPG Key

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBGTKfZABEADywaGrrjQ/SN5xfOJ+T0JwzpqliqxC7rYyHXCjJMct95pasXk/
NGIl0yKWh3DACHb01l8iw6H/YA/1Zt5ykxjkIFGSzgXRQ4iPdkqolWsCXtm8RLEP
yEFZ+htEBYjqEYZiPcSXMIzg8KbGD0TaTsQFnrshOg4zko5kuYi/GQmV2bACAK7Y
WcsykY+txBBjuMugswNPZC6WtEt2dWZd9A4MARNHOPWpThE1z3ZjepaPHdevUO6w
Nlt+o90XQ4kRwzaS/2u5Rf7NvOJVb0jPzfTDLzXe4jxjmU3p60+SkFkQhk8lga9M
ZHqgDkOdmRBBtj1rkcVEtctdHg2UN99M60y8J5fJG8isI8wxqxESoEaaBHzcaD+y
+8g+/FcTnzXUnAh7yiE0rm2Dm+5mjCGPROWpOpFJvUnEolIUdfsVycV/vPPEB97L
TPj0ez7Mdk0h4fUJCYJCixLfBFb5UzgilDzlMds97s04Fl8p9fvMw70qZct1SRyL
bp1LpnOX8XTsuRvWZGIyErMlO+kr/kK4Xs7tkJAJojEAfzbGdjslBw57zgLTks0Q
reKtW668z5ACN6Em9jFsir6QaHGPUP71rNpJ6J65EoILKGCVHY9/MBKIqboYIBXx
rgvSsiRvfDL7Eb7ogwZFW6aTC8LD+BppLTPxaQ3Bba9BXiV2KNBFMKMi6wARAQAB
tC9BTFogVGVycmFmb3JtIFRlYW0gPGFsenRlcnJhZm9ybUBtaWNyb3NvZnQuY29t
PokCTgQTAQoAOBYhBCUADLeIRIvdg4JPVaPiqS67MmuFBQJkyn2QAhsDBQsJCAcC
BhUKCQgLAgQWAgMBAh4BAheAAAoJEKPiqS67MmuFsrgQAJjB51xNXsq62VNmTslY
f33OkwrcpxgeliOTjZ8YVNt1uOak+JNdZyDvaf6ikBD0Jl9b3/1xxM8T0q7e8s4e
ZIAue5b6jksGmP5dSENOX5ZK8WDDnrte+6QwGh8VLBuG0CMyHL1qLaB7H60pvq5M
WwissI6hNPpOkKoJYC9rM435XeOK/BrD6pb6vjWX3GXczXVM49gJiBDhwBC4+yp4
rUmVuCKfyJSiGKlx1XNCnauyR2JN6lFb0R7KLC+ofQkSvM3LUQ+wzdTibiRGcQsn
0c8j3oZQUyJdQ3ysNmEvqqXEikOOdt7/5XGMopO/9zyo3kmuA1FyhE8NCNyCr5IK
OZSlS6OV9bGFJfRMRUR0KyaL+of1gtOZqX3mnYbqWqMsCe+kB0+LC5HJfSh4wfu4
IG9Z+jZkutoOYA+AlMbX+iCF92yaFkohcg22hjUEBFg49Cx+m/BRX/b+ZyfbzYah
7yPoRGa6g0o3gabjj3jhv7HgNSNDvIlLQuLXCEHgZkuvnFnRPwr/p20qixsOeVWa
PGOhlRiah4pXpUqdj4ewN8ciejtJKp0VnPf70cQu9JbAu5HTc48ahiI+wpwwQyu3
8lvTqHM68KOdMgYuahV5Gt/TOyrI9dt+OMmH7jSmvzPKDFg1ar/pznyStIbNAFIU
1ImtfjKkUWxoqwQ2se5/K2fMuQINBGTKfZABEADzlf7/oHB6BGTGAULkCgzlHIup
ufjNlZikTRSKhmlR6SQeeG9hoA95OLBTnp7wUjS2FMU2DPpidycA3l00GcTT8XWj
ZvxKdx5wLlGwuwZWyeW6vmcxcfXKQJc1A6h5jyzYx9wUj85u2UBKPp7smZfBG8qU
iSylfTWGcK3vFb5Hmxel9SW8mjxMFyaMvnz9nR5TJ73u5bjfdPjVlYImzVM3g2V7
ZFCr8Ov5QLONZSWNrVQgIBFUiWZVbUbBoBIJR/dBn6gkieqtlYl8LD0LHW84ncWn
I7HXGjinDYk/kAmv6PnOsM3E9FFgzg40wTwAvosS8ZQcyPGubIt+MjvPu2Vq5Utw
jHmR+fzhajg2LJkTiHbJ2LvJy1D+F5HCbJhHQuF0G7zcTqhqdwwLv5C2dBfsG+Ui
essY5uPHY1JvAwZpWoTvy0Uv0fE+UaeWAPW3/sxeTFZ+A8zWDu1AYl22uJzwOPrB
NMF3pS5XIcS9vTpClTY7RUtdLKKKHJr89FvlqJy+9MRpVpXe+BkPbtzY/5VjNuJf
XTPLAq0/RjftdB5B3yShkOF3UlhKdYtmfrudREjJ5UAom4JCQutdonEbB/pFZ8WL
2n9iWAjbpAzZ82uBrrVCf51vZ3aXRU3AYLW6eM6hIs/X/OOpCHbM5BhGD1dbwVWM
smK7UrLnZaY+eNR1iQARAQABiQI2BBgBCgAgFiEEJQAMt4hEi92Dgk9Vo+KpLrsy
a4UFAmTKfZACGwwACgkQo+KpLrsya4VY5RAA7CUouNszbNYFqpEQDEGnaXNnslwd
V8CTjKIU3eHH4VGeylCPhqn6VqGTKz+TYIBq8cjmSQL7wwTfaQ+h26DBlzR1PW3A
/j1/JBpAvrkGOATs1zh5h6xwKnd3iviq/jmsYXtCLQZTyTNKHfrbjcdnOOhB3Yny
QGCJgbtmtA39teTcEaPd63X8mQA7tjOM1RFeuoIQOjVteNHLvo/vO31bBtNjC3xb
3JIQQxbWPdqGFnQsas8oLEHlF8EpUDTaGIdcqAyBvaTyc1xKzscC7xapLXVZY8nk
EsQiwIUaIQwsyAVUCtnvqOX2JrcoC5fjpvbFwMROk6dL5hKL/IgOaNCcQkK4ot5Q
Oi2ofQohKA1zmtbbbbld97Q+BlFn+dKs/sB3GR8yqhQrTHKnLLgY+dQVeg843V73
xt3QEPoZo+QRBt4eDIO7qwg9yjzsHAfNyZ7oGlLvyKqqEKVHMVsuK1sLRj+GzUR4
7prr244c6yPIum5W85OHV2qeWO47eGj5pl+XXQK6E974+SWQpyVqbgapVRUdkg0D
8HxkunJZ3F5VtD7TJOe1QAfCf68Xhgy7D3cERAGwwRShEG4bfHDdxydQzJPsyMFZ
E+zJMBkCOnsvQKt6xBL7wKoQDhzLMeEq6b08+BhrDKIpcCf6mGWAqBsLYvyT/YF9
9izhagjG82L+sOU=
=87Tk
-----END PGP PUBLIC KEY BLOCK-----

**Comment by matt-FFFFFF** [comment]
ref: #920

**Comment by ghost** [comment]
Hey @matt-FFFFFF thank you for this submission. Does this cover all providers in the Azure namespace?

**Comment by matt-FFFFFF** [comment]
No, this is just for this specific provider - see #920

**Comment by matt-FFFFFF** [comment]
Given code signing requirements, we will not be able to use the same key for all providers in Azure

**Comment by ghost** [comment]
Thanks @matt-FFFFFF . We can support multiple keys per namespace, but we have to have all keys for a namespace otherwise the providers without a known key will result in a failure.

I'll take this up with the core team and see if we can get per-provider keys prioritized.

**Comment by c-baumgartner** [comment]
this would be awesome to get some prioritization for this feature, because I am currently stuck in a situation where I cannot use terraform 1.6+ because of the licensing topic and for this project / solution I need this provider.

Because of this situation I raised an issue @Azure/alz and matt-FFFFFFF almost immediately opened this issue ❤️

**Comment by ghost** [comment]
@c-baumgartner you should be able to use the provider now, you just won't get the benefits of GPG signing.

**Comment by c-baumgartner** [comment]
@abstractionfactory thank you very much - indeed the init part now got through but I think you did not want to affect the other providers in the azure namespace too, didn't you? Now this is the init output:

```text
Initializing provider plugins...
- terraform.io/builtin/terraform is built in to OpenTofu
- Finding hashicorp/time versions matching "~> 0.9"...
- Finding hashicorp/azurerm versions matching "~> 3.0"...
- Finding azure/azapi versions matching "~> 1.14, 2.0.0-beta"...
- Finding azure/alz versions matching "~> 0.13"...
- Finding azure/modtm versions matching "~> 0.3"...
- Finding hashicorp/random versions matching "~> 3.6"...
- Installing azure/modtm v0.3.2...
- Installed azure/modtm v0.3.2. Signature validation was skipped due to the registry not containing GPG keys for this provider
- Installing hashicorp/random v3.6.3...
- Installed hashicorp/random v3.6.3 (signed, key ID 0C0AF313E5FD9F80)
- Installing hashicorp/time v0.12.1...
- Installed hashicorp/time v0.12.1 (signed, key ID 0C0AF313E5FD9F80)
- Installing hashicorp/azurerm v3.116.0...
- Installed hashicorp/azurerm v3.116.0 (signed, key ID 0C0AF313E5FD9F80)
- Installing azure/azapi v2.0.0-beta...
- Installed azure/azapi v2.0.0-beta. Signature validation was skipped due to the registry not containing GPG keys for this provider
- Installing azure/alz v0.15.0...
- Installed azure/alz v0.15.0. Signature validation was skipped due to the registry not containing GPG keys for this provider
```
The signature validation was skipped for 

* `azure/modtm`
* `azure/azapi`
* `azure/alz` (the actual patient 😄 )

**Before** your change the init output looked like this (you can see valid signing key ids for `azure/modtm` and `azure/azapi`

```text

Initializing provider plugins...
- terraform.io/builtin/terraform is built in to OpenTofu
- Finding hashicorp/time versions matching "~> 0.9"...
- Finding azure/modtm versions matching "~> 0.3"...
- Finding azure/azapi versions matching "~> 1.14, 2.0.0-beta"...
- Finding azure/alz versions matching "~> 0.13"...
- Finding hashicorp/azurerm versions matching "~> 3.0"...
- Finding hashicorp/random versions matching "~> 3.6"...
- Installing hashicorp/time v0.12.1...
- Installed hashicorp/time v0.12.1 (signed, key ID 0C0AF313E5FD9F80)
- Installing azure/modtm v0.3.2...
- Installed azure/modtm v0.3.2 (signed, key ID 6F0B91BDE98478CF)
- Installing azure/azapi v2.0.0-beta...
- Installed azure/azapi v2.0.0-beta (signed, key ID 6F0B91BDE98478CF)
- Installing azure/alz v0.14.0...
- Installing hashicorp/azurerm v3.116.0...
- Installed hashicorp/azurerm v3.116.0 (signed, key ID 0C0AF313E5FD9F80)
- Installing hashicorp/random v3.6.3...
- Installed hashicorp/random v3.6.3 (signed, key ID 0C0AF313E5FD9F80)
```

**Comment by cam72cam** [comment]
@matt-FFFFFF, we should have support for the provider specific keys merged in early next week.  We had a perfect storm of PTO and sick leave this week and have not been able to get https://github.com/opentofu/registry/pull/1082 merged.
