### ISSUE TITLE
Is the microsoft/power-platform provider available in the OpenTofu registry?

### ISSUE THREAD

**Issue by jmservier** [opentofu/registry#1091]
### Thank you for reporting an issue.

Hello OpenTofu team,

I am currently migrating my Terraform setup to OpenTofu and have encountered an issue while trying to use the microsoft/power-platform provider. It seems that the provider is not available in the OpenTofu registry, as I receive the following error during initialization:

```
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
microsoft/power-platform: provider registry registry.opentofu.org does not
have a provider named registry.opentofu.org/microsoft/power-platform
```

I would like to confirm whether the [microsoft/power-platform](https://registry.terraform.io/providers/microsoft/power-platform/latest/docs) provider is currently supported in the OpenTofu registry, or if there are plans to add it in the future.

Additionally, if it is not available, are there any alternative providers that can be used for managing Power Platform resources in Azure?

Thank you for your help, and I look forward to any guidance you can provide.

Best regards,

### OpenTofu Version

```shell
$ tofu version
OpenTofu v1.6.1
on linux_amd64
```

### OpenTofu Configuration Files

$ cat providers.tf 
provider "powerplatform" {
  use_cli = true
}

**Comment by cam72cam** [comment]
It is not currently in the registry, I can submit it now.  In the future, you can try to submit a provider via https://github.com/opentofu/registry/issues/new/choose, which will auto-close the issue if the provider already exists.

**Comment by cam72cam** [comment]
https://github.com/opentofu/registry/issues/1092

**Comment by cam72cam** [comment]
@jmservier Provider entry added, should deploy within the next 15-20 minutes.

**Comment by cam72cam** [comment]
For reference, we scraped GitHub looking for providers 10 months ago.  Any providers created since then need to be manually registered with OpenTofu like I have done here.  I'll bring up automating that process with the team next week.

**Comment by jmservier** [comment]
Thanks that is perfect
