### ISSUE TITLE
Module: terraform-data-duo-ips

### ISSUE THREAD

**Issue by captn3m0** [opentofu/registry#110]
### Module Repository

https://github.com/captn3m0/terraform-data-duo-ips

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by ghost** [comment]
Hi @captn3m0 did you run into any issues with the registry with regards to this module? Please let us know if we can help.

**Comment by captn3m0** [comment]
(This is an experience report)

I found https://opentofu.org/registry/, which said 

> In order to view the catalogue of providers / modules, or if you’d like to submit new providers / modules, please head to https://github.com/opentofu/registry/.

But I couldn't find a catalogue in this repo.

Further, I created a submission (this issue) because the https://opentofu.org/registry/ page said so, and the bot replied back telling me that the repository already exists, but again linking back to the repo URL, not the registry URL, So it seems that my module is already included in the registry, but there's no clear URL or a way for me to check the bot on my own.

I understand that the [Registry is still WIP](https://opentofu.org/blog/opentofu-release-candidate-is-out/#the-registry-challenge), but there could be some minor changes that can fix this confusion. Suggestions:

1. Fix the messaging at https://opentofu.org/registry/ till the catalogue is up
2. Update the CONTRIBUTING.md file in this repo to account for module submissions. Clarify what (if any) modules were automatically imported from the TF Registry - just having a list would be nice.
3. The [Submit Module](https://github.com/opentofu/registry/issues/new?assignees=&labels=module%2Csubmission&projects=&template=module.yml&title=Module%3A+) issue template could account for this as well.
4. The GitHub Actions auto response should include the registry URL for the module.
