### ISSUE TITLE
Unable to use temporalio/temporalcloud provider due to registry indexing delay

### ISSUE THREAD

**Issue by Paul-Weaver** [opentofu/registry#1107]
I am still encountering issues using the `temporalio/temporalcloud` provider, even though it exists in the registry.

When running `tofu init`, I receive the following error:

```
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/temporalcloud: provider registry registry.opentofu.org does not have a provider named registry.opentofu.org/hashicorp/temporalcloud

Did you intend to use temporalio/temporalcloud? If so, you must specify that source address in each module which requires that provider.
```

An earlier issue ([#1106](https://github.com/opentofu/registry/issues/1106)) stated the provider exists but hasn't been fully indexed yet. However, this is still blocking progress.

**Steps to Reproduce**:
1. Use `temporalio/temporalcloud` provider in a configuration.
2. Run `tofu init`.

**Expected Behavior**:
The `temporalio/temporalcloud` provider should be retrieved and initialized.

**Actual Behavior**:
The provider is not being found, and I receive an error about the missing provider.

Please provide a solution or workaround while waiting for the registry to be updated.

### OpenTofu Version

```shell
OpenTofu v1.7.2
on darwin_arm64
```

### OpenTofu Configuration Files

```
terraform {
  required_version = "~> 1.7.2"

  required_providers {
    temporalcloud = {
      source = "temporalio/temporalcloud"
      version = "~> 0.0.11"
    }
  }
}

provider "temporalcloud" {
}
```

**Comment by ghost** [comment]
Hey @Paul-Weaver it seems that somewhere in your code you are using the `temporalcloud` provider without an alias set up. You can see this from the error message referring to `hashicorp/temporalcloud`, which is the default namespace.
