### ISSUE TITLE
Provider: infobloxopen/bloxone

### ISSUE THREAD

**Issue by davidgarvey** [opentofu/registry#1108]
### Provider Repository

infobloxopen/bloxone

**Comment by davidgarvey** [comment]
~/BloxOne/dns-bloxone/terraform-bloxone  tofu init                                                                                         

Initializing the backend...

Initializing provider plugins...
- Finding infobloxopen/bloxone versions matching ">= 1.3.1"...
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider infobloxopen/bloxone: provider registry registry.opentofu.org does not have a provider named
│ registry.opentofu.org/infobloxopen/bloxone
│
│ All modules should specify their required_providers so that external consumers will get the correct providers when using a module. To see which modules are currently
│ depending on infobloxopen/bloxone, run the following command:
│     tofu providers
│
│ If you believe this provider is missing from the registry, please submit a issue on the OpenTofu Registry https://github.com/opentofu/registry/issues/new/choose
╵

**Comment by ghost** [comment]
Hi @davidgarvey please submit the provider as `infobloxopen/terraform-provider-bloxone`.
