### ISSUE TITLE
Provider Key: terraform-provider-equinix

### ISSUE THREAD

**Issue by cprivitere** [opentofu/registry#1111]
### Provider Namespace

equinix

### Provider Name (Optional)

equinix

### Public Membership

- [X] I have made my membership public

### Provider GPG Key

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBF9PkJcBEADM4drbXQBuVi02LFiqcyBYmoqiyEZ/FNlKiTiKkCRf34QE1v8X
e8kxgmS5VD+gBC80zVLDBIGDzSoMmqWC2bN9eoy9w1aUeTuFTt3H4+YUmwPxtjSG
gB2ozLXjcIChAMQtvtlX5jzEECpVU6IpDvN/jtosDG4ZGLbg+vRHgAP7XRfQn9LB
mxBZQnIEv9duNd5LSz5VvNqeSDGbdIei256lQdLb05RY7I7hQZz4AYNKAxPlJ5kg
14HyYgQEsBYKYIIAh4aur+X/cauHSK6mJYqeRxQmqYuUQVuP4J0GJirEQgo42xAI
jsZtSR/32s7x8k+BkYkKMi5h88X22j58pYchmy18FMgFhDpXrl5aZPA2AZCNJvhO
ej1wiSqzEG7kF0etuuysHA1ToDpFAC8BZLgHeJfB7Dd7/DJ03P++9mEJbDiJaN6x
dplj+9+ZJLIJbdPQTdxy3Qg7GCstahxR31d+wZKliewG0rsH5zqem/TtTrg/Fp6/
DSGorARuk3Sa9bL6PbjdCkXn/GqnPVIhaZt5oYsIJMWbyVObk/ZbGKBaw4w6J9NL
GDJ1p0+ByYYPLGfSxSBLz1JNJpACGh47DtzMgIM/g3vUvOkCzFvAhEG9WyrZ0Qgq
9THYUdaWB1iBJi1ODpKtuSK9FcQbjegSYCS4vwpv+PHwk4Ht3FtzX38qkwARAQAB
tEJFcXVpbml4IERldmVsb3BlciBQbGF0Zm9ybSBUZWFtIDxtaWtvbGFqLnN0ZWZh
bmlha0BldS5lcXVpbml4LmNvbT6JAk4EEwEIADgWIQTP0JAXdt6O2B+B4xIaZWMc
cohoXgUCX0+QlwIbAwULCQgHAgYVCgkICwIEFgIDAQIeAQIXgAAKCRAaZWMccoho
Xh8UD/9Z0IHsehSUB60TLrBrJyVs95a5pcWQVogL4be99OyL3vw1yiN/SDCMTutQ
9KTvOyClnn4f89215sn6VwfYPidfC9smNj8swmRSacJnqY1ileYHxlMP8i0s2Py1
10etDXVN7BePkjUMr6FqVRAGCsaXNXqZ04cl2OYseuaeayq7WwCF9hhuaHihdq1K
UC4D4MS4x1h7rYmzB5rqABlU3A0GAtkMoWZ+SZ7DYO1v3pJzEvf1s0XXraBuoZ0w
gYKASbVvEdhZ+R/AG0nSXLdQW+nlDMTho1rzpvohHKOgWcgfrUSh79gtcBDmx0Ak
fpUdqWvrUOvjVDScubnR+i444vxacjE3srthk1ixEKInyE9rk3pZaPvE5W7pydSt
Ct+51FZrb+8BmqIV/k/qpZYCFy1UlGVm/XNiwgQDlyDMoWTKZjWvJbGTM07b5oDH
/yqcfCvRMSfMDuJCb1W1l6LmIwPmLGk96J8hJpQb3aHlOyje4oc4I/rdv2TPjZSL
qAYlj4I9h8LqqL+XRtUBU7aHL4qTP2UrAO2DMtWUZFoE0Jo1cpF+OqiYGHQGlbdF
mi0UqamY92UtX4cNpA6UPphuHhNrMy8sTcuyNic0DDsA4bcTsC2FtzYY0igc5ZMI
1VlcIfs5OtMEDPBi2bMSR55eicuy7wDRq4noM0U+DNDLQttM0bkCDQRfT5CXARAA
5TAjaiy1hYM9xbWx+ZBmsaDB8aoagwoHfdSIinqcPLRQrwgQO88OMBEXT/wE9/LL
5SfQ5m4q1NUcpDlpEa5/rpqjXXEJI108kb1EhkGL22Hjt07bWnYqZ+RA1ShAmDnX
Y/ybcTnouQIxgzwgWEPZizOoQWj5Dc3TLiJ6d2d4p2M7gop+SiHYYdgt9OUkD0Uw
f6axkv0OvDlVG4jEnBT+jlf8bwtnvfxfmWV13r6mGS5nQt8w5/Jm3hOmUBFYBppX
oKFpFYNis63h8aGB9qklpEo/HD2QhnuRHL2t6z6Ora2ydyNmlEn2p+9ZcIaJAJHJ
c+qQ5flD40UZcmvJ/tZUHRa7A4PEypfGsBnLnIDVRtY7+lka0VAneTWapQscY2HG
xjj/sotpDQ6ht6S1O3ifZ4pMmcj0HlJo0b0AwOsnUqa5uq8FHY1FjrdulZ4QXcTP
LYs1HsowaGm2073H8FesYhz9ue2BNdB+O0qXukK6gPuMs6ZBy433VmjbdCmhdd/5
MYZ2T2cxNZDjpCG30vh9qz2xLBYvuSVpxkaGaPkfvXOBWClFByDCK6dvsFmlJnsp
EOatdJTk56lVVjXc2oHFi4LZ4GHxPV1TAByIIauw3PQ4usG0jDVl/luN/dtpBn0d
iamiw/1Fr2mmU/k8gHe3OC5vkXO1t2Zmrw8KC4YuVisAEQEAAYkCNgQYAQgAIBYh
BM/QkBd23o7YH4HjEhplYxxyiGheBQJfT5CXAhsMAAoJEBplYxxyiGheL+oQALN+
K+VYgGUwPxIFn4aqj+k+FAYY4IJjzPtRZv5HaBGX/IbSEai8pqyF6hZfJr9bPPJ2
tVp27fkazhFcd+5PvmRvY+Bz73Z31cL/aDACNwjNDhHvNWTAGZFCQvrEfHqEjYCO
QleirfLkoIlw9rf7dYDWW62NKDot7JamR7wpSVpnXgSUwBDt78KikEpTH/2lYlEz
NI8A7aJbkEdroJaEsh15LWWnqCsozhjk3+kf3p8q11KWo5YadJ/OfBtLtTS/h1VU
MhxlnnmmrV8aV5rQXNNxUaLhNhd9+3D74mrsq6IIlr694O52YYCsQfaKCPO8YFU9
4GJJyMLH9ws6ayM+JkJVvLy9K+bbxyEuOKkX9162+0vjCnutu98K4HmhQM7PMIss
m6Y4pNN6aFCqWPgIyG7x4unYQjZSEqQHPias1p/77z3A0KAj6tN6oTTuzLo2T5WK
MQr2lumagHGNKuGCL9b5xfBBKg4Yc4TMc5jZRVTYxCcssuDj8HB5JzQkvrkZ3oj/
rnIsbraRT+3JZPn9+Liw8tgzkICaZwIbUWYvtVOfyS5ZeZReWbiiNYvcsTn118If
g86I1SBUenadutkCUrxetcQxz4L2K/EXQf6K8x6kVOcWnR4hCjfHC97A2Fx3+3FZ
w2qONgWkEGfQ1kOS+GTOB95Wd0APJfprhyUVA/8O
=+kPW
-----END PGP PUBLIC KEY BLOCK-----

**Comment by cam72cam** [comment]
Thanks for the submission @cprivitere!
