### ISSUE TITLE
Provider Key:  RafaySystems/terraform-provider-rafay

### ISSUE THREAD

**Issue by srinivasrafay** [opentofu/registry#1117]
### Provider Namespace

RafaySystems

### Public Membership

- [x] I have made my membership public

### Provider GPG Key

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBGDrv6oBEADG0ZGTAii3SnM0LhXRM+GOZNIgHquk/7f1t4vBLSvpVWRvikOy
o9hkqLuMtZDuCrSgR5bi2BrK1YP4oa8zw1OJlojFHQOYMl1WvTfK++K+iYuevdvZ
HwkqG+YIwK5UPVS5PxeIhXIHnRmO0l47nrU4UJnSz1+srIuEjjlxGsg6IoGuqBcf
9LBAQTPyQUtOYnzBPlBKk95+9G+Jnm1jdLpZJFzZ2ust5pNwAOKTZTcihF9hkuhe
OpUIXomElkHJGyhixht5cciOekNJMXSNfHWKpVNi4tKWgDGvDi8YizdXsDz8waO8
5QRLvuxLbeFpUDabKy1GTM2n+bLcaPHZmuPPbZwxifRHKMBysY0wfbWLBx4i19B/
Hu7JGbRBXTJ3dy9MWp8arKlYJNKotm7nOMrHJEe+jD0yUljTCejtZHL9ryS8sX+7
FIrIEvflGfpTAj53qpex9ydLemyhW60v3smI7YM5EjZYDhIhupQuHbdDcGRg4IIm
+mO9CsOIfpMOXyNznjwXY1srZ/mrhmFkeu8qpkfWmT/K9gXK3c9luJxyOQKKR1Gd
gUXBOGZjYZcZWcnS75vazSgv3cWJXCm10hls6749HtWe5JiZ5BitznLyPVu0cg3C
Gt2T/oi717B/z0zxyhVR0Qajzh+0jiP0lXkUOX20vbSC8OPkVk7CwvCM7QARAQAB
tBZyYWZheSA8YmVubnlAcmFmYXkuY28+iQJOBBMBCAA4FiEEl7MoAJJRN8aRnqQO
SdYXhwZBVk8FAmDrv6oCGwMFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQSdYX
hwZBVk8r+A/+Lru8ejG5DFX/V6fcSEK4BQcZB2r7l9myMIsq8m77uqTUtSLKKQV+
2WIw9pZJ8Y7U/dFSTCkyVsEzfIXLZNSNlzJWIzbiVLU3G+XFH4GdZZKbfq37BBOy
9OJZa4TclpmioDDaqVOWHuZYuP0WoFMTP5hNvw/aWU9Q0z7u2dNmcKNlcAfnVhzg
081XE4mhffvIDvQ+qJVGJJChPDkZXJ2dx9FS0N3Fz3AAILvGtwGF+udGxrm1+JOI
5DR0K5I5/BCnnlxWclOT8azg90hoRs2kx+sfgkBsWCZh7dU54uu6Z7xedVwm+Eet
eO0C+PoCcYKvWXRsirOTJGmQ3Y0BoUN8O0BYq3DFN3OdeCEfF1HOS5Bbdx96dHV5
idzleuXGAFr2M0WPxMFsgBvdy7ESqIvTEjHONYUCTU6AuknFdiIqmk0b/ZhiArqB
SDVHrw2ut/clH//sELaxGM0buCs8Xc7f5elituqnqpSQ////BxwQkIpfXr5zfg1e
Zerv7N5ZgrGxh+0+D5UBkzXRAU5pIDPYqoK8eMvhC7+Gszq3otS4obGUe8KZCFtK
Ew1mHw1TsoM7c2xJqvx6IVN/w7eWEkaXumcAtxQG8+FBFobVTCKyrgRtq1lfUeV8
nXvDTnrFllbj7H1Ma7o9qCxWS/txTOdj6UQ/Sas4qhGIwejyNK4ZySq5Ag0EYOu/
qgEQALcvEGEpa/+Rv5zi43/q7dUi6F4HWTXi+khluwrxz79nk2s7gWTY1+MtzAam
myCk/jMi4K5Xhbq7O8rRE6/tKPapIw5M0PV/8mTQRj3O8onvb1/yle2qTWpvCLWW
Rbnh+s7OTnGxVgl+GAbBfDc3zYZUcBh3qb1aIfZSJiEIUfUs3WFyiNilZTstivkW
H3grq3/5iGZz3myoQ5m94GXZlFoXh4C7DhFHspRRB7GA/VP8J4X38+dDnlj8Nw0t
AD+KZdt85vpzkXvSNQ/wIOtFc2iRXstQf0fy/HHeb8Q62Mr/MB21O4iC6HWrVrUL
StZQcmE4QImUHWQYZcbZO9ktL2GZdnjmU6M3+puE4hw7qq1nBaCOJ2skJ0XDdwVq
P+61qReGqP6H7Wf9o0QFqPtCGEU8glGFccYslMuYTi8BUUHAahg0dOZK0QcqF4q1
M8T9cQtk6PPbb8i9lSHCLCBx8olhn4RbRa70Km0l2XfWKpbIvJZmZ4AZwg/ETOOG
ODLeCrzHa+F7ZiF1AJI6JQPOhR2x/4syBeH8ZGWkHjg+m/+/diUqb85zWHPIW4p6
c/zBaP5y4Smiu3CS8mGaJoG/hnVTqsQaBg3RLKtLmGRA2Tvz2RGVlpFVLab30h/i
xBSkmiNZ/m6nVWiskIBWBHD61atqMn3huo1hLrI7xVpGsf8tABEBAAGJAjYEGAEI
ACAWIQSXsygAklE3xpGepA5J1heHBkFWTwUCYOu/qgIbDAAKCRBJ1heHBkFWTyob
D/9GQDtT2yfVSDlk8wThERq5b7kdPNMshVxeEl+0++eUJ/lRIRmity4PNIN7wFo/
GAn7hquw6cbUQK/RrS7UL7xJhpwIeKrHpRSm/CvizEbfZw+D05pVTu5u8x70OKqI
LvtVgrfzq7xRjBcqYU4kK3s74tlVeNBNEqmDFn83M5x+lm4kGbOYco/HLdGT1hmD
Vh9iaOI0uVns7EdDGd3Wwy5pnppJ4++Nsb29K+7+nwXNjdMdzMUBORV7LNIbgTSb
wn50kj2z9D0wxLBYVNgJkF+0LGx1lIQulU15vqGh5VKq/3SgCmqAsdAZ6rkH14pv
Q3VESu2rhQdAPFmq41hOWsA3/AaOe03xjw+nDZ8MSTsVTAhtsQU7m+R4s53vuREo
t0TEEctethZjdHAKDR10GvlMOA4ZbYChWQ58v+hOf4OeT2XcNO4ILWvsdLZlF7o7
3bjcyjz8nsR9B1f8synRKDnXeqfmDtMOcrDGVMZv5trz/0NA+B7yCRAnR/WoHbKL
lPZ5pG4g2DhEiipwdqP59PlsZhEc5ZEcugOGfdY+JHp+bw7m5HDUHiOsplRcG1S9
sJuFn11GXrsbWXEFRXunaF0vwcD/O0eGnSVCup3Bia4oo2GsvlD0Klcx88bK3H4J
/zITSGyDYTSD5dcHz0vV5kaULXSdidYRzf6OnC48FAew2Q==
=fwA1
-----END PGP PUBLIC KEY BLOCK-----

**Comment by ghost** [comment]
Hey @srinivasrafay in order to submit a GPG key, your membership in the RafaySystems organization must be set to public. Please make it public and re-submit the key. Also, please check my comment in #1116, which may be related.

**Comment by srinivasrafay** [comment]
Sure, Thank you
