### ISSUE TITLE
Provider: Incus

### ISSUE THREAD

**Issue by stgraber** [opentofu/registry#116]
### Provider Repository

lxc/terraform-provider-incus

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by cube2222** [comment]
Thanks for submitting this @stgraber! Please also [consider submitting your public GPG key](https://github.com/opentofu/registry/issues/new?assignees=&labels=provider-key%2Csubmission&projects=&template=provider_key.yml&title=Provider+Key%3A+).
