### ISSUE TITLE
Provider Key:  lxc

### ISSUE THREAD

**Issue by stgraber** [opentofu/registry#118]
### Provider Namespace

lxc
 
### Provider GPG Key

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBEzDJtYBEADeY2GjCIHiP69HyT6dea1bcBYKHzGusmPjUGfNExAgseCgkFGo
xROSpjt5ez8FGyvjvSevVTtWTO955eLrhj7fUzfcN8ot+Lj5EeCeyX6evR/jv/Kw
dJZfKNHEKFlsRL74NEodSIvxDxANsu4iggpPWe+RMcZt7yP/4j5j7/yfZHCtDNVe
6vYr6FvR9YmJ1TK3SudKQ0eLYBgW75V45xtgl1dzcTfmmnQKRq0NBgGHQ9P+VdA5
TTaKDxDyVGuGL3eSBABLKiOTVxn8cLK75NOHH920PbOIKAfXh0StvIRbHL0EcwNj
4nrSHHsDqFwQaieVueEpxaL3OfKXlF/4KdkCz8J1fXMiKd7MrOaVCGfriU4J9H3V
2JUPzHCv1QOLlJFkzyfbAh/62xRuUKihqBnLvMStl1wCesbMSAUxZZs2u+emqjD7
wqf7bj5u34bCb/7eBnirBhk7fCPrWeiw+tyr8focN3TB9ZjoFba+lzReP+ehYpFI
15ro7wJ82VvEYw3/UIOyUhGBdGWZzwoag6Y2sm7zY84YGtNV44LsaKpJYZUi7er4
2JQZ6PN68lfkGgTyjd3eFQ4la7pmhOWDZt9ldy8rz8dw0K8gKRP+b5NNmaPznCcM
tg8s+mQqcjWpeqwmq93JrgbxGwgiI2qw9P+dZI0jn+Aoth+DDki3MC6ZXwARAQAB
tChTdMOpcGhhbmUgR3JhYmVyIDxzdGdyYWJlckBzdGdyYWJlci5vcmc+iQI6BBMB
CgAkAhsDBQsJCAcDBRUKCQgLBRYCAwEAAh4BAheABQJMwy5hAhkBAAoJEMY4l01k
eS1nJN0QAJxoakm+pry4OJWuZvJor8sNaEp1UT0m6NODiDTnG1GkQT/JArAdcorF
B97zBBG405dYuPrrDihQEomztFz8N00Qz9F9iJMkPR1nZ8+rcZxTmttmizVO+Z2l
zWpU7IQx/dUlD+9kQTLtIz6L6MfHuULHyUTQPpOx2stXKH1y+vn4zCKpxVBeorRq
oYqMJ1sSNS2w/PV3kK4yr3llB9/pbqbXI2XEydEzF2t5hcKuO2/vxHOVCLx1OBuh
o44ELdNhBDAfH1mssYzda4+ZSX255w9M5LEiqhkcSm/Pl9RDQOGeVzEJ3dHaqA+d
4SrTIS5pmurxRk3Kn+jiJAADP0Ef8juLfgfJIG4TOQI5KBF3XMya5cbKuCDruRIx
QWzzPIyrKOC6mz6KDV/HyYqbDKRV0flaBzfXSzLZb3AbmVYRPjlnuAIOK73HwH7e
XpDCfhY199Ijf2vJMbho8ZtD9nf4imb64RX3wabxMNyPQZSEvleaxD0MRx+0Z/D8
rG3i9oO0I4VpJmqayhVvfbmwoX4uEJlNTBlUIeuRIgLvlsnQm3FFa77ipa0GBsVO
DHmOmvXNY/nbjH5zRrtosauwHWUCeYWoWiKnO9+PaCs2C1jvMN/etx/+UHC3pUoZ
MI+6glbSJEuElAYrcBk2R67gX23ggLldw0pKdYk1CDQ+IXSx/FMVtCZTdMOpcGhh
bmUgR3JhYmVyIDxzdGdyYWJlckB1YnVudHUuY29tPokCNwQTAQoAIQUCTMMuOgIb
AwULCQgHAwUVCgkICwUWAgMBAAIeAQIXgAAKCRDGOJdNZHktZ35SD/434tFecFY6
22NY/YLjQUN++bSvP+mbeCeOXnOULZozURQTuQzneTWFgkPOL7UvRIrw0WznQEwh
UMai7PUF3SbOYcj7iYSXJM6t3aNfW0zmjS185Ny2bRB7URihTAyEeM4Jpk6oMTmh
qmH2OHnFQuNqmCl1tiH44KVv/sQAEzN/txjxj64YSq5NSzkQKlMG/n7QfLL+RhoB
4db1wY8vhnrryP7vUx5DR1A5z9MYfFTIJb75vsQM6r4s3sVtwSTGkozJMUZAs0EX
bI2Tgx2Wd7t2ix21lBu0PDb/RINpXQV0pyhT1kQxa1ZKfpLoM2LRWp6ctqmU+qkr
yaW8cLEHkYmDKEQIgQ7/DrOJPrPgjfBIC9LOcXgI1LbIh1L7tNFAOiOVS/e4C3zx
BowCS4VCWq9m0LrmC531sFF46cmAMhrmtStWqJpn/Yaxn8VmhhTUzIVOUr3gL9Rz
bynYGIiSif+LXsrPLzEaDTGjmKm3oFvDadUHmb6HyuQ0M9UCgLQKkWiOvybx6Q16
doFm61VQsJMqHDSpLBjOc5cSHO9PiXlYzkK0dv8h8e0LG2MORHCJK4s8SfsPAXBC
JwoZufcohaO0DD/fx93ErcAyNlDiwL2TxrQ4wEMHj73lt18A/HqPVpU0zTWDpNDe
/N12a3sfTfs9IdB/izq6k2kTzZwHmqgpKbkCDQRMwybWARAApvNuefvVycI47ABo
T7AzBsHf0lbt4ihMpugZ+GfubzK98kn8pDRprUAfACx6+NLkxuAf9WyL7CFoFLSJ
je1m7ZhYeeNckrF5Ir1VRsF+6DueantQzawL8tq6o/sr+4/F5e0jwpXAbHNKiuqj
Q/DbLVPEmln29aYtJT3Vtm1eVzK2XkxicSlRROKHrGbaGSHEJgWr/7zqNcDPY9Ss
/pms2lqGCWK7MMG/PGVhYIJ9LKNK4yGQtxD51UuruAy6MmRfu1cKDzJ4frQjJTkr
c746uofRzK7F/uTQYFpXXd2uQ2/xi+dRnTyoqszvlS7Cm5/V2AhblbnUVE+gWgcR
lg3WXetJmI/jMwPCYSy1wxWFwZGYs/VTXcimHBcOZWu7cAur8zDNkm6uQaMaFRrq
LmkkLjoY0e8cXZIkcmQfvlWHdDkebQevRvKlNWIJChRXLU7SAKjrIe5y1lxyzy3y
dS8saK1nt7swubf737jHahQkNev9QwZ3r9ZxsyRXXRkXpKOoHQ2MVqyId+6Nk8Pn
/0yE6RPN+t01je/I731fLUZzsCs6y2e5d+xxQzQSTGBiJfxfHodBts3D6r3sxxYn
nvIe3H2Trzv34lNmiwX6RhxqPGiHBSvRxoTXz4luydDKIrBdaN+sgTkMINa3KDhf
VMmbdnwTOQbW2pi3qUCbjA0TI+EAEQEAAYkCHwQYAQoACQUCTMMm1gIbDAAKCRDG
OJdNZHktZxrrD/97bryBoLKJNc4tAtDY8umo+phdL/kUTx9gVeKHpZZVoymHW7pS
3stXC9UJigHuaDjkdvHq1v9fUdIp9mD8uqWgGJNO+hV99ARZSEkXfAFtNHYw0gVi
izz0J0FEmMibJJBjj4kDi9Z/2fWRKsvNfwQ6UKrKtYkkM1DWNnqhNJVDVNJ+4Mr5
Y8wbkItPV07f5L3kdYFE90K08IJh/pvalt383RuNmuqFwNGjStLcfo2YRpTyjmWA
oR7qaGflTAKm0+Qj/vx8vfHu7WAfcdcAT6ftZ5Q7C0LcPPuNkTBGFUyvJwW+7AV5
3Pln6vsbZg451J4iFQ0FTAYys40LbkLKYSAXfvfYHXY9ZOCvoZvsoeDG8zDUEGj5
EnsiJNlJx2xCRwjIrCzujUs91HdxQoVtXWwtlknZNwO46x433+ukhkTGJGQ7YFao
x/JxkvQOhndYJBKm5C1P7ZlLmcRndv7Lrld9rVsYGk4/lCLDPXb/ZJ0jmZLYNqez
2z0Pcd0m+jtbVVuMxuIMI2NOFIccVsQxlrtWCdhnGfs+KH1D1eyLNB7PpzWq01yI
z3pNBo5YYOLovpu0wVB0vxLTkDxmcl4aoM6MGkbnDfK4al+RQ+hDJlCAW+z3hUxH
2CmlO+WHtRJyXqE37QX6y9xmflvckMvo+CB+gopGyzMJuLqkBL2sFHZbI7gzBF3b
RX4WCSsGAQQB2kcPAQEHQOhdeiF51bz5W+mPtpRYnXQRuLqimMPE5PBD1ab8APt6
iQI2BBgBCgAgFiEEYC9WdmPlk7y9FPM4xjiXTWR5LWcFAl3bRX4CGyAACgkQxjiX
TWR5LWcagRAAmQrnjBZVYrK4tqtn/QfLgCM05OZzZISx4ipGyObjhYyBdu4k9XpT
y9wIPocu4aiCLCOjge6xL8HCHz4SJP1i4ffPQI+t6y82DAzMPkQ6weu6700oJWpX
TCfE53f3Kimgok89H1rpd44QQzrIpWIqCtZ7i8iASAZ5F/ZqfhK9eEKF9EbNVVFD
dZc9q5P8kJ0w9C5nWpsfQVq+xEiGe+Jivc8mgWS8Nw2p+FvVL9nuKMSjYCTP6iru
xmoqvc0MB6TbiJsyukYF5oGC24YbwNBl03Xk3lQbZ2PjZ4FOgMYTqtg5fIo44ZAZ
ly+7E/QIOAb8n24+9TjU+vwKNJczsDN58O0PeDAYQMWzidhwCi/qzWGuVTf55xXG
rdHOddlUi/UAcgBrfxKrX0GCzshCs24oPqlyfvCK9ZFj8jopVrVaEEDgSLEPzpl6
RmcNL0yyWA0Boi98E/Ksr27v0F0U5EauPnNZg4BC+ClLw7sjgfUHmS/lTuq0KlMK
XGUhg9sngYDWPgHTRT+jrhEVah+3HV/xl8lqrZ5KIiORZmC1PuoGK5R8m3zxo+5H
fBJWh9UlM/3VKWUgrKdqA3lthXr+wp2TOJ2Tl5xpDTnSnpXttRCrVnvWxtdN+02Z
BCaOsVjqiSepScK2DoEcuMMODED5rlycvarvKZVfayTVlI4tWm7w4JI=
=l/rp
-----END PGP PUBLIC KEY BLOCK-----

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by stgraber** [comment]
Note that I couldn't submit the usual version of my GPG key as it's too large for your form.

```
 There was an error creating your Issue: body is too long (maximum is 65536 characters). 
```

So I had to to a manual minimal export from gpg, hopefully that still works fine.

**Comment by stgraber** [comment]
@cube2222

**Comment by cam72cam** [comment]
I'll be taking a look at this shortly.

**Comment by cam72cam** [comment]
Thanks for your patience @stgraber
