### ISSUE TITLE
Problem with the `infiscal/infiscal` provider

### ISSUE THREAD

**Issue by StamenchoBog** [opentofu/registry#1195]
There is some problem with this provider since I cannot see it in the registry of OpenTofu (registry.opentofu.org). Also, when I try to query it from my local machine with the commands `tofu init`, it displays the following error:
 
```
 Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/infiscal: provider registry registry.opentofu.org does not have a
│ provider named registry.opentofu.org/hashicorp/infiscal
│ 
│ All modules should specify their required_providers so that external consumers will get the correct providers when using a module. To see which
│ modules are currently depending on hashicorp/infiscal, run the following command:
│     tofu providers
│ 
│ If you believe this provider is missing from the registry, please submit a issue on the OpenTofu Registry
│ https://github.com/opentofu/registry/issues/new/choose
```

Here is also the block where I put the version and decalre the infiscal provider:
```
...
infisical = {
  source  = "infisical/infisical"
  version = "~> 0.11.6"
}
```

_Originally posted by @StamenchoBog in https://github.com/opentofu/registry/issues/1194#issuecomment-2431893240_

**Comment by ghost** [comment]
Hi @StamenchoBog this is a problem in your code where you are not correctly setting up the provider. You can tell because OpenTofu resolves the provider as "hashicorp", which is the default namespace. Please paste the relevant parts of your code, including at least one resource definition, so we can help.

You may also find the [provider configuration documentation](https://opentofu.org/docs/language/providers/configuration/) helpful.

**Comment by StamenchoBog** [comment]
Below you can find the necessary information and files. The problem has been resolved, by I am sharing the situations which lead to this problem.

1. Below is the resource which is defined to be able to store a secret. Even do the provider has been declared as provided in the documentation, it tried to resolve it and fin it in the `hashicorp/infiscal` provider.

  ```
  resource "infisical_secret" "some_password" {
    workspace_id = var.infisical_project_id
    name        = "EXAMPLE_PASSWORD"
    value       = random_password.example.result
    env_slug    = "prod"
    folder_path = "/"
  }
  ```
  
  Below is what I get when running `tofu providers`.
  
  ```
  Providers required by configuration:
  .
  ├── provider[registry.opentofu.org/infisical/infisical] ~> 0.11.6
  ├── provider[registry.opentofu.org/bpg/proxmox] ~> 0.66.2
  ├── provider[registry.opentofu.org/hashicorp/random] ~> 3.6.3
  ├── provider[registry.opentofu.org/hashicorp/infisical]
  └── provider[registry.opentofu.org/hashicorp/tls]
  
  Providers required by state:
  
      provider[registry.opentofu.org/hashicorp/tls]
  
      provider[registry.opentofu.org/bpg/proxmox]
  
      provider[registry.opentofu.org/hashicorp/random]
  ```

2. Once I fixed the provider on the resource itself (displayed in the following code sample), it fetches from the right one (OpenTofu's one) and the problem disappears.

  ```
  resource "infiscal_secret" "tailscale_exit_node_password" {
    workspace_id = var.infiscal_project_id
  
    name        = "TAILSCALE_EXIT_NODE_LXC_PASSWORD"
    value       = random_password.tailscale_exit_node_vm_password.result
    env_slug    = "prod"
    folder_path = "RESOURCES_SECRETS/TAILSCALE_EXIT_NODE"
  
    **provider = infisical**
  }
  ```

3. And at the end the problem completely disappeared  when I removed the `.terraform.lock.hcl` which made the providers to re-initialise. Then the entire flow works as it should.

Either way, thank you for the quick reply.
