### ISSUE TITLE
Provider: Cobbler

### ISSUE THREAD

**Issue by SchoolGuy** [opentofu/registry#1200]
### Provider Repository

cobbler/terraform-provider-cobbler

**Comment by SchoolGuy** [comment]
No it doesn't? - https://search.opentofu.org/provider/cobbler/cobbler/latest

This is the updated version of the defunct Hashicorp provider which has no maintenance anymore.

**Comment by SchoolGuy** [comment]
Okay even though it is not visible it seems to be present? - https://github.com/opentofu/registry/blob/main/providers/c/cobbler/cobbler.json

**Comment by ghost** [comment]
Hey @SchoolGuy the search index isn't up to date yet, but the provider is available in the registry.

**Comment by SchoolGuy** [comment]
@abstractionfactory Thanks a lot for the quick ping and clarification.
