### ISSUE TITLE
Provider: northwood-labs/corefunc

### ISSUE THREAD

**Issue by skyzyx** [opentofu/registry#1207]
### Provider Repository

northwood-labs/terraform-provider-corefunc

**Comment by ghost** [comment]
Hey @skyzyx this one is already included in the registry, but the search index may not be up to date. Are you experiencing any problems with this provider?

**Comment by skyzyx** [comment]
I went to search for it, and there were no results. That's all. My tests appear to be passing, so I think all of the plumbing works.

**Comment by ghost** [comment]
@skyzyx that's due to the search interface still lagging behind. It will resolve itself within the next few days or at most, weeks, hopefully.
