### ISSUE TITLE
Cannot search some tofu modules

### ISSUE THREAD

**Issue by bsgrigorov** [opentofu/registry#1257]
### Thank you for reporting an issue.

Cannot search modules that are part of the registry, but don't appear in https://search.opentofu.org/
For example: https://github.com/terraform-aws-modules/terraform-aws-eks
If I do `tofu init` it fetches the module, but I cannot search it on the website.

### OpenTofu Version

```shell
$ tofu version                                                                                                                                                                            10:59:52
OpenTofu v1.8.2
on darwin_arm64
+ provider registry.opentofu.org/hashicorp/aws v5.74.0
+ provider registry.opentofu.org/hashicorp/cloudinit v2.3.5
+ provider registry.opentofu.org/hashicorp/null v3.2.3
+ provider registry.opentofu.org/hashicorp/time v0.12.1
+ provider registry.opentofu.org/hashicorp/tls v4.0.6
```

### OpenTofu Configuration Files

```hcl
// Snippet of HCL that can be used to help reproduce this problem
```

**Comment by cam72cam** [comment]
Hi, the registry UI is still in technical preview and is currently being populated.  Please take a look again once the banner of  "beta preview" has been removed.

> This technology preview contains documentation for a select few providers, namespaces, and modules in the OpenTofu registry.
