### ISSUE TITLE
GitHub App to notify OpenTofu registry when new releases are published.

### ISSUE THREAD

**Issue by skyzyx** [opentofu/registry#1279]
### Description of the feature you are looking for.

One of the things I appreciate about the Terraform registry that I’m unaware of in the OpenTofu registry is the GitHub app that receives a ping whenever I publish a new release, so that the Terraform registry updates nearly instantly.

Enabling such functionality could streamline the registry's ability to know when to update the versions and index for a provider/module. Push vs pull, as it were.

**Comment by ghost** [comment]
Hey @skyzyx is this, by any chance, similar to opentofu/opentofu#1236 ? At any rate, I believe it should be possible to create an RSS feed per provider that contains the versions on api.opentofu.org once the search interface is fully operational.

**Comment by skyzyx** [comment]
It is not.

The Terraform registry supports receiving webhook pings. This flips the approach from pull (registry periodically polls the endpoints to see if there are new releases) to push (the provider release notifies the registry).

![CleanShot 2024-11-11 at 11 26 23@2x](https://github.com/user-attachments/assets/6fb2ee3d-f510-4b17-8d92-a0fb0766ec60)

![CleanShot 2024-11-11 at 11 27 28@2x](https://github.com/user-attachments/assets/6dca477c-4481-4b5a-b9cb-9c3a4c615542)

I misspoke when I suggested it was a GitHub app. It's even simpler than that.

**Comment by skyzyx** [comment]
Not that we can necessarily remove support for polling/pulling data for provider releases (e.g., I don't expect HashiCorp to ping the OpenTofu registry on releases). However, for the providers who opt-in to pushing notifications via webhooks, the registry may be able to rely on that instead, which would opt-out that provider from polling/pulling.

1. It would be a more efficient way to scale-up the system to support more providers.
2. It would _significantly_ reduce the delay in identifying new provider releases.

**Comment by ghost** [comment]
So if I'm understanding this correctly, you would like to ping the OpenTofu registry if your provider has a new version? We purposefully avoided this by design since it requires us to run a web service so the provider author can log in and the provider author to trust us to some degree.

This can be reevaluated, but I wonder if we can address the root cause. What are you experiencing in terms of delay that would require such a solution?

**Comment by skyzyx** [comment]
I was unaware that the system was designed this way intentionally.

Last week, I was noticing that the official AWS provider listing was a solid 1-2 months behind.

* https://registry.terraform.io/providers/hashicorp/aws/latest
* https://search.opentofu.org/provider/hashicorp/aws/latest

And presently, I'm experiencing an issues described in https://github.com/opentofu/registry-ui/issues/241.

I wonder if a Lambda function (or equivalent) could be written as something which can receive the webhook payload, then trigger the rebuilding of the index? Or just the index for that provider?

**Comment by ghost** [comment]
The OpenTofu search is lagging behind because we are currently still fixing indexing issues. Once it's up and running, it should update within the hour.

**Comment by cam72cam** [comment]
The current latency between the github released and the registry deployment is worst case 15 minutes.  It averages around 5 to 10.

If that is sufficient, I believe we can close this issue.
