### ISSUE TITLE
Provider: opensearch-project/opensearch

### ISSUE THREAD

**Issue by prudhvigodithi** [opentofu/registry#1295]
### Provider Repository

opensearch-project/terraform-provider-opensearch

**Comment by prudhvigodithi** [comment]
I assume this issue is to make the provider visible in https://search.opentofu.org/ and https://opentofu.org/registry/, but I still dont see here. Adding @abstractionfactory to please check.

**Comment by prudhvigodithi** [comment]
Never mind looks like there was an issue with search, direct link https://search.opentofu.org/provider/opensearch-project/opensearch/latest works.

**Comment by prudhvigodithi** [comment]
I see there is an issue with license and says as `None detected`, the repo has the license file.
https://github.com/opensearch-project/terraform-provider-opensearch/blob/v2.3.1/LICENSE 
Thanks

**Comment by ghost** [comment]
Hey @prudhvigodithi could you open an issue in the https://github.com/opentofu/registry-ui repository please?

**Comment by prudhvigodithi** [comment]
Sure will do thanks.
