### ISSUE TITLE
Provider Key: 

### ISSUE THREAD

**Issue by prudhvigodithi** [opentofu/registry#1296]
### Provider Namespace

opensearch-project

### Provider Name (Optional)

opensearch

### Public Membership

- [X] I have made my membership public

### Provider GPG Key

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBGP+jzwBEAC8iCZTOg80Dx8xT0mN4mRlGiVbjEYwNrf6dj51f5Yg7/jzE6MO
FJv09dt9/1DjmKzjzqjt+Nic70zbFOEa1SiCd5gXndbn2gUBbnnn1poYdT3lLDnI
F4ZpYPiN8hIsFXsrJSjHp1x1p2NGyZf4OvxH7sP+BBZi9VTGVAYFJ8mALXEbW4A/
xDplYjDMv7EktvnBySQ60QuM1l3/CucqtKbt4LFcIMJv+HB8HMa0CgOrZsyca9V7
+xsTATZtbGLLkcy1lOxOu9kuGmKoQvtVZvpWY18B4nXXl7wZS7TU07Bx2sY9IbI3
CKp+Iwbx/qI0ESUx0fATybsQ1oZZo8P+jN2F7NDxUdMbBaRBjFg4ZBKuOxVPm5aY
MZ6UvVIbZDSqk1bpgLlPhIIbRvailI2zF4+cE1xfnXLYg9xhGFRnbTlG5rkMYu3a
jUI+YCBjKNDXeMF6GGuy56dzTGQtbTKlBqWFs3wyXgMY1XZGTfm3RpeZsy2BkUpc
nlUHsj4bPhiHeGRU2Wl9fqHbqSFWniNAwge5LgXMnXuOMrlSjZIMetFQYhXl/vk1
lpY4/FUEhgNQSqFUQ3NkciSHPtEr7HfoBRjXeW4/rePERuQA7+oxBMS6h1HoN5+1
++5ZOh/mthoTvdUvj/2c5RtAhiAF9QMpJNJ7NiqgSDVCErDdAvB2XamMSwARAQAB
tGpPcGVuU2VhcmNoIFRlcnJhZm9ybSBQcm92aWRlciAoT3BlblNlYXJjaCB0ZXJy
YWZvcm0gcHJvdmlkZXIgb2ZmaWNpYWwgc2lnbmluZyBrZXkpIDxvcGVuc2VhcmNo
QGFtYXpvbi5jb20+iQJUBBMBCgA+AhsDBQsJCAcCBhUKCQgLAgQWAgMBAh4BAheA
FiEEoMFsps+oq/TbUzjhydVANPWU0UUFAmYMWwcFCQPu/0sACgkQydVANPWU0UW7
BhAAq5zUCqY/G24X9uMeCXnKWp/i2EFmuPhK2tIG/HY31yzLqsvRzsTsnYAZfGoJ
q7BiPjZm6sb30xhaKwBck0pJ0WeA0xl7+MZYBpNpcsQxJxoDIc+UzdzgQI2dndtT
J2z7gCi/X8fIIqyLPWbhWi98UF+rqF0fC7uK3x+iHi/r8YZ+ttbr1D2BG08k8Pl3
MmDGKknxQkleAWQsl/kfjHsvENSvLHG/vDtL/wDA6vUcnQhqnHJefGoExtsO56C0
nKRi1ujSav7TLeAgeapzfdqN9MAnRXdQVoU+X4IkSHBW5HWo4J7avG5aC5BkwISf
yeyJuDzyQbfRKu2ExfcobVE0iVkljx8ngj93qjZEXaobzyVbxCvySKfaYmN24Kqd
P0H6aCmDh9b1k+0F4YiYlJXwAyypy4AD/Sp8gBKnJSbKRrNsiXzzTEcYIJHABk/6
h4jFQwp6GKXIge9vPJz3Lx4Si5vPFrH65zsBR5EBvtUrGeB7B4Eh0B1FssuHV0t5
CKZTM6OqQIzu6gTfAlQ0NeuRuGmLg7/T7RCZU3DCGGa7fMlULC0Xg94e76Oakvb0
J7YmY7TLgHBJdX/NhIgdB7vAWlyfnUOS11RoAlO0bHd/Ad0ERjMpMTfJC4AN5MzD
G7eDsxOzHQAAbhKBRHk59aoqsSciG/8RjwIluCTzTgGrRpG5Ag0EY/6PPAEQAMUf
jqogFJeC5uXZcflW+HRpho9GOn8+51wix0KdB+Jy5kw6PRbpnMcxizmUq6iKNi/G
KgaWsGS3xp6K8n13Z4y21amfL7gRrzD38fLyp1IhvbJdkO16EHZKUa685vkvw+7X
fbwy0lsXVm8tC93YGBOTkDF5nlZqXpylDqEE71FHvALl4hNj640yfsfU+Miu3NEL
iMT2KO//WzTrn/I4JeEqoHxVIMYcnPN3/Lj43At3mbf3XwT66WoH6twKbRgpEjCW
HNbQNGROKGVoZ44J+hWqiGqhG0ozGSVXceKlK7do9IehDWY4JMZ9VcQsj0jhT2GN
jnq1rmm/4RpE7qbPVtcTtyNHsiuGZMgVWya4guQoLDrIGcTyWG8NFnaIT1v1ydpS
lmFUjHxprtc5M66ySJPIAoeQRAo4EDdhXJ8Aierxo/nT4XMij6u/0jmRHhHjWi47
zxkU2FYVZcmFAP4cK7hHGYLwdgW01+BGAZWuv7L+hcB48roqHUOikWL6RltX97z2
4mA1tln+FvX5Hal4R+VnZZyU7z+W+rXGr0NMgDIIQs92EcdeEags8RlSrWpoGtEm
3uebioD0BybNhXPdxNyEJLR7121nZJGreYSBR8xoCCZ7rDwhD3MmOhNER1xOe7TU
MrfESpF+mSkWWLuSznG9Mp/n97zBB3hn4Wom0kHDABEBAAGJAjwEGAEKACYWIQSg
wWymz6ir9NtTOOHJ1UA09ZTRRQUCY/6PPAIbDAUJAeEzgAAKCRDJ1UA09ZTRRQdd
EACtTEAF3rxrHvabv+7SDpy1mh1GBWJkpxaPh5gnkmD3cF7wuSNe713h7ZEtyr9m
tgfc3pFHLIuGQM57PKB1rVeFPEdbhqcA/Ld0Z0w9QeNEU4NaFcpXmnhEYv67x5ZM
sNf5ltthsSshGH5N7PS20zUEHUrhKU1Ori1+mG6ES1IZZ04Q2s+842II6bv++9FG
hL+ChLA7qVQAw9GPGJ9bdN3tvA52KCQjwYTL5mnVyLRwEVpBfba6QZ0iLFzfGKir
3Bf7CKfrLs15BR+Ryest3SiXNzFVk/cbgz6q8/8IR22cvOrpxXAkygtCidhJtPsK
hOUihhz9kR0PyrYG4CC43llULkw6mXCTBaBp5NWMwItFsr2g5ElJVoc/8/+mFVmA
7DElPb90Oo5SCZ/tcrD7PlSdX1B+AV3V6YcM/ua1BagopgsvhFzVegCdOgL0aJrw
GyLBXkWhejXLWF9lPY+QHaLNEwdcNIacXNgjp9ysNx7FHz+csPdtplKA5vVVS1Ws
30JFWFZ1wdfDNd+59YGt8+K8xuSWrx/CgOZaSAwqpBZZT5RGbksJiJ/CKD/M3wHK
0Q/IMZSQ2WLfdvc/FzSJDbvuTWsJN1sL+oIrxzIpFq6k7pCAffuxKHBBvRMry5HS
PTFTEpdmdSqxxcJ7/CSqjkIb4sus4H7DSqq691CI60u+Ow==
=9IiI
-----END PGP PUBLIC KEY BLOCK-----

**Comment by prudhvigodithi** [comment]
Coming from https://github.com/opensearch-project/terraform-provider-opensearch/issues/221#issue-2614889626 Adding @tthompson-figma.

**Comment by ghost** [comment]
@prudhvigodithi this key expired in February. We can add it for older versions, but you should submit a non-expired key as well. Additionally, you don't seem to be a public member of the `opensearch-project` organization on GitHub. If you are, please set your membership to public so we can verify you as an authorized source for the key.

**Comment by prudhvigodithi** [comment]
Thanks @abstractionfactory I have set my membership to public. Let me take a look at the key.

**Comment by ghost** [comment]
Thank you for your work @prudhvigodithi !
