### ISSUE TITLE
Failed to clone module's repo assuming no case sensitivity

### ISSUE THREAD

**Issue by kislerdm** [opentofu/registry#13]
## Problem

@cam72cam and I tried to clone the repo assuming no case sensitivity, i.e. `git::https://github.com/terraform-aws-modules/terraform-AWS-iam?ref=v5.30.0`. It failed.

## Proposed solution

Use `strings.ToLower` when defining the module struct.

**Question**: is it expected behaviour?

**Comment by cam72cam** [comment]
I'm pretty sure that this is expected, given that we explicitly allow for mixed case in the regex.  @Yantrio is the one who added that code.

**Comment by cube2222** [comment]
Yeah, I believe this is expected.

**Comment by kislerdm** [comment]
@cam72cam @cube2222 Thanks for your replies folks! The question is resolved.
