### ISSUE TITLE
vmware/avi v30.2.2: checksum list has unexpected SHA-256 hash

### ISSUE THREAD

**Issue by lopf** [opentofu/registry#1307]
### Thank you for reporting an issue.

While attempting to install the latest vmware/avi provider version 30.2.2, we get the following error:

```
│ Error: Failed to install provider
│
│ Error while installing vmware/avi v30.2.2: checksum list has unexpected SHA-256 hash
│ 8f8f44ed9032cb3295b28dd3ac30946c213b8cef26a9a094ed70f7da217afe08 (expected
│ d02d60ca64867975ce37c901d06ec796dc1c1f056f2b3fd531c3437f776bc4be)
╵
```

We think this is because they released the same version multiple times. According to their Github Actions at least 4 times.

### OpenTofu Version

```shell
OpenTofu v1.8.5
on darwin_amd64
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_providers {
    avi = {
      source  = "vmware/avi"
      version = "30.2.2"
    }
  }
}
```

**Comment by ghost** [comment]
Hey @lopf thank you for reporting this issue. I set up a PR to remove and re-index this provider version. Once it's merged, it should be fixed within 15 minutes.
