### ISSUE TITLE
Cryptvault.cloud

### ISSUE THREAD

**Issue by fasibio** [opentofu/registry#131]
### Provider Repository

cryptvault-cloud/terraform-provider-cryptvault

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by fasibio** [comment]
I am not sure what to do :D

**Comment by ghost** [comment]
Hi @fasibio thank you very much for this provider. It seems we picked up this provider automatically when we first initialized the registry and you should be able to just use it with OpenTofu. There is nothing you need to do.

If you run into issues, please let us know here on GitHub or in the [community Slack](https://opentofu.org/slack) so we can help.

Happy holidays!
