### ISSUE TITLE
OpenTofu Private Registry Creation

### ISSUE THREAD

**Issue by sap147** [opentofu/registry#132]
### Description of the feature you are looking for.

We would like to leverage the OpenTofu registry however to create a private/internal registry of our terraform modules. As far as I have seen, this is not possible yet.

**Comment by ghost** [comment]
Hi @sap147 this is a valuable request, thank you for it. However, the OpenTofu registry is currently built for public use only. It reads from GitHub and doesn't support other VCS systems such as GitLab. The hosting mechanism is tied to Cloudflare without authentication. For the time being the OpenTofu registry is not suitable for hosting a private registry. You may want to look into referencing modules directly from Git instead.

**Comment by sap147** [comment]
Thank you for the update.
