### ISSUE TITLE
Provider Key: humanitec

### ISSUE THREAD

**Issue by astromechza** [opentofu/registry#1324]
### Provider Namespace

humanitec

### Provider Name (Optional)

humanitec

### Public Membership

- [X] I have made my membership public

### Provider GPG Key

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQGNBGN3p2oBDADC42ylBvgvUpQaJrPr7Cgjrezbvjnletco/IJn4mz8JlScoaXR
v1hnl/EZxPpwUfBJfzKcrVuM3jcenFb8/cPVpKXhaKsHBCn+t6SAVnP+sl9hNtna
/ngVjKDgPiucqMiOaQtfFY3rZKSyPYfUGYnA6A1jg3/V/EMJ2zNxQRC5+AJB0N+F
9sdhd6kFB92zV5wsWpJkLi1mvKuF8Ts4lB3wL221bTGk8EAtnENOGepBbZAOuIkW
HSm1TUvjJ9AJKnqNhQEGkxtiPTTSX+AGJtN6DsNyWrUokeVTapdXAXDdXn4OkFeI
HynEEQDwbnuHZEsRSAY4xKiY6dttCR6IZv9p5mdZ5ZmALFUnhlBpsZfudwRby1Zj
5MpKF6k5srluGOla4ZbcQrVwXu9x5yZh2y/AfRCrFJwmzV3NqhrLP9lQRn6IVzeY
J34am/xsSPM5WwTo2/8VD7mPqpHPiu3OnxVv1nEgIDYbZlonxiR7bb8iP//lzJIk
NUSKsrVcyjBUg68AEQEAAbQhSHVtYW5pdGVjIDxzdXBwb3J0QGh1bWFuaXRlYy5j
b20+iQHOBBMBCAA4FiEEw1F9E1gAOfWB1bPGEDVKhjfVC1YFAmN3p2oCGwMFCwkI
BwIGFQoJCAsCBBYCAwECHgECF4AACgkQEDVKhjfVC1ZmzgwApdfs3rV6LpMB5Oin
V1toiwG2Xq2B/1RrkvDQ7djZMwc/mva0ogsLYwh5GxBA+YM5t8YoQoqEmCR68Brj
W+7j6eL9rsrIJL5rnNSKTOh5OW43YHzESE3jw4M9j4UcjznnqvBkvgZLsj7BXdJz
E89t6ZoKxZ5sbhRVqEcTynrMznD1Y1ujc2owWTqi2drz9kyY/XHHW7zHLIGw8Mzn
nzUK8xjCUP9k1pISBo+VcBVtcOWZ1Qd/dKZNqc3zUjZPnJRxmXo0frfXr9NmMg6V
+Q2vj594YOqesfOKknYfA+9rcTt1bE0N5kE6Ol8w66eoJqCELLbPGvx3WOk2adAV
UuiOzc8HHzxA877YDxexBlzjtPJijMF6mG/KzURKz1t5zMIdQOT/2HdWG9vrb9s3
a2kJJXkmM6YkUsdSCe5KYB5y5oqRprTopd17lUJlobZZO77w97R7bVhRUPpuIcbf
C+cz3sVXe3KR1hUXweQs8KYCcYtXGnYSvWMGoGtfjEeUmGx4uQGNBGN3p2oBDADp
XqoDVERLd04YoXajMqRrKcHY04qNgK81XuJ2kZIj33rqyR9PKQbIHCa+qWtvuQO7
V4uBPOD06tEnbnvIG5ZUx2AS3hVWTv1X/yWbsTz5OCJijFPQl3paq9vD/W5QCM+h
QN2D8q9ZbcQ1t15tujSNsN71+ZU9sY1AsmwDsS5qMXiz6O7IBL/WW2nVWSkM7Nod
qSnIouDV9/D9FlPzZ5j4Qus9SR22XYsC3G7t1JJQGDGA/R2Q/nww0aI0ejzk+EW7
jt7YVOT7AlWMsFL1JP5NU6gxnIcDfHueSrZUN70BlqaIE+f/jqcFbEI1fU5tJ7fh
18hSyB4Mzbxcq94Hy/+CcVHsh9T/LlMZqB07gUzVzo3rYVuQI+yj0nx0ISDQbvAd
V/ag+naZN9Oo4ySr88LJ/Z38SNpecdUJ4FjaMD4hyi3yE5d7NprBYp5yZSndLBy9
YJ56upf5xI8ayyOCT00iCg23INzbjvYc7AWcTqyPq7V+xTMc4ztfZJnm9sB5aNsA
EQEAAYkBtgQYAQgAIBYhBMNRfRNYADn1gdWzxhA1SoY31QtWBQJjd6dqAhsMAAoJ
EBA1SoY31QtWqJYL/0FtqPEBSCzuJ/FG8ruLPs+eXrXRu7SbOfuL9YbqQtSAjoJv
A9zWjkiURLah/cKKkON8DW78Xo/mIJw/Vxn/A8Ev196iO5MoPRP5EvETLsmwnIgV
nrfBJALz0baYrllkk1h46xugJsxDWR/8TG06QbW2VEVZ5z9dDxBv016HwWSLUMrV
R7t9gfi4wq9iZ7zJXjPsdKHAW28XcFvpAWgr03Xi9jG7SAfWB2X314Lg56n3B3Qq
FDAhFb3OnP/YZlrLF9Qh2ftl3ycHmfmiZ9LbPGEGjqWeoE/hveQWJ1n9Qp8xQpHX
a8kqxiGnVHk9iFTiQAXB7Ya3TFlTkRN6fWqrJVKTbOBx5/6OYIcTh7UHrJDPdOPh
DOPjMO4QzrmZO0u/9tSSMJZHPRGbTZlFvGS9+Bep8aMTwHJSg80Ei3dPuo/Tvu2V
NgoZPNQOYBupdEAMolKWpRVIkTsIt2slXNzz5Joee0AIYsd5mfgDPzvNO3SKbMq1
Zno8gW/nXZp99Rh03w==
=M2HX
-----END PGP PUBLIC KEY BLOCK-----

**Comment by astromechza** [comment]
The providers are available are setup at https://github.com/opentofu/registry/tree/main/providers/h/humanitec

**Comment by ghost** [comment]
Hey @astromechza thank you for the key, I've merged the PR and the key should be live shortly.
