### ISSUE TITLE
Provider: vsphere

### ISSUE THREAD

**Issue by asteriskie** [opentofu/registry#1328]
### Provider Repository

registry

**Comment by ghost** [comment]
Hello @asteriskie which provider exactly would you like to add to the registry? If you are simply wanting to use a provider, [this provider](https://search.opentofu.org/provider/hashicorp/vsphere/latest) should have you covered.

**Comment by asteriskie** [comment]
This can be deleted.   I think it was accidentally added while trying to open a support request.

**Comment by ghost** [comment]
Hey @asteriskie you are welcome to open issues if you need help, or you can join the [OpenTofu Slack](https://opentofu.org/slack/) for faster turnaround times.
