### ISSUE TITLE
Boundary Provider is outdated

### ISSUE THREAD

**Issue by devlsc** [opentofu/registry#1346]
### Thank you for reporting an issue.

The boundary provider has not been updated since 2023-09-19 and is on version 1.1.9 instead of the current version 1.2.0

### OpenTofu Version

```shell
OpenTofu v1.8.6
on linux_amd64
```

### OpenTofu Configuration Files

```hcl
// Snippet of HCL that can be used to help reproduce this problem
```

**Comment by RLRabinowitz** [comment]
Hey @devlsc , thank you for reporting this. We're taking a look at the issue

**Comment by cam72cam** [comment]
Looks like the windows build is busted: https://github.com/opentofu/terraform-provider-boundary/actions/runs/12139635535/job/33847716801

**Comment by cam72cam** [comment]
More specifically, it does not provide windows arm packages for plugins/kms/assets:
https://github.com/opentofu/terraform-provider-boundary/tree/main/plugins/kms/assets/windows

**Comment by cam72cam** [comment]
Should be resolved @devlsc, thanks for the heads up!
