### ISSUE TITLE
Provider Key: seal-io

### ISSUE THREAD

**Issue by thxCode** [opentofu/registry#136]
### Provider Namespace

seal-io

### Provider GPG Key

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: Keybase OpenPGP v2.1.13
Comment: https://keybase.io/crypto

xsFNBGSATOwBEADTXnlPdgCyT7txbYHV0nxhbstVBDI5w9wOIoNpcJmjry5KkTC3
rOEayHV9qkH1cLmAs41cUHnYhD4K+NYTszDQcynrjTklVIOsd7H/Td+YLLvwUXHb
MLuhGX5ekmAENFRqBiVUIVtvjT5SZOhAfNbpLWonVvVjkCM/kOLadb/sCreO7Cxf
aK4X1CF496pH5h7lnuTlri7ylffMLaEMuD6UOUd9BVGX4UfPCbsLH97xJzYtOmyn
WdaBGuOqhPmuLGWBdGc5l3+TuPLHQmv5q5nNWnj5/Mdwi3CFxQiXlQLFs6PpDZzz
7c5YM92FrjXeIC76GyGSMP1fXCP03YYLPWeFW0cRjb/tkkg1jyb8jMM+xHiA2cPC
RdPRQwJ7eM2vuGt3MMtoaTAhaKmwufr262/Ro7DrA4A7W2eVCs5rckmnUmrksRe6
jPv/1G2WF1N+aRlgmRbQR+solK85FgaE7UnmCVblfBIp2h9yQjQvho7Jl78FuO3d
+MMooXidTmKTySRs8aL6AqaoWq8RSJBfTMwL174IMSnIgqQ+jAans7q/RPEDTx6D
xY4gZFyBWA1Xac6BSRt7xvRdgojyaUmA8CYTUuCoFKB6BYB3r9qoOLYtChXnZ9vn
yabjD5p61pdn4UYL6FeAM7aZdyky1kIBQkOLIZXshTG4i4/suoW+b62RJQARAQAB
zRFTZWFsIDxjaUBzZWFsLmlvPsLBdAQTAQoAHgUCZIBM7AIbAwMLCQcDFQoIAh4B
AheAAxYCAQIZAQAKCRDdB4GhpCJ5WB1+EACkKfThpiTkgBqBfOHP37wHDRGJmaQO
MXTaKMRgq8ti4YwIrVV0upRGlgRfkJJuoyRI5mO8U3WhXs+hC8+Ujx6NyWWlmWF4
DarsQwNpiO3Jrglvr4IGgEgTmTQIdVm0z7+BBDGEeex4rc2A6r7yrHQYSe3Xp0aw
PVm6Jd86shKyfrLD9/NiGQuyC/W6jVnb4VFen4tA8oz7K56YJyFYSVvt2Dx2YtpR
qymKsVP/Buz/l1/86+G39jxEZ9BLMVlbFqF9KjPBeM6C7ZT3cbFV6zhbD89Od7jY
8X/qMyhbfIOHfv5nsH/khWN559TkESVc0j2JLo96B1YZ1WL3ScExz7I67y6JwPeO
UJQ6P4SFpt/GSO0Kbf8gdb7wDpAUf0WMbhAL5S02Y8ZuSUpnuo2Ekui9MO/0Hpzl
VS52UCU0I0Azvs2r7sqBVK0IN+PdJc4GuDfDVYOX8dAi/iCNTUh25MdSh1/9hx0X
ydXw4UKD16cTOsYsT3Q403hyjbw8ezG0/5MOLFbfFhxsMKcNbiJwMICdPjOKCPjw
S6Gr3Gpc4DSgm+HyVe52AMVBod/8uVsOv+YtTG8SsF+eyUDizYHAOcBaPabo9LfI
5+E2rnZFm/W/z3mYofx2pYLQ/vGtysYW9ZfdP47Yw0y1NfQOPiyhYNhzWT+to7kv
7N7LzWEPTGro0M7ATQRkgEzsAQgAxT/pn3LSD45Bcf19Ah1vuO0T+iguVQVEoz35
1uvbXvFewtG/MDDP7iFlNwQFvpJPM8GOCLDlOnnKxqdMrLXtuWRJepZ2hHAGvYNY
MHNM69gQikB4tZgTBaI5TodXnt1wX8Iu59GOaA4kwA8Axp+e/fHPJfrP0N7e3jxp
GCuILG0+ys0nSP2u6/O+2KnyMHDNlTRBC2F7Dw7fNM2WLDa/xBcia0fn66jtS6Pi
XyaZh2Lk8DeVqyOefQuLpNmay3WuMJwVlFP+lu6of/Y5LASTLc/Eg8Nej1LaT/+z
Tw1Hp9MT44bHqJfzrguhmi5ztz0ZflJ1ZlQwptQzChA32V/F6QARAQABwsKEBBgB
CgAPBQJkgEzsBQkPCZwAAhsMASkJEN0HgaGkInlYwF0gBBkBCgAGBQJkgEzsAAoJ
ELhsm31cvYvxSBsH/2XoLu9Dd0ep+lVzW47oyACYTzpiKyPBrrqWt+KmMJB0uODY
/vPXwyC1cpvfXaGOLyuRsU6i6KYF2v2GM5K5PP6alXYW9PoDbtWZIOIXgPOgpTg5
et2L+S77+KXLelUS5pXlcJaNSydUyBE52mOyzN+hYUInvnKjy1koh98zRw8WP2Jo
MSQBBiLP4W8yNhi+LQIZZiKaVc2cb4a8HtBUpS6C70F6DtKJ7ULsXhfdEKYI5gqJ
iQEfhimEc+gz+9r6AJbRRaOx6tKWAeyNUimF78AlWeF0zrsTOSvJ8i4+8QTr9ydl
6Ak3k9sX7GhDB/bFTdRk6mlJXsYX14HZR/Pm9ITaORAAsGMroVyeR5ljaxSzIeGM
fyEDfy1wPSOzXzNRQKztmPYFA0j1KSSScgvmqU/QkcbtgpbDuidQyWDCsCKGEaTn
LKFU+yW7E5Qx4D4cx1fyddmcNjei7TSQLX0f0G2hldBhyD7VEScsfc+IFapCLT0j
uesStvamLHx8BE4f22QtVu3KaQLa/xUQJFa3mNXOJtVhqZuZUU0kQpePhhkMUVEz
rz+GDbyJ6zqBIF+MSn94G7KbVwzMnT72P/+CY6y4BGUyU6+/5ovi2TKTC6fv1N2T
gzOBHOYpgPPcf0yegQ+fe8wt1zaX8jClun6VJHgaYat41InmHm+fOl+8wpNuMLxy
Pa7J7inIM/LHDHCv0rB8QPpPfVZKETXDeQVOsazJWmsSi3MSTiP7GVen0k3L10w8
IAH5jnYvzSPpX4HKNftkHJGin69rz9lOrcCGeClm46AnyfMDKOsW4Mfi49amG9de
zMmOEIGknDhRoKZsES4+bASkctaLTdtDbIdjHNyZirI7HjnX0QrNw+uRW/gU7LNa
7ST6cwAUdXZ/2kyo/Nv4Y04OFcnZWGtVL2lnVk+jDAumnyhXIaUrIXBqoAHVuMRc
nlmBgi+9G7UpRkDmkHjbn4TDF1LG3nUReom8oxkSgNA13379r3M98B6ylLzG0m2m
NdcgGIagPRAL83A+CDxLHEHOwE0EZIBM7AEIAOv8t5IX89sabamysmpIbhZLR0DU
rUgd9EH5b2AsFFrDJigz6HjuaR1GGt3tb7v3hxcm0g2e9ZytJEKexmxsqeOwmBsK
VzDx8S41WIlxEcCmTpbb6gwmaZ7W5Pch2VHaYPek7XgJx1I4v5lPG7a7qpYTDOF+
FJVfUeAcUkZPxi7ccOTUQ7Jr+HFNWWDyeNoQZ/wt8Bl5JVKgXz/W0xmTI0gSJxZc
IYxG899waEoK74dPKsDytxzXDcXm290c/jmjqnEVmIHyv3n86f/ELWgUFBE78Ngx
YqFsw3UxsuuVzsMHtlMgfylZKuT+/KP4L+jzKXHcSNbEFvGKV3yQ1mbdzTkAEQEA
AcLChAQYAQoADwUCZIBM7AUJDwmcAAIbIgEpCRDdB4GhpCJ5WMBdIAQZAQoABgUC
ZIBM7AAKCRDGwItQy5aZssApB/9G4HCyi4WooBvdubg1H7SpsdKCnPvvAEps9iPm
4Yj7zsygZ3e8G6s/OuwTBdMurb6dNjOyPKO4fp7lH1diNb2V8ifzqLxm7h/H08Nr
v9Fsy/tJyNsBbKVHdCxh5xlH/zM90b2M4EXWVPr+Emh2/t7VgbWaEsgWJwPE7Xu4
IOK/G6Hla8TVjv6PfRid4yML79pcO59sjlKp0VCTVH4HMOfj845VoVxLIa16XUWj
9WuUl5YiPKQTzYJSF3Cmd51UgOnrKGIcaoQm1PTwi98djz3LQ8KAT2KxIIAVVB/0
gpaB50gqVix6gFMmCmaKPlfTZj5xAkVqECVwa2jRtzMX9JsgaCAQAIMxFVcJtLrP
MTsYvbzcyT6Gq6yB5RFk7AAfFVA9gHW/dyKZmDFg2KNkTegOZDrRogjYn1tpTJZu
qO7Y96TndLUa4/tQLWwIQtpFi4tcfTjRtoX+jZkbkV24LA7K3tLw13brAF5t8GJd
WrjE9TOXGCFCQo7SNxlyOj4h1D8Rzsv9jD8v1Tspdd0YC8+3DkKuAH1I/yScTRKk
N8ZzJ6XC1BI8W0Dx2RtRtjMzM9Mo+SCWYIWvQ8GFsDjoSUC8KPgYVFI4X2YonBOy
IjngH2MY24wdYP1awRKVkWXtIhd6F/3oZG7FeYL3CqitxtQpYdRHEXQdkrTgEunk
Obl2oPxXAbWn1BcfeVQznQ2u1Qooj1I5schC9aMuUmMOUfJjZHM0abxQCszC4gxM
66p6tPcW15JQSfyXfyy5lGtBjal+Tb74+TNAN1qz0hr9RDd736u2G7Zqlcz/Amou
4ADik00aUSVlgqGDuL7nUQTJpPSiKJfvXP73ZkwLKFNIo2goXoWa1oKWHujCmYcw
dGypj6z2RPrfHLfKNCI816kWz+yCSgt6f4jnHQh7TCosfeAJruU0DKjLQ0z/+ayv
sX5ul2TSQKi1iOKDjOST2gTkbu11d69NmBj54Y/+uVzy9WLawprKzOMo8/t24C+q
ld9zD12ZQw2lKzvojHuFv7Uqmzg/8NJU
=hWF7
-----END PGP PUBLIC KEY BLOCK-----

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by thxCode** [comment]
please trigger the bot to verify again.

**Comment by thxCode** [comment]
@cam72cam PTAL

**Comment by ghost** [comment]
~@thxCode please set your organization membership to public on GitHub so we can verify that you are a member of seal-io. We opted for this method because we don't want users to have to log in with their GitHub account and give us an access token.~ Nevermind, I'll trigger the workflow as soon as I'm at my computer.

**Comment by thxCode** [comment]
> ~@thxCode please set your organization membership to public on GitHub so we can verify that you are a member of seal-io. We opted for this method because we don't want users to have to log in with their GitHub account and give us an access token.~ Nevermind, I'll trigger the workflow as soon as I'm at my computer.

thanks a lot
