### ISSUE TITLE
Provider: seal-io/courier

### ISSUE THREAD

**Issue by thxCode** [opentofu/registry#138]
### Provider Repository

seal-io/terraform-provider-courier

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by thxCode** [comment]
does the "new" provider mean new to the world not new to the Opentofu registry?

**Comment by thxCode** [comment]
cc @cam72cam

**Comment by ghost** [comment]
Hi @thxCode when we first set up the OpenTofu registry we wanted to make sure that thr existing providers continue working so it's easy for people to switch. To that end, we used the GitHub API to find and index all providers and that's likely how we picked up this one. Going forward, new providers will need to be added to the OpenTofu registry using this process though.

**Comment by thxCode** [comment]
> Hi @thxCode when we first set up the OpenTofu registry we wanted to make sure that thr existing providers continue working so it's easy for people to switch. To that end, we used the GitHub API to find and index all providers and that's likely how we picked up this one. Going forward, new providers will need to be added to the OpenTofu registry using this process though.

got, should i close this?

**Comment by ghost** [comment]
If you can, please test if the provider works with OpenTofu correctly and then feel free to close the issue.
