### ISSUE TITLE
Check for valid JSON on PRs

### ISSUE THREAD

**Issue by ghost** [opentofu/registry#152]
### Description of the feature you are looking for.

On auto-generated PRs we still should check  for valid JSON in case manual edits were necessary, see #147

**Comment by kislerdm** [comment]
@janosdebugs Hey Janos, I'd be happy to give a hand with this issue this week. Are there any particular implementation restrictions to be mindful about?

**Comment by ghost** [comment]
Hey @kislerdm this should check if the JSON is formally valid, as well as being readable by the registry. The main intent is that if we manually need to edit the JSON (artisanal JSON), we should be prevented from merging a broken JSON as it would cause further issues.

**Comment by kislerdm** [comment]
@janosdebugs thanks for clarification! What is the condition for "being readable by the registry", does it mean validation against specific json schemas?

Also, are there any specific conditions to trigger the validation? For example, trigger only if changes are pushed to the branches which are prefixed with `module-submission_*`, or `provider-submission_*`?

Thanks!
