### ISSUE TITLE
brand name correction in README.md

### ISSUE THREAD

**Issue by kmuto** [opentofu/registry#161]
### Thank you for reporting an issue.

https://github.com/opentofu/registry/blob/2e640a6f07a4f5209d79d0d23dcac994c201640b/README.md?plain=1#L1 should be Open"T"ofu, I believe.

### OpenTofu Version

```shell
OpenTofu v1.6.0
on darwin_arm64
```

### OpenTofu Configuration Files

```hcl
// Snippet of HCL that can be used to help reproduce this problem
```

**Comment by ghost** [comment]
This seems to be correct. :) Do you want to file a PR for that?

**Comment by kmuto** [comment]
@janosdebugs thanks! Sure, I'll try to do.
