### ISSUE TITLE
Provider Key: v0nNemizez

### ISSUE THREAD

**Issue by v0nNemizez** [opentofu/registry#170]
### Provider Namespace

v0nNemizez

### Provider GPG Key

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQGNBGWoM3EBDAC+rONsv2E3RVjM0aWLU7ALsN/Qwkya/7EZuSdlsbdMBPmBddyI
Acj/efKlGcTrnMYy9SP9JLOc77ntrtweoMaKPKWgPs42GF2aGVM+oMKmncl1rVVg
s+xYr63P/4EXrVjCnQ6xL2HS/seMBviRN/IxhBZrRM9JsJUgrQEO/EDsvBkKgZo7
Xv9URMDmnQbjeG4tHoUTmRqRuXaSNsYjETy4aJ/Kfj0ryaWtUqYR1MtokCcWVwoQ
xp23BK0MI7zY8kX1WZy3Ia44pL4rJ5nMPabJeraQRiy/s0Wl09xQ5pCePn4IeHAM
vpokF5NyfhpxZjxf6okkeWALmxmFUH3nya5VOKr+L3+qZDtcWVzE9gT9sp5hp6RQ
aSk6tE07v1/LtC3WA9ElsoitDguoMYYbNs7JGlRspe56/Cox3TEqnt6+AY2AM1/9
B2A4rasppmgKK18MV8RMiy8eWdbrBnNbBRDj1OOmlZQ5QC3QaXT+La4uoJnGTTuV
wIOdYtCy+ncBLzcAEQEAAbQ1U2ltZW4gQW5kcsOoIFZpa2VzdHJhbmQgU2tvZ3Vt
IDx2MG5OZW1pemV6QGdtYWlsLmNvbT6JAdEEEwEIADsWIQSV3tFvqXWaoNgvT7N6
T9Qz6zOduwUCZagzcQIbAwULCQgHAgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRB6
T9Qz6zOduzP+C/4nkpbMdQ/rkAtI7jvDp67p45n+XKxg0H2kn9c+sPBgk/ugyWxg
sJg/+eJ30eGHoRyZq5GOiHHADGjv1W8dWjqm7+QSNKLGAhjQuwynPKM7gn5qSVxe
Ve/5jaIMY6r1mvIBlNK2Q0j9J78cNHCBnviR+st9ArWVV+mWHMX0tknwH/l9JNpu
HVbv8uhrzPoTXzHe61x9kVXS8/aT9sztfuu+un23u3gKVQ5/WACk+ntBQfXGqP2r
OVe7NERyB7rueI3VQkQtpx9+g962vF1AEwwZAw/VTa+gV4obJBSw/3JtBvAdBvRb
l/b4SM6/cz2HGi9tQ4RetK/tKBdl6rfpAcpZZRIXjWwBVLU67Cde0ZbnpMNO4/dA
Q0wG/xWkWD3rgelbRKDNoRZAofdjJBhNZNlXw03Syj4BXkEBL9oFmG2pYkHkf/cV
yLqeFM/pDoFMHdkVDu5gvB+crscmjWoTkvnDI+1GQ/DRVj9JOmolO+tFhSrJuvKy
yj8PZSeYeDgqM1a5AY0EZagzcQEMANfIGB2STuyB2Uubt+A21WGQ9YRE1WSfkRIB
8jIWIoSjtauG2vfCP1ilEuUM3XGIwrWFNtH92GWmiknXKTrjmSVc8Z2JHeMTe8q5
5k/FzoHAjA2XWKlfebaqpaM0HbZKMf1zq590ohSoGmaJJetN5hcwS9/GUMDS27Fm
EitwTPEuT+J36BXbyqHaW2ZmmAErcvfnMVfNDsfyar0QezchrD2IA8wP/p8c4Dhc
DI+jPhSLWxOU2ulx3H/JEXCtvORt7y8+9ji65rjyfKvZodI84M/kD5sN2tNZO8lH
QEvSMCKjY1bFUMJHUm3q+DYKc44vEIyWV3/soOP4iiRfNOybH+8i+G8FkHbIUuwE
HH6moVVFPgfjP1W1DVkICT4GHUck9V3OHsEeuqsBcu+tATo/s6szwUFqze6oQFzi
GG1rLKtJyhpIbuNMOp4Yblhm1igt6GoetyFrZ4rK79IZ57wKvbgtVgFSI81AVNix
ZYkxXMFjMIh6+R0r+Cq3Acr8hwxKJwARAQABiQG2BBgBCAAgFiEEld7Rb6l1mqDY
L0+zek/UM+sznbsFAmWoM3ECGwwACgkQek/UM+sznbvzsQv8D9x/z1y2wNKl1PIt
vS5KEPgopf0htPiSLRzEHbT50pVzcRYwZV2fhvBvnyePu3Ho+lWzETm51QnsQEro
yX/WYRZwH+qzrFhD+1kG/BSpvAt/yJQSKRfl7TMnneme18undlOEE08AIRTR+Z+y
ZyWtvnhAyK6RP9KxNTX7Mn5d8WSYxVOYfJwysbf7SSXTB2rss5SuM0Hxx3dQPlGW
RZtzm0ApeA+oZU1Eje1VBNuUSIXowmHf7YEdpoowg5wFI7ZAFdTm9i8zBxnpCevs
kyRQEgmbL/KS8VteqKHinbyNp8eemLaCXsft3kmYD0ViM9gLE3FNyc+YcV6zSb2E
sTxBH/tLLImXTkl2e5D53I2Et/DGQyTy+QdzLGg+wUwqmQ2a9cEkB2QdDvjavZPn
gJZtR79J8UiUcje7Iv++/voSMz5D5Wa6f5NYf7n7z85deSFhXhBjyZ8NmqQRrXkp
flfjQKkzYMyDYzi48WVIfY7OYlQfOcN+kbmEZQ26frdIog5W
=7wZt
-----END PGP PUBLIC KEY BLOCK-----

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by Yantrio** [comment]
Hi @v0nNemizez thanks for submitting this gpg key. I would like to hold off merging the PR until there is a provider in the registry too. 

If you do have a provider, you can use our provider submission form to submit this to the registry first, and then I'll merge the GPG key in after :D
