### ISSUE TITLE
Provider Key: Brightbox

### ISSUE THREAD

**Issue by NeilW** [opentofu/registry#189]
### Provider Namespace

brightbox

### Provider GPG Key

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBF8ZiJ8BEADc2bWE8QjlTsA4UpcHC13+qhv2BNOs58rqW3tlK0eeUABhIwpe
IG3NhRboybUIgE1tHbJPTau9LEGcFQTj+Sgnu5A5Ysky4JSdbuU/GypJn8IE+zL3
YVNmZTIHgBSdZj5bsXb3G1dTJ+VpAafgt9g3WqOosqYxcxDJSZdjhRc3mAxM6OEv
UpxT2Mj97a7CKrSQjbt2Wtt9or3HycgZF+dZL7px/WTHXXPrC3mdLgMfVS8MsJEn
VdeEgIlYQNclnSpf5N+Qv8S0Wtp7DEsnTQ1iNPROvrnNt1dlVcdza/k1eiSOq/Xk
KCvt+ekvmZUen+m1r8FGZc0mAJ6BIblV7aCzX7JstY2yDXdUlHgOBhSygZ3VSYCj
1ipRf5ZSpxnZyIcyXXY+3uyY8pVZAEddVYdbyB/kyCxPZlbNW3Dq8Qt0EX9UbHQt
lvYHL4Hu5frC0i30JfudzM3x2vsq6jWpqxSENSNqZuMREtO6igFXyxBLs+tBGVdJ
QL2A9dgBrTqbmurnhUgkGuBpC/VYfsnS5Pryf9OtCRHqxzPiG6dzHfJ5wLwXiAdX
gs5+LwCNz6hRCLFHfnvv562wlPmth4UnWcp/RpCQZVu4vlT9DBW4VFLId0aBsn2J
SNZV301FDoGKFmw4LcCf1Hkn1mU+LQYObi4DHcDM9/e9kdrQ3LcWx3lX+QARAQAB
tEJCcmlnaHRib3ggU2lnbmluZyBLZXkgKFRlcnJhZm9ybSBSZWdpc3RyeSkgPHN1
cHBvcnRAYnJpZ2h0Ym94LmNvbT6JAlQEEwEKAD4WIQQ++rKk5+o5kCqkLPSGoBx4
0nasfAUCXxmInwIbAwUJCWYBgAULCQgHAgYVCgkICwIEFgIDAQIeAQIXgAAKCRCG
oBx40nasfN9GEAChK1ZoYqdnSHa0kn3ipqms8VmMS7RM5v7E0IHMSZKx3b5bcQGz
PGDGUmG4A2Cu0LI+9gKyd/qtpZJQ+7nYvVZjxMBqHWhHVNUMlOyFLv6fDx7ZuvsJ
DQ+G2sCauvPHeH4JO/kH+tq9U+toqx1HV1MHj22ISPxjttO7FHltg7ontfw/YL62
UA6XhJGEehTmf6YMxVQPjhO/MPEauy8h5RFnNL0BlJo7tmhX94Z9URAGQEjkpWmf
02phT57KSVs8TyteCBvVxnM8HXiCaRJOHGYrr475uhQEWUiJFw29zdAaynNnYrDG
DspicGBqz+fy6T06QkcUFoIqnqgG+7b/bAKK98kJ4BvxMtEan27k1n+jpr3NNA+w
uDk2yBcMBeFooMRByOZ61+cLmIlueRFfeKPyTobowK0qey13OpIz8ylGYOFQrD5B
K0c3sCkapLqzK2jZwFzwMI81P2b7C1UjMvwC8JubycnkUDa77oeHBoXuaGTdyziQ
r/V/b0vEQh3IRg6RAGJQLTPqKw+ISDclteCmSaazsqoeIoaLkGm4SY3Sk96jblOw
XqS6y+963uk1ebbikBX/t9xiAMF7+Nazpif/I4fZliYwyq/mPLhW2/5wwjRinUS9
qxic1LHh8LSHbY5CYEW8t70CAorc6jzOsFLb7tvgKpOGJQzvo02MUVOsfbkCDQRf
GYifARAAvyYpLy10sgwmSZ2yYoasz7ug517Ia4/CR3ZCk0N+pvA9myvxI/FH6JLk
HacF6jsyZWPr+POi6TZStZ46HsHcASeKjItPlB3tq+u2yYuijPH8DTJkO6Aup/u1
3M17T8/T+6ioiV4UfPYYjRVJ218lX0ZERs3D9H1c/F5IKh+uA/woi+AnYN8Nla04
t/8l4JSGZLtXvrNoVjhl1RdCPgdMG680CcG3FTb7nRQNFEFDS/WfWqjc9N/plyMw
U5+yCnIz3tQwEwE58IEuJ94JDIxJaQICVpV0MaGEsnjWBIjJnCucWfyG3V45GfxW
1OuJEFnsUEn1VPqbng7wRTHyhbrEDqSPbvZl+LkY28u0T/scboVgGqqWMpPSNyvS
ENWjzJwF0mLiHJy7bNTOdG+Yalwgy/5qeoKaNPqGXaW3qFZM5Irfnrp/YyzN+hgX
juLUT1G1dcGVEYa4YwY9U0Q1sjJQ/Fb6uiE1c/gxJTXp2qxrZE087js2ZFn9Wgx/
U+Ko30uo4sGGyy3ChLivUa8XfQ8WC0xMRRMiW9Imf+JXOi+ggRFimUYECDAhIju8
1av+3/TQyJgjqGDBzkCDF3iwLvA8+v8SdZgV+LTvW1O6qlPg/kTLLkGASA2R0q7f
JgdX8p17Yw+dQ/gd92Jxjiu7NR2RWYaYGx/7OLcP/nEcargzfd0AEQEAAYkCPAQY
AQoAJhYhBD76sqTn6jmQKqQs9IagHHjSdqx8BQJfGYifAhsMBQkJZgGAAAoJEIag
HHjSdqx8RYQP/1Ga/4TsOh0iQ2GPgNdMKVOe2EeclyYYD+CyRR8+W+fWVVeJe8Vd
a5C06QBu+PBysp2ZLuqqQ1aEoL5Lcjc0PmHiGNlwmYjHq6uu8losR+L7FTudga75
wLp5dqO+HsydOjuE0kZxo2dujjiuSpjwpDxOWnwxHSkrzkY/S2B/5Dle37jFzeQm
98gu4nS1C7c0nQMEwGJvRDdWtyW4E15XdOWvrPPf/0qXSO8ntqwZ5xQs3qLVeGbe
o+jC1L4VfJkbCFiSIAzmAsw+30LZP9mKnN/v/0K2xSsa4NA1DN/7DiDnhSIq02up
xmSeM5s3aAjs15zaYOeiWEaC7JWHAUzdkOscUsQ4+NRyoJUkdekMEdcTWnVvdwKy
uQNtp5YkTOo/qM9dERIrW/DEOBON8x81YPUllLMs8iCvdtuPD70KhsCsauqGwOuF
NUFtYdy+c5KLEIhV8nTx3NNzqFTS6RaN4ddG+1AbxnhzTJN9hZ4v0P0IOiTvdVJz
ad6C2SfWF+yT8gEnVPJ6qxoVGfBZ3btMMCP7B3jSjbZdhYxoPbLB52orZRVPXmCG
CMctgmjdWMhY4rpaBydHg9D04yaG5+b1LuRuFg2Cl5MqgQ9FMXQAf1I1nDN/b5xV
VdKyT5Ub9sSgOnk+22tb66mXRf1DpMp+X8nuvG3xebU8BRr460+WMaPu
=TTr0
-----END PGP PUBLIC KEY BLOCK-----

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by Yantrio** [comment]
Hi @NeilW , would you be able to make your membership to the organization public please. There is a link in the comment above.

**Comment by NeilW** [comment]
Done.

**Comment by NeilW** [comment]
Might be worth putting that requirement on the issue template
