### ISSUE TITLE
Ensure whenever we're interracting with paths, we use lowercase paths

### ISSUE THREAD

**Issue by Yantrio** [opentofu/registry#19]
We should ensure that we do things consistently across the codebase, and dealing with just lowercase pathing makes things easier as we dont have to worry about case sensitive filesystems checking out the code.

**Comment by cam72cam** [comment]
We will want to make sure that this does not break any github URLs we are building.

**Comment by RLRabinowitz** [comment]
It's worth to mention that host providers are case-insensitive (`OrAcLe/OCi` and `oracle/oci` would call V1 API with lowercase, so they are essentially the same provider). However, modules are case-sensitive (So `terraform-aws-modules/aws/iam` is not the same as `TERRAFORM-AWS-MODULES/aws/iam`).

So, that means that we have the keep the casing for modules, at the very least
