### ISSUE TITLE
hashicorp/azurerm provider not being updated

### ISSUE THREAD

**Issue by simongottschlag** [opentofu/registry#203]
### Thank you for reporting an issue.

Hi!

It seems like the `hashicorp/azurerm` provider isn't being updated automatically.

The latest supported version right now is `3.87.0`: https://github.com/opentofu/registry/blob/main/providers/h/hashicorp/azurerm.json

The latest released version is `3.90.0`: https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v3.90.0

### OpenTofu Version

```shell
OpenTofu v1.6.1
on linux_amd64
+ provider registry.opentofu.org/hashicorp/azurerm v3.87.0
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.87.0"
    }
  }
}

provider "azurerm" {
  features {}
}

data "azurerm_resource_group" "this" {
  name = "foobar"
}
```

**Comment by Yantrio** [comment]
Hi, thanks for reporting this, it looks like this is due to the our sync script failing. I'll look into fixing this now =) 

For reference: https://github.com/opentofu/terraform-provider-azurerm/actions/runs/7776526278/job/21203782811

**Comment by Yantrio** [comment]
Looking into the issue it looks like hashicorp moved their tag, and our sync script does not take this into account.

I've raised this up to the person who has permissions to edit the repo and we will remove the tags manually and sync again. However this may take a little bit of time as it's currently Sunday evening. So we do ask you be patient on this one, sorry!

**Comment by simongottschlag** [comment]
> Looking into the issue it looks like hashicorp moved their tag, and our sync script does not take this into account.
> 
> 
> 
> I've raised this up to the person who has permissions to edit the repo and we will remove the tags manually and sync again. However this may take a little bit of time as it's currently Sunday evening. So we do ask you be patient on this one, sorry!
> 
> 
> 
> 

Nice catch! I was able to use an older version of the provider and that worked just fine. 😊

**Comment by Yantrio** [comment]
Hi @simongottschlag.

Thanks for your patience on this one. We tracked down an approach and we've resolved how we keep this in sync. 

You should now be able to use the latest versions of the azurerm provider again. 

Thank you for reporting this! Please reach out if you hit any other issues with our registry
