### ISSUE TITLE
Provider: AmericanCloud/Cloudstack

### ISSUE THREAD

**Issue by CodeBleu** [opentofu/registry#232]
### Provider Repository

american-cloud/terraform-provider-cloudstack

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by CodeBleu** [comment]
There is a version.  https://github.com/American-Cloud/terraform-provider-cloudstack/releases/tag/v0.4.1

**Comment by RLRabinowitz** [comment]
Hey @CodeBleu 

I took a look at [the GitHub Action](https://github.com/opentofu/registry/actions/runs/7949773108/job/21701323803) checking the provider, and it seems like the 0.4.1 version does not have the necessary checksum files (`_SHA256SUMS` file), so this version was ignored. Please make sure the artifacts contain this checksum file

**Comment by CodeBleu** [comment]
@RLRabinowitz I have added the `SHA256SUMS` files. Do I need to do anything else to get this going?
