### ISSUE TITLE
CloudTruth public GPG key

### ISSUE THREAD

**Issue by matthewcummings** [opentofu/registry#252]
### Provider Namespace

cloudtruth

### Public Membership

- [X] I have made my membership public

### Provider GPG Key

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBGKopwABEADXNlp83Xaeem9P4c4bf0HXzfX3b1NUmPCL9hKcEHhhFGzSWCKG
AqVHiM3BNOTFjDUUIpy29UCeUidb/55rveJ2rkubWGHAXuDLzDD2hueML/9N4/Vg
Ov3Oag+QBHU1/0uGiZlmDfN64cOlKEfh3nUH79rM/oLE9hBm2AQcofMgvOzR8qt3
EhyWZWXDuwfM3Aw+UbjP37wVfLic5PWBg9sx/YbRJl+kIycvTwB72yu4Sgu7E8MR
2sBlCBlo2oPAPDQhFa1xhSr0v1Afg4GJiGKlTzVRpYc8AL+9LgtWrh3X3BTUCF6n
RmPzymSqibm3WVZRxLcHZ3fcGKbvrnQZpYov5F0l5eQ7u+aYl4qYDSWYnp4kCMUm
U90UsOgfzdZMVPb3rlS/haoko7BmGSFM5BgLm/ux/EGJ+eNjPvjhohMbcamSjG4S
yJN406Jv6vFJRSNm4/BaO9T6KxeW7jokO6+6TAnJnmSKLculpwMG8J9Rxisr+a7L
u+wsSMv3JdCCQCp7EMAOGuTRDx5idSWEPFObqt7vAo43KQzoieaP5FFAYqM5y7Z8
vBi2r20n5vCgeapBreHOhJ0Uj7VGNtyrUzwcWi3XX1FjdJYnCHdby7qVOvC644Pu
kaT7IxIT57eK1qf788gPYTyLmcLlt8TwpCO0ijqzDFr7sJ02ds9rxiZRbwARAQAB
tCpDbG91ZFRydXRoIE9wZXJhdGlvbnMgPG9wc0BjbG91ZHRydXRoLmNvbT6JAlEE
EwEIADsWIQTZyF2uZmwTX0CytoLx8o+WPO7JkQUCYqinAAIbAwULCQgHAgIiAgYV
CgkICwIEFgIDAQIeBwIXgAAKCRDx8o+WPO7JkTGbEAC+KzIxwzhrlkgRE3bv5h1D
CzKph3WBhEernh5N+vEko5TAmDUPk+eeyLyyK17OBGL8Cf18e2dzqKVwjlJskT7s
ZJcmCAvHnhhjhv6C9KCsMz3zJCsvQVdXzI75hZl6EBHZn93yrG8YgAUI+TSx+3ow
n3qGyOo1itvrpcLM/B4DBysqaeWPaBkx5xGpbuyaLmZjV7hZiMeg8cHl9bUE4rta
9m9WucwolNWzz9oOPXwUR/oRZTMmDoHpafleWpZrcB8mw3T4GVViO5lLtdIQceCU
rgfhW72XunRD2BrJtlR96fWgHbjL7adFmH92PxSFzrlCxdEzZMWY2D6q6AoYQwHS
31qFh/Of+IzfvWue91mOlnk9CSv2Mm02E54U8RBDym3wOH9ALh1BQwR3C6+DpfBr
d5/gV57KjZDYcjATBfaPgO1xovywOEo1KWaO6Vae01/g3/iD5UinAo2+7KSCmGgg
qJclFQu90llrAEDbwcdxv3JkInJwlHVyhgFAbPXG1TXjCTbwizYCMFD2o+9ZcLrp
xoO9sHWP2rCrXHk4kJ8cnYQ9Gw3zTATE8dBEHTBQD7niwww9i8Ki6mEPk0naCUeC
DFVQtys/jSuNTh9NkODET6VJW1XifqkF397r7T8rhzo4gpthx9eBbByU8eaNXZF9
P+b4otJB11sW7Y9vofxbALkCDQRiqKcAARAAr++pcGcrso142Ld7CI2mxV+rbCIV
prK1MXgs+8EiGhmQrjrasDbwGbIVfFQCsM+NesvzaU0jngCeoGJ9zxc6IQeeVVZb
BpEsQ0zCEy6aS846qqbuUSq7RA4gMkdK4Hm/51c9sPWnXgFc7hEczHPyLF8D9cJI
fhEsOwOLH+Cxinen65eE4fHn9Ys09+VuUV58sov14TkD9AieW4xyixd5sSnU7OZT
xww6V2iUq8KpZdPDpIgk0pMnTmDXwvDyx1lqeZT10ecA4rQUoIE15YCyPOGKXeoV
iqgb9mWGJBxAvzOFxYVsy3TpLGhNXyt3i6PzMbsYljTQktVBlNCTJ+zul2sS/IrE
5NfUuzDLmffsV1QGrmjw2z10znyaVDEpXYYoP09aijixjGKxnO7YrDKPsyAsE51c
+xPPwHdhOmVYMWBoby2n7LwGh66REvVSy4ObTeFBbjPJfcNnl4S0KAbJkfz23SDu
as3wrHhI3TSHLUEbwCA/s4zLH4M0WWRbAXgkf7fCUCl4iQH80dvwO4ZEUptI22Cq
+krfhEAkYFGwcGwlCviIcHUpW17mWlSAidPEzF6t9ELvzNzjEEIjWf5E6LYhXtUK
CZYuIzIBoIG9i/FDADINtzwIgc8pprQruy6F+muoLb8al0PzIGF5SYybgQFmq2Ww
pdEM92cPijhaLokAEQEAAYkCNgQYAQgAIBYhBNnIXa5mbBNfQLK2gvHyj5Y87smR
BQJiqKcAAhsMAAoJEPHyj5Y87smRaaQQAM6HCywwnJIOyCzaAa09qt20uZLT1m9p
2PzvQTLMzqKPG11GYs5VBKRe/EVmWPSWfeqB9bnG9n5dsDVlmxIn8Y+BkD2YJ+0U
3wSm4NT4TGb/n+abbChucoiu1IBPg6IU4wvpdbgduXlJgs9ZCBsNYZw/Yy2j0D2s
XI6Z+uxBi1Yf9EtVyoIjbAu88/+wXVgbn9rgDvVDnB8CJBofwRoX6AsNeemNFeS5
G5jMQfpGEsC4LuGaNKvc84WarL5SM/i5/tHG7Mu86o8PZJLTSfehU7ujNflL7rW9
peuuXx6QG0BT01PicSjHfSTobwPy8ey+R1PV8Gq+4NEVl11RJL0NQV6Tiacc8NGg
pQQSGKb1GUxYXUZVXCslYWh21gtTZzxWS4B8349oUEBTYO12ctm73WXi+Krsgi74
cBoRp+b0RcVFetpJpa81Cmu67C5drYBYXXlclLYAozBiAvQ73KQI+hau5V6LM9tO
mh+u1+E6uV1rD/aJvbTDu2ueWJ03wH5ptz+1QuQzKiFdpd5Z//DH29OeHn1FmF4Q
mjXYyyenqhSoVocEGG+a3Ry0NLbc4EqbHiqftK9z7KgOumPNn9cRkb/ljFeIb59+
Zeoa5O6Vxrn8dLDXoK94Y8N0hmWr4LNt3QZMqt9eYD8V6V3HVlymcvLYYEDoyeP+
CFN4hPKrRDmn
=eTaF
-----END PGP PUBLIC KEY BLOCK-----

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by ghost** [comment]
Hey @matthewcummings it seems that you are either not a member of the "CloudTruth" organization or your membership of this organization is not public. Please set your membership to public so the registry can verify it.

**Comment by matthewcummings** [comment]
@janosdebugs done

**Comment by matthewcummings** [comment]
@janosdebugs please let me know if you need anything else, thank you.

**Comment by Yantrio** [comment]
@matthewcummings Nothing else is required now :)

I've merged your key and when the next registry syncs (it updates hourly) your key will be available.

Thank you for this.
