### ISSUE TITLE
Do we have any alternative to terraform-provider-null ?

### ISSUE THREAD

**Issue by yogeshlc** [opentofu/registry#261]
### Thank you for reporting an issue.

In terraform we have a provision to use null provider. Do we have similar null provider in openTofu?

### OpenTofu Version

```shell
OpenTofu v1.6.1
```

### OpenTofu Configuration Files

```hcl
// Snippet of HCL that can be used to help reproduce this problem
```

**Comment by ghost** [comment]
Hi @yogeshlc yes, you can use any of the HashiCorp providers in OpenTofu, including the `null` provider. It's included in the registry [here](https://github.com/opentofu/registry/blob/main/providers/h/hashicorp/null.json).

**Comment by ghost** [comment]
I'm closing this issue, feel free to reopen if you have any issues with the null provider in relation to OpenTofu.
