### ISSUE TITLE
Provider Key: 

### ISSUE THREAD

**Issue by outscale-toa** [opentofu/registry#308]
### Provider Namespace

outscale

### Public Membership

- [X] I have made my membership public

### Provider GPG Key

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBGQduOoBEADeKa5tCQ+qM1WzEDIFw+6j8SdKz0DnhSjBJmavL9SbJ4uprZZa
B6GAXZWCgRTTNdJh++xpm0AEn62+ixcKOwz/dT8eP2QCtZEUnJtUw3WyBh0IeAgh
zWRboYyjweu/9qoJ0XwCzHyLvlxm28pqpLlaVqxTW2mOxG+YwX0pLrgWCIK5YBr8
xucQoglXfTSwo8FmNKUW9QKUadhrtEKsHLgFeq5JZohzzKlhzqTbZ9u2agPSoJ1Q
twYKrordroigUEJX7GPpMzWxAwMjNI3q3e6z9KK8tee9in1W9iJyqwGrLUEULiyE
LvMzlEAzC5USy+Yf2STTsEuSp/fyuXFsotzHY0X9/MVdha6IMPttfKcC0iEY98W1
55HkHlaYKNDDfTiDMx1IRgkUV67vs7uYKsz0XeceJ3DmcRQiCKprrAiuCbpeGHij
0+LRsZDvG8bR19T61iTiFQDzPqewsiXh1fLdHCs8PKQkf8dhq1EawSJUcnW71BvO
uoWkkgwESnGMOSPkAXlqmB4bWo0HMlm/GG5A5LIbxwS9yUpC9iTDNyEELBzLkVsY
ZT6vur8AXZ25masy+DPSxotTa5d9yhKaNC6SnjCLugiordstez6lhL9E+G1PwWXf
7GynLjQdPW5+pfzEkC9bSkPW7woH4zqqqwAURe+VP79NY5KhBR3nceAUgwARAQAB
tCtURl9rZXlfb3BlbnNvdXJjZSA8b3BlbnNvdXJjZUBvdXRzY2FsZS5jb20+iQJU
BBMBCgA+FiEEg0WUtJLaauXLI/NW6I0FKzJr/O4FAmQduOoCGwMFCQ0oaIAFCwkI
BwIGFQoJCAsCBBYCAwECHgECF4AACgkQ6I0FKzJr/O6WDRAAiXGGAKp9D85mMaLB
VAAEAX3rZ0whby0PS83fvtDvPF+4/FsuXM/894C8DIS7DSehukSCLTDvsPTeNSWZ
N1K0w1swdvI+FVYGcd/liPf+HOU0dYPeX6+NCxgWxSTwISOhOciSPdg0sb2D+YGT
/QvnX3Ohq0ubpSgOzy0m1S4tRfXOHy8KRn03hp8ihyNImLjjybhK9d9LmAyXEgL0
WcrXYN+qHLJ3oDBsr2amNBcKaNG8O5unkZcF0xva/8JM5Wp8IKLdRcfvJwJri+pd
awaEgurVqGozpwzTLcTzypsw0U1KJE+LVrCog6LTckEUsnu+mysAThqENRPsEZbZ
kUL3wp2nZdavEDW6r7epPe0lCOh8E1LgkRVeMoEGDb+qle5XN926V5+X+fxKHPFE
89FDikdufZK8QzBpYRVwcSSliODrn+X3OMN0rrNPy0yFAJg3wfYUtyIRyWubTJfA
niMACAzPU2wxlxiRMUVmJwRkgs4TQAdr2OK5uztwhwil7jBgNw9s4pKsVHeW01S2
hPoPuT5i6dfAbwylgpacsl3qGOSMCuUN70+lQAZsbA+0lpCIallTfNv5dAQBZOVJ
YMptFjVrybZKnieW6LEf0JwPiWuxTCx8U3kuxz6dSL+kTQgKfqMeo6nNNDsjAui0
NnxM88fYg7Xn4q6LjpcaCEt9yW+5Ag0EZB246gEQAK8KWzGJxeN2RuKG9QRXCbd7
njuOzvkWISlWXCYWWpwEWf/SgZSTW1ASrQ+JILz3stvSEnp8YBqjDVC7NvSfXP1W
MuoG6N4n4vOXKfBN2xi/1T+hVUekjcMdIDByq57Hdr68BsElmzozicsOfBOZOT3K
8wanSUeQi6h/uYGNgLNKG7V+Ta7yDuCiOVRVulXrAuz6AhvK9Qb23LTO1J/1UvlQ
QJylC56HHXW3O0ONWl5ytBJ1GHRV8NPRMQ6tyodqJMmqiISRhI0WpVHYMp6QlTVQ
tFGBL5POVV7x9NVIUmwsiS8PZ67v85KtLVHUHuF/YoFJdbmC9oEil5qbM2MyJi0R
LyrLlhxgpRPD2U01CGcdU4f1LQEwz2zPJ04zLqEK9S0fgHNW81H8R2XvtCHz2wbZ
6EJsmU2/VTkOYvMAknu75dCuluADkMDQiR3fTajJtjiEVOKqVUc0uBoMoI68HE61
1k7C9MKQzb9qBgiHbuzLOJdTtaB4ySLCCevWYb5+ymUroZyRnuB2G5rsyB0CfgsE
78j9pojH3P+r36x9WFzY1YPAAcLYjqgCqaA/Wg+xEGU/BB5P2NZbf6vDTHDPSJ+T
2WS/3Ih5ubrDoRCxa3g8t90v/YDrNVTcIieBo84tkQuBcMe+rSzA+90wQwVOTZKi
2ZWCBZYRb6C2ezSl30J9ABEBAAGJAjwEGAEKACYWIQSDRZS0ktpq5csj81bojQUr
Mmv87gUCZB246gIbDAUJDShogAAKCRDojQUrMmv87r23EADAWx5SyFHMOsCh6hC+
1Rj6GCXMPYYMhpvaizJRTQDA0SU4RzyWoaP60bZiWdowu0I2SQZOqZR29ao0mmCX
t4g3U8RlU25pC63oS2Y06IVhiDlOoEK0xzIqgAhl5N0hiuNCnKBNMQJisCrlq0ac
PQpT8Ms7BwlBkxCfyM22C2gAkTw6aYx3rdGbLeQf0MyNf257QB0V7eT1vMyEAlY+
FewZqFawY+YH6QbeUmilnYuaRK2xlbVWbSc6b7B9IGKgcjAB+82B0zp0D6ozuR/F
2xeKrkV/+j1t/zc9KLCxGlcww3NffiVi4U+CWkZJZBi+9E7DvzVr1LlbNw+KTxoS
U+3Tm+Ff/0VgXTh4RjoquZSNF8mTjjE4VGHpi3URL55U1WuiLPrtCepZMcfNMS/T
XWqNELg89P6R/HIM9xy+afuAh2Psr6nMJUWcLBJ9vatQh/VjhfitEAaGbe6+I0MK
/4KV08KssTPYGEYqB6dGWtgyP7zPKQAkkxS7pYf51rrvqhNz11xXGo2oRRIsAjWJ
H0HNDhDcgj+9sh8dTMQUWIlB5z0CQ8KsbFyJwFGHXH0aG+400LicErMFkB1CbRzC
YBJN132NXzxWv41eu5TRgjdsFrDuIEVs4S/dO2vFj98eB/H57P0D+ZyO/jMOlTqy
w+zqCX5kaMU1M9oA1CC7DP7Waw==
=3DzL
-----END PGP PUBLIC KEY BLOCK-----

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by cube2222** [comment]
Thanks for the submission!
