### ISSUE TITLE
Error while installing registry.opentofu.org/opentelekomcloud/opentelekomcloud v1.36.4: authentication signature from unknown issuer

### ISSUE THREAD

**Issue by steffeneichler** [opentofu/registry#321]
### Thank you for reporting an issue.

Hi,

I'm not a able to init a stack which requires opentelekomcloud provider.
```
╷
│ Error: Failed to install provider
│ 
│ Error while installing registry.opentofu.org/opentelekomcloud/opentelekomcloud v1.36.4: authentication signature from unknown issuer
╵
```

Same provider version provided by hashicorp registry and loaded via `terraform init` is working without problems.

I also opened a issue at opentelekomcloud github project.
https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/2470

Because I'm not sure who is responsible for this provider.

### OpenTofu Version

```shell
OpenTofu v1.6.2
```

### OpenTofu Configuration Files

```hcl
resource "opentelekomcloud_compute_keypair_v2" "OTCComputeKeyPair" {
  name       = abc
  public_key = file("files/public_key.txt")
}
```

**Comment by ghost** [comment]
Hi @steffeneichler I tried to reproduce the issue but only got a warning:

```
$ tofu init

Initializing the backend...

Initializing provider plugins...
- Finding opentelekomcloud/opentelekomcloud versions matching "1.36.4"...
- Installing opentelekomcloud/opentelekomcloud v1.36.4...
- Installed opentelekomcloud/opentelekomcloud v1.36.4. Signature validation was skipped due to the registry not containing GPG keys for this provider
```

Is it possible you have set `OPENTOFU_ENFORCE_GPG_VALIDATION` to true? If so, then the OpenTelekomCloud project will need to publish their GPG key in our registry.

Edit: I've posted the exact steps needed to publish a key [on the opentelekomcloud issue](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/2470#issuecomment-2002065453).

**Comment by Nils-Magnus** [comment]
Hi @janosdebugs , hi @steffeneichler,

I am the product owner and architect for the opentelekomcloud provider for this other product. I had opentofu on my list for a long time, so thanks for reminding me eventually!

IIRC, the [provider](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud) as such should work for both projects without any change, but we need to provide some GPG signatures. Could please kindly point me to some process and format documentation that explains how this workflow works in detail? What do you accept as proof of identity for me/us here from opentelekomcloud?

**Comment by ghost** [comment]
@Nils-Magnus you meet all the requirements since your membership in `opentelekomcloud` is public. You can just [submit your GPG key here](https://github.com/opentofu/registry/issues/new?assignees=&labels=provider-key%2Csubmission&projects=&template=provider_key.yml&title=Provider+Key%3A+&namespace=opentelekomcloud). If you need any help, please let me know.

**Comment by Nils-Magnus** [comment]
Well, @janosdebugs, I'd like to learn a bit more about when would you use the key to do what and why. Do you expect a key from me or from the team, are there any requirements about its subject, its keylength, its method, etc. I guess there is somewhere either some documentation or at least a sample I could look at?

**Comment by ghost** [comment]
@Nils-Magnus we publish the GPG public key you provided in the OpenTofu registry so that users can verify the signature on your provider. It needs to be the same public key you (presumably) already published in the Terraform registry. We do not need access to your private key.

**Comment by ghost** [comment]
We have some documentation on plugin signing here: https://opentofu.org/docs/cli/plugins/signing/

**Comment by Yantrio** [comment]
I've left a comment here for the uploaded key: https://github.com/opentofu/registry/issues/396

**Comment by Yantrio** [comment]
Closing as this seems to be fixed now 🙌 

![image](https://github.com/opentofu/registry/assets/237469/d48a3e9c-7621-492c-8411-d0ddd8320e7c)
