### ISSUE TITLE
Add Hashicorp/powerdns GPG key

### ISSUE THREAD

**Issue by franklouwers** [opentofu/registry#333]
### Thank you for reporting an issue.

When using the `powerdns` provider, tofu reports:

```
- Installed hashicorp/powerdns v1.5.0. Signature validation was skipped due to the registry not containing GPG keys for this provider
```

### OpenTofu Version

```shell
OpenTofu v1.6.2
on darwin_arm64
```

### OpenTofu Configuration Files

```hcl
provider "powerdns" {}
```

**Comment by Yantrio** [comment]
This provider is a redirect as defined here. 

https://github.com/opentofu/registry/blob/main/src%2Finternal%2Fprovider%2Foverrides.go#L70

You may want to raise an issue on the provider author repository here: https://github.com/pan-net/terraform-provider-powerdns

**Comment by franklouwers** [comment]
https://github.com/pan-net/terraform-provider-powerdns/issues/101

**Comment by ghost** [comment]
Closing this issue as there is nothing the OpenTofu team can do here.
