### ISSUE TITLE
unexpected error in provider 

### ISSUE THREAD

**Issue by jogarao96** [opentofu/registry#340]
### Thank you for reporting an issue.

│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to cloudflare_ruleset.rate_limiting_wild, provider
│ "provider[\"registry.opentofu.org/cloudflare/cloudflare\"]" produced an
│ unexpected new value: .rules[1].ratelimit[0].mitigation_timeout: was null,
│ but now cty.NumberIntVal(0).
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵

### OpenTofu Version

```shell
opentofu 1.6.1
```

### OpenTofu Configuration Files

```hcl
resource "cloudflare_ruleset" "rate_limiting_wild" {
  zone_id     = 123456789
  name        = "Requests from ips that exceed requests per minute"
  description = "apply HTTP rate limiting for a route"
  kind        = "zone"
  phase       = "http_ratelimit"

  rules {
    action = "block"
    ratelimit {
      characteristics = [
        "cf.colo.id",
        "ip.src"
      ]
      period              = 60
      requests_per_period = 120
      mitigation_timeout  = 300
    }

    expression  = "all(http.request.headers[\"cf-cache-status\"][*] ne \"HIT\")"
    description = "Requests from ips that exceed 120 requests per minute"
    enabled     = true
  }
```

**Comment by cam72cam** [comment]
> This is a bug in the provider, which should be reported in the provider's own issue tracker.

Please report this to https://github.com/cloudflare/terraform-provider-cloudflare
