### ISSUE TITLE
Any way i can use centralise location to refer provider.tf for customise plugin location?

### ISSUE THREAD

**Issue by yogeshlc** [opentofu/registry#343]
### Thank you for reporting an issue.

I want to use custom plugin & I have 5 different terrafrom (opentofu) resource template placed at different location. But i dont want to refer the provider.tf for all the resources every time i am doing "tofu init".
I tried using .terraformrc to provide the custom location for plugin but it seems not working.

Any idea?

### OpenTofu Version

```shell
opentofu version: 1.6.1
```

### OpenTofu Configuration Files

```hcl
// Snippet of HCL that can be used to help reproduce this problem
```

**Comment by ghost** [comment]
Hey @yogeshlc thank you for posting your question. Unfortunately, this is not the right place to post questions as this is neither a bug nor is it related to the OpenTofu registry itself, but related to the Tofu language. I will close this issue. Please use the [GitHub Discussions](https://github.com/orgs/opentofu/discussions) or the [OpenTofu Slack](https://opentofu.org/slack) to ask questions.
