### ISSUE TITLE
Hetznercloud key not working

### ISSUE THREAD

**Issue by xoxys** [opentofu/registry#354]
### Thank you for reporting an issue.

After https://github.com/opentofu/registry/issues/352 installing, the provider does not work anymore:

```
tofu init -upgrade

Initializing the backend...

Initializing provider plugins...
- Finding hetznercloud/hcloud versions matching "1.45.0"...
- Installing hetznercloud/hcloud v1.45.0...
╷
│ Error: Failed to install provider
│ 
│ Error while installing hetznercloud/hcloud v1.45.0: authentication signature from unknown issuer
╵
```

\cc @jooola

I have also created an issue at the provider repo that might be related https://github.com/hetznercloud/terraform-provider-hcloud/issues/906

Can the PR https://github.com/opentofu/registry/issues/352 be reverted until its fixed?

### OpenTofu Version

```shell
tofu version
OpenTofu v1.6.1
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = "1.45.0"
    }
  }
}
```

**Comment by ghost** [comment]
Hey @xoxys Hetzner submitted a GPG key in #352 today and it seems that the wrong key was submitted. We are reverting the PR and started the synchronization process, this should be sorted out shortly.

**Comment by jooola** [comment]
I'll have a look.

**Comment by ghost** [comment]
Thanks @jooola !

**Comment by jooola** [comment]
This has been solved with the new key.

![image](https://github.com/opentofu/registry/assets/19195485/b37bd36c-ac4a-483b-b7cd-9f8444dc4958)

**Comment by Yantrio** [comment]
can confirm, this is working for me too.

![image](https://github.com/opentofu/registry/assets/237469/c519b4c9-1478-4532-a62c-dc1bc233cb04)
