### ISSUE TITLE
Registry provider update issue/question

### ISSUE THREAD

**Issue by Doridian** [opentofu/registry#382]
### Thank you for reporting an issue.

I have published a new version of my Terraform provider yesterday, and it seems the regular update jobs run quite frequently, yet they don't seem to have picked up the new version of my provider.
Provider is here: https://github.com/opentofu/registry/blob/main/providers/d/Doridian/hexonet.json
( Which should pull from here: https://github.com/Doridian/terraform-provider-hexonet )

I tried looking at the Actions logs to see if there's any errors related to my repository/provider, but I couldn't even find a line mentioning it.

**So I guess I am mostly asking for guidance here**: Is there something wrong with my provider? Does the job, despite running, only update a subset of repositories at a time and I just need to wait a bit longer? Is there something broken on your end? Something else?

Thanks in advance for any help.

### OpenTofu Version

```shell
Irrelevant, but
OpenTofu v1.6.2
on darwin_arm64
```

### OpenTofu Configuration Files

N/A

**Comment by cam72cam** [comment]
Hi, thanks for the report!  This may be related to something I've recently changed.  Let me dig in

**Comment by cam72cam** [comment]
Should be all set.  One of the filters I used to break up and parallelize the job was case sensitive, which has now been patched and deployed

**Comment by Doridian** [comment]
Yep, it seems to have successfully pulled in my provider now. Perfect, thanks! :)
