### ISSUE TITLE
OVH key not valid for all providers in namespace

### ISSUE THREAD

**Issue by ghost** [opentofu/registry#385]
### Thank you for reporting an issue.

The key added for ovh in #346 / #347 is only valid for the provider ovh/ovh, but not for the other providers in the ovh namespace (ovh/eyaml, ovh/mimirtool, ovh/mixtool), leading to them beeing uninstallable:

```
Error while installing ovh/mimirtool v0.1.2: authentication signature from unknown issuer
```

CC @rbeuque74

### OpenTofu Version

```shell
OpenTofu v1.6.2
on linux_amd64
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_providers {
    mimirtool = {
      source  = "ovh/mimirtool"
      version = "0.1.2"
    }
  }
}
```

**Comment by rbeuque74** [comment]
Hello,
I will fix this
