### ISSUE TITLE
Module: elasticache

### ISSUE THREAD

**Issue by xlejakx** [opentofu/registry#400]
### Module Repository

terraform-aws-modules/terraform-aws-elasticache

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by Yantrio** [comment]
Hi @xlejakx , I'm looking into why our automation failed here. Please bear with me whilst I investiate :)

**Comment by Yantrio** [comment]
@xlejakx I hope you do not mind but I edited your form submission to just be the repository name in the format that we expect and not a full github link. This allowed our automation to work
