### ISSUE TITLE
Question: How do I look up documentation on providers/modules in OpenTofu registry?

### ISSUE THREAD

**Issue by msamendinger** [opentofu/registry#408]
With terraform I'm used to browse the documentation on a provider or module on the registry eg. https://registry.terraform.io/providers/spacelift-io/spacelift/latest/docs

How do I look up provider and module documentation on providers or modules for the OpenTofu registry?

**Comment by ghost** [comment]
Hi @msamendinger the OpenTofu registry currently doesn't have a UI, but the data is right in this repository. Additionally, you can use [library.tf](https://library.tf/) to look up modules and providers across multiple registries.

**Comment by msamendinger** [comment]
Thanks @janosdebugs for the link to [library.tf ](https://library.tf) that comes really handy! And I guess that would be the site to go if there is a provider/module hosted on opentofu but not terraform registry.
Please excuse if this is not the right place to ask but can you explain "the data is right in this repository" in a bit more detail?
If I search the repo for `spacelift-io`, just an example as I'm working with it atm, I see json files pointing to the GitHub repository for the spacelift terraform provider. In the providers GitHub repository I can see the markdown files.
Are `registry.terraform.io` and `library.tf` parsing the markdown files out of these repositories?
Sorry have no insight into how the registries work and compile the documentation.

**Comment by ghost** [comment]
Sure, so there are three directories:

- [modules](https://github.com/opentofu/registry/tree/main/modules)
- [providers](https://github.com/opentofu/registry/tree/main/providers)
- [keys](https://github.com/opentofu/registry/tree/main/keys) (GPG signing keys for providers)

Each of these folders contains more folders with the starting letters of the GitHub namespace of the author (username or org). You can dive further in to find the JSON structure that describes what the registry contains. This is what the registry then generates the final format from, which is hosted on Cloudflare. As you will see, the registry is only a "link" to the original GitHub repository, the download happens from the original repo.

**Comment by msamendinger** [comment]
Got it, thanks for the explanation!
