### ISSUE TITLE
Add the ability to add provider warnings

### ISSUE THREAD

**Issue by Yantrio** [opentofu/registry#410]
### Description of the feature you are looking for.

`tofu` understands that if the .Warnings field is populated when fetching metadata about a provider that it should display those warnings to the end user.

Right now we don't have a method to add a warning to a provider or a specific provider version in this registry. We should allow people to fill in a form for a whole provider, or just a provider version to add warnings that will be displayed when users try to install a provider.

**Comment by cube2222** [comment]
I'd prefer doing this in a non-freeform way if possible.

That is, introducing fields like `"mark_as_bad": bool` that we would then translate to standardized error messages when rendering.

**Comment by ghost** [comment]
The way this is currently implemented in OpenTofu and legacy Terraform using an undocumented `warnings` field in the version listing response. This applies to all versions of a provider, there is currently no way to issue a per-version warning.

References:

- [OpenTofu](https://github.com/opentofu/opentofu/blob/34a0e515b9f3f7fd83d6b7243417f0873718d60b/internal/getproviders/registry_client.go#L138)
- [libregistry](https://github.com/opentofu/libregistry/pull/34/files#diff-e2f6ea7b85d28b2f3a35bcc2c7dd7aa9998bef68162afdf3877ea0ba3ae689f2R54)
