### ISSUE TITLE
Consider handling checksum changes of existing releases

### ISSUE THREAD

**Issue by birjj** [opentofu/registry#417]
### Description of the feature you are looking for.

_Inspired by https://github.com/Azure/terraform-provider-azapi/issues/477, which is currently causing issues with the `azapi` provider._

Although bad practice, it happens occasionally that the checksums of specific releases are updated in-place. This recently happened to the `azapi` provider in [v1.13.0](https://github.com/Azure/terraform-provider-azapi/issues/477), and has previously happened to Terraform itself in [0.11.13](https://github.com/hashicorp/terraform/issues/20661) and [1.3.9](https://discuss.hashicorp.com/t/change-in-sha256sums-for-terraform-downloads/52522).

The current way that the OpenTofu registry works means that changes to hashes after a release has been created won't be picked up. Instead, a hash mismatch will happen until the affected provider releases a new version.

I'm mostly opening this issue in the hopes of creating official discussion on what OpenTofu's approach to this is. In particular:

1. Should changes in checksums be supported? It goes without saying that changing hashes is bad practice (what if someone has already committed the checksum to their lockfile...), but it happens. Terraform's registry supports changes to hashes, as evidenced by the new shasum in [`azapi` v1.13.0](https://registry.terraform.io/v1/providers/azure/azapi/1.13.0/download/linux/amd64). I fear that these kinds of issues might cause people to switch from OpenTofu to Terraform, as that makes the error go away.

2. If it should be supported, how is that best implemented?

**Comment by ghost** [comment]
Hello @birjj thank you for this issue! The core team regularly reviews new issues and discusses them, but this can take a little time. Please bear with us while we get to your issue. If you're interested, the contribution guide has a section about the [decision-making process](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#who-decides-if-a-feature-will-be-implemented-and-how-is-that-decision-made).

**Comment by cam72cam** [comment]
I'm pretty sure this is a duplicate of https://github.com/opentofu/registry/issues/278

**Comment by birjj** [comment]
So it is. My searching missed that - sorry!
