### ISSUE TITLE
Why is my username present in your repository? 

### ISSUE THREAD

**Issue by mBlomsterberg** [opentofu/registry#426]
### Thank you for reporting an issue.

![image](https://github.com/opentofu/registry/assets/98821063/b3d231ac-14da-435a-8cde-6dfa301dba2b)

### OpenTofu Version

```shell
Not related to versioning
```

### OpenTofu Configuration Files

```hcl
// Snippet of HCL that can be used to help reproduce this problem
```

**Comment by Yantrio** [comment]
The OpenTofu registry scraped public github repositories for modules and providers and included those so that people can easily migrate from terraform to opentofu.

If you do not wish for your modules and/or providers to be in the opentofu registry we would be more than happy to remove them.

**Comment by mBlomsterberg** [comment]
Interesting approach... the module is public so I don't mind. But it would have been nice if you added the explanation somewhere in the file.
