### ISSUE TITLE
Hashicorp Azurerm 3.101.0 not imported?

### ISSUE THREAD

**Issue by aneillans** [opentofu/registry#428]
### Thank you for reporting an issue.

Hashicorp Azurerm 3.101.0 provider was released about 3 days ago now (https://github.com/hashicorp/terraform-provider-azurerm) but it looks like it hasn't been imported automatically into the registry from the actions; last update was 2 weeks ago? 

### OpenTofu Version

```shell
N/A
```

### OpenTofu Configuration Files

N/A

**Comment by cam72cam** [comment]
Looks like the latest we have is [3.100.0](https://github.com/opentofu/registry/blob/c38a0d2/providers/h/hashicorp/azurerm.json)

Taking a look.

**Comment by Yantrio** [comment]
Hi! thanks for bringing this to our attention. This issue has now been resolved and 3.101.0 is available.
