### ISSUE TITLE
owner field should not be case sensitive when submitting a module

### ISSUE THREAD

**Issue by dkooll** [opentofu/registry#503]
### Thank you for reporting an issue.

When publishing a module using `{owner}/terraform-{target}-{name} the owner field should not be case sensitive as in the public hashicorp registry this is also not the case.

### OpenTofu Version

```shell
OpenTofu v1.7.1
on darwin_arm64
+ provider registry.opentofu.org/hashicorp/azurerm v3.103.1
+ provider registry.opentofu.org/hashicorp/random v3.5.1
```

### OpenTofu Configuration Files

Both should work

```hcl
module "storage" {
  source  = "cloudnationhq/sa/azure"
  version = "~> 0.1"
```

```hcl
module "storage" {
  source  = "CloudNationHQ/sa/azure"
  version = "~> 0.1"
```

**Comment by cam72cam** [comment]
Thanks, well hop on this first thing next week!
