### ISSUE TITLE
PaloAlto Module not working

### ISSUE THREAD

**Issue by a83r** [opentofu/registry#543]
### Thank you for reporting an issue.

Hi,
yesterday I created [Issue](https://github.com/opentofu/registry/issues/529) and it was pushed yesterday. But I cant curl or use the Module. It always shows me same error, other Modules in the PaloAltoNetworks Modul Folder work flawless. 

Source definined in main.tf 
  source  = "PaloAltoNetworks/swfw-modules/aws//modules/bootstrap"

 Module PaloAltoNetworks/swfw-modules/aws ("FIREWALLNAME" from main.tf:123) cannot be found in the module registry at registry.opentofu.org.

### OpenTofu Version

```shell
OpenTofu v1.7.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.49.0
+ provider registry.terraform.io/hashicorp/random v3.3.2
```

### OpenTofu Configuration Files

Module Source definined in main.tf 
  source  = "PaloAltoNetworks/swfw-modules/aws//modules/bootstrap"

**Comment by ghost** [comment]
Hey @a83r thank you for letting us know, I'll take a look right now.

**Comment by cam72cam** [comment]
Looks like the generation step was correctly executed here: https://github.com/opentofu/registry/actions/runs/9114254641/job/25057720797

**Comment by cam72cam** [comment]
@a83r We dropped the ball on a migration for upper/lowercase paths.  Everything should be working now, sorry for the inconvenience!
