### ISSUE TITLE
Provider Key: germanbrew/hetznerdns

### ISSUE THREAD

**Issue by kimdre** [opentofu/registry#615]
### Provider Namespace

germanbrew

### Public Membership

- [X] I have made my membership public

### Provider GPG Key

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQGNBGZRsdABDAC5X2nDVYPvSpzlWDMcfYxUAhKMjSxwftw+VATWVp6A5y5NPD4u
W3frv8QXDXEeqZRz4D19UXDDn+cQzfAXY+f5XXb866qGFb2wSAUpHNzCEYH5dg9U
RQy/8FQc9GOuSQXCwmiS5zqKULuHq6p//nnjWEYnnlGMkTnYDhYxLQfAX2dpvUES
na0wibzr5NpTa4mkkIGOHr9BF4RHW7qHD9K3swGTpAR2KiijB6KEabRPWFnprn3X
0cybN1ZcufIeOiQdEqyhLaTkn7NhrSh787GSNcLpS2u9sdOZSqjWOCfZMLxtOa2U
3haKjN7Jq4s6ASoxGUHFrIqqKnPBzaRmFYVu8KzgMoihF2sFOvLkP7OB/Sbvq7Ht
9a4kpHJvMFdyq7jTguX8D4pzNyigL901l9SgfQ3zqLyL7yiAta1jIehmmAN971P6
gk+t5B8tcxxL6BvAY9eH4i6+/9U4kLD6x7LavR5GStvZR2a28LnOW1Uq9NRZU8vk
dER11oVigurzw98AEQEAAbQjR2VybWFuIEJyZXcgPGdlcm1hbmJyZXdAbWFraS1p
dC5kZT6JAdEEEwEIADsWIQSLxemY+VES7gGiBFWHIZkf+pdKfAUCZlGx0AIbAwUL
CQgHAgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRCHIZkf+pdKfKmTC/9r4qJOaONy
1vjL/grVzcLy0goQvdDWlNf0UFDpYDbAuKB532MfU5eDMz78EXtCo5hUmI08npjK
mv4AMAazgMvdReaJfHjRtamaY9gNUoKCReoaJ0hyUOHNpbWtAer+pgkwEsH4yRoP
DmZxQ+EWAcxOPXo5Tfoq21i9srRmhiUCBFPRs+cOJ2upmDh97Ttw5wJxbCrvq3Es
St/d/8VzdRaxD4Ku4waUURC3+KyBDnNUR0D5QAmwejRaJ8e4ViQEh4d4WOR7hgA7
6p8qprPCWcoF4jbVt0pzgOZBUm13xOz8AUKJ8KaE8Wb0wXMOor3lm1XAK1b9QmJb
XLzAl68DCmzoJs6NtrROyZS4RqzyMf3nJJ6002AXnnnUQzBVH9bChZkUnaG8iTt3
0aCbmNadk2r5los2NGTWZerMMpmeo3B3jvN0wI2EzExS2tVBpOuj/fpgx3+s2RXq
KI9+9oArowO14MDELy9Kr241skuRNuyNalDV48HScdiUoZtYicg60c25AY0EZlGx
0AEMALZrO0QOaBq3u67EqvaY4ssmhNLZ0XE6r24iDRG+5uN3a3Inqx3imbZb3t3W
FBz6Y/5g/LapjnNWGM63S8vYWl/yGbsqh4EHyacY810xQMChfonu/tUQlpmYRMbX
1tM5fTYTdvqinucOqqGBCjtGf+nGnI17ITFkwHxrECxNeQ4yhiKiChqOVlgtlGt7
mvIyd7Go+EJkSkQhTdG+qnULXC1SrWumocDrGSNMtwVoH27GELb3lA6jdbdaoci9
457/v/b0E6v1OfGERxWeqje2g26YRWEOgDXD2EF7VceUUUFATgAzs0BZzg2/LNYo
gaVGuehr77Ke8LYkZ8kVO297h38HfyHPbfG+pkhcjA9OHbB7bhOV6+zYtgaXEp5z
ULwSKbZ6zhuqMypezRPEnVdxzKSxFP/UOHydPSkIuwLcJURhlhIwMCvSEOOpZu5E
/WI32t1Ok/7CwtM76SXmAAtvft6v8yaMpH1844HIJgN2WGnTycCczu0bVfojp0HO
RzsBZwARAQABiQG2BBgBCAAgFiEEi8XpmPlREu4BogRVhyGZH/qXSnwFAmZRsdAC
GwwACgkQhyGZH/qXSnwmgAv+Ikf0Wc1PgfjnLjP8HB1DJjgt3RxRdapptLXiPOz5
RpWN5OWsZ0Uizh6cy9VPDTo/0S8sz1byTjmhUuGA8fRqjiXZfa3gBW4b7ca47vWo
ahayB7vePuqXkUuN+5KRFciqU7ZY5NPcQEzGEWGs4umaS0zW1xDqH6Z1aBwKgZs8
pqdSyoac8IZaIuYs0j5wA7FbkMjrCqHboAOjFkVeiWpyPqh38BLxgWvC1oJ5+5J1
WsedlsHeH+MPm6LdusaALbCHoboOzSE+N1dkI2nOHFmL6AiaWhvOTd646WHg+wcU
rWNj0qcBwQYXXmZIt04+Zbm9lX8zNTcPthLTz+1gexkCHPXieZmmaoCihLSPpO8O
424CYNjcvt/cMPRO4QgeZHPRPf+ABMLWyGvsuqbCTL/7YUNfvCMNShCSUOOC5/Jx
mrSp1/ofq6A8y/Xgu7U+0+FpnP4hRQPsakK/Qo22xUixtAFdVWL23hwPWWnEpZqx
kTMgWuu/tGeml+TXX2UdKviA
=8VrB
-----END PGP PUBLIC KEY BLOCK-----

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by kimdre** [comment]
I made my membership public now.

**Comment by Yantrio** [comment]
Thanks, I'll re-run the automated check 👍

**Comment by Yantrio** [comment]
Thanks for this submission @kimdre , It should be available on the registry in the next 30 minutes or so 👍
