### ISSUE TITLE
 Bump Provider and Module Versions github action stuck

### ISSUE THREAD

**Issue by MisterSquishy** [opentofu/registry#625]
### Thank you for reporting an issue.

provider versions havent been bumped in a couple days now, [this job](https://github.com/opentofu/registry/actions/runs/9242509462/job/25425444578) appears to be stuck awaiting approval. can someone click the magic button here? i just released a new version of my provider and id like to start using it

### OpenTofu Version

n/a

### OpenTofu Configuration Files

n/a

**Comment by cam72cam** [comment]
> bump-versions (q) is waiting for Production deployment approval

what???

I'll give it a swift kick.  Thanks for the heads up!

**Comment by cam72cam** [comment]
We even have a timeout configured in the job: https://github.com/opentofu/registry/actions/runs/9242509462/workflow#L23

I'm guessing there's some bug that mixed up jobs on GitHub action runners that we hit?

**Comment by MisterSquishy** [comment]
wooo i see my new version now!! thanks for the swift response

**Comment by cam72cam** [comment]
Job is now running, I'll keep an eye on it!

**Comment by cam72cam** [comment]
The generate and sync job should run within the next 15 minutes to push the new data.
