### ISSUE TITLE
Bad shasum values in latest v0.8.1 ariga/atlas provider

### ISSUE THREAD

**Issue by NathanBaulch** [opentofu/registry#639]
I'm not sure this is the right place to report this, but all the latest CRC values in `providers/a/ariga/atlas.json` are wrong, meaning it can't be installed. I've raised an issue in the upstream provider repo also - https://github.com/ariga/terraform-provider-atlas/issues/131

https://github.com/opentofu/registry/blob/ef0d4dd6e5ba944798334048a4a4fd5e735be580/providers/a/ariga/atlas.json#L11-L45

### OpenTofu Version

```shell
OpenTofu v1.7.2
on windows_amd64
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_version = ">= 1.0"
  required_providers {
    atlas = {
      source  = "ariga/atlas"
      version = "0.8.1"
    }
  }
}
```

**Comment by cam72cam** [comment]
It looks like their release process was run twice for the same release:
![image](https://github.com/opentofu/registry/assets/892136/2724d51f-ddb5-4208-926b-3c57b39ad931)

Versions/tags should be immutable.

**Comment by cam72cam** [comment]
Based on the git history of [registry/providers/a/ariga/atlas.json](https://github.com/opentofu/registry/blob/ef0d4dd6e5ba944798334048a4a4fd5e735be580/providers/a/ariga/atlas.json#L11-L45), it's pointing at the original 0.8.1 release.

This is the registry working as intended, providers should not be re-publishing the same versions multiple times.

We can make an exception if we hear from the maintainers of that provider to force resync that version.

**Comment by cam72cam** [comment]
@NathanBaulch sorry for the delay, this should be fixed within the next 15 minutes as the automated process catches up!

**Comment by NathanBaulch** [comment]
Thanks @cam72cam, LGTM. What's the process for getting the recent v0.8.3 version published?

**Comment by ghost** [comment]
@NathanBaulch when your GitHub release goes online, our registry should catch up automatically.

**Comment by cam72cam** [comment]
It's about a 15 minute process for both providers and modules

**Comment by NathanBaulch** [comment]
> when your GitHub release goes online

Meaning a release is created? That happened a few days ago... https://github.com/ariga/terraform-provider-atlas/releases/tag/v0.8.3

**Comment by ghost** [comment]
@NathanBaulch your release contains no binaries. You need to upload your build provider binaries, SHASUMS file, etc to GitHub Releases. The 0.8.1 release is the last containing them.

**Comment by NathanBaulch** [comment]
Good point, I'll ask the maintainers what's going on with their build actions.
I should probably clarify that this is not my project - I'm just a user trying to get a bug fix deployed!
