### ISSUE TITLE
Module: Rancher rke2 vsphere cluster

### ISSUE THREAD

**Issue by aditya-tanwar** [opentofu/registry#652]
### Module Repository

https://github.com/aditya-tanwar/terraform-rancher2-rke2-vsphere-cluster

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by aditya-tanwar** [comment]
This is a rancher module to create and deploy / manage ( autoscaling ) rke2 rancher cluster on vsphere platform.

**Comment by aditya-tanwar** [comment]
Please ignore the issues created before this .

**Comment by Yantrio** [comment]
Handled by #650 . Thanks for your submission!
