### ISSUE TITLE
[ tofu init ] Error while installing gitlabhq/gitlab v3.18.0: authentication signature from unknown issuer

### ISSUE THREAD

**Issue by Gilk260** [opentofu/registry#654]
### Thank you for reporting an issue.

When initialising a project using provider `gitlabhq/gitlab v3.18.0` get error:
```sh
╷
│ Error: Failed to install provider
│
│ Error while installing gitlabhq/gitlab v3.18.0: authentication signature from unknown issuer
╵
```

But when changing version to `v3.19.0` it works.

I have done some tests, and it looks like version < `v3.19.0` are broken. (Only try v3.17.0 to v3.20.0)

### OpenTofu Version

```shell
OpenTofu v1.7.2
on darwin_arm64
...
+ provider registry.opentofu.org/gitlabhq/gitlab v3.19.0
...


Done after testing with `gitlabhq/gitlab v3.19.0`
```

### OpenTofu Configuration Files

```hcl
// Snippet of HCL that can be used to help reproduce this problem
terraform {
  required_providers {
    gitlab = {
      source  = "gitlabhq/gitlab"
      version = "3.18.0"
    }
  }
}
```

**Comment by cam72cam** [comment]
@Gilk260 it appears that gitlab only uploaded their "latest" provider key and not one of their legacy keys. I can reach out to them about that today, but it's highly recommended to update to the latest version of their provider.

**Comment by timofurrer** [comment]
Maintainer of the GitLab provider here - I can take this over. 

@cam72cam do you mind assigning me to the issue so I won't forget?

**Comment by cam72cam** [comment]
All set @timofurrer, thanks for taking this!

**Comment by timofurrer** [comment]
@cam72cam here is the request https://github.com/opentofu/registry/issues/655 - PR got already created.

**Comment by cam72cam** [comment]
Merged!  Should be deployed within the next 15 minutes.

**Comment by cam72cam** [comment]
Thanks @timofurrer!
