### ISSUE TITLE
hashicorp/google-beta v5.33 still unavailable

### ISSUE THREAD

**Issue by wyardley** [opentofu/registry#659]
### Thank you for reporting an issue.

e71248f172cd775e10ac672d09db57a7615cbf9c didn't include `google-beta` (I've seen this before sometimes where there's a bit of lag in their release process) - but doesn't seem to have caught up / gotten fixed yet. Is it expected that it will take this long to update if it wasn't caught then? I waited a couple of days, but still doesn't seem to have gotten fixed.

It does appear to [exist on the terraform registry](https://registry.terraform.io/providers/hashicorp/google-beta/latest)

```
Initializing provider plugins...
- Finding hashicorp/google versions matching ">= 3.33.0, >= 3.83.0, >= 4.25.0, >= 4.51.0, >= 4.64.0, 5.33.0, < 6.0.0"...
- Finding hashicorp/google-beta versions matching ">= 4.64.0, 5.33.0, < 6.0.0"...
- Installing hashicorp/google v5.33.0...
- Installed hashicorp/google v5.33.0 (signed, key ID 0C0AF313E5FD9F80)

Providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://opentofu.org/docs/cli/plugins/signing/
╷
│ Error: Failed to resolve provider packages
│ 
│ Could not resolve provider hashicorp/google-beta: no available releases
│ match the given constraints >= 4.64.0, 5.33.0, < 6.0.0
╵
```

### OpenTofu Version

```shell
OpenTofu v1.7.2
on darwin_arm64
+ provider registry.opentofu.org/hashicorp/google v5.29.1
+ provider registry.opentofu.org/hashicorp/google-beta v5.29.1
```
```


### OpenTofu Configuration Files

```hcl
terraform {
  required_version = ">= 1.6.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "5.33.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "5.33.0"
    }
  }
}
```

**Comment by cam72cam** [comment]
Looks like the release was published 3 days ago: https://github.com/opentofu/terraform-provider-google-beta/releases 

I'll dig into it

**Comment by cam72cam** [comment]
Looks like our version bumper was stuck " bump-versions (a) is waiting for Production deployment approval ".  This is a bug we have seen before in github actions.

**Comment by cam72cam** [comment]
Should be fixed, we'll open up a support ticket with github as this is the second time this has happened
