### ISSUE TITLE
Be more tolerant of missing repositories when bumping versions

### ISSUE THREAD

**Issue by Yantrio** [opentofu/registry#66]

**Comment by cube2222** [comment]
Collect and print a list at the end maybe?

**Comment by cam72cam** [comment]
@Yantrio I believe this is a duplicate of https://github.com/opentofu/registry/issues/48

**Comment by Yantrio** [comment]
it isn't. What happens here is that when we fetch the list of tags using the rss feed, it throws a 404 :(

**Comment by cam72cam** [comment]
Ahhh, fair point.  Different error path.
