### ISSUE TITLE
Provider Key: GitHub

### ISSUE THREAD

**Issue by kfcampbell** [opentofu/registry#675]
### Provider Namespace

integrations

### Public Membership

- [x] I have made my membership public

### Provider GPG Key

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBF9QTrEBEACfOug9ZAgK65C5eoA0YcdKH9Y52QTx+++W5C3rsIQJ+dweH9eR
kzGF2J0hgCXAmAAjP+GnFL+7nzdRAgtLmZX7MfU7lLjiIrwKSGJiY+jF6gYQvBVF
0N38fksdEQ5jBQfszQBkZhiz4zLUlnzKcopaioNe4/YsYSc0z9D4W5rY9FBhmdqF
spM70/rW69g3GMAaY8FU/ebv13ClQGYz7q/5VoTuzD30KEyumXhiQ3UXQ/YxUO02
JrOH9IDSykJBk4qp6eyKoca3WyX5jlvp0fpK805Cd0t8oQQa39DvhYaWIWI+YMZv
p7aB5N8XD3SCpba2NwLMgqqKn0NQuNBPeGaLRhW0owdTeqoLIyfnVIABVcyVyEJL
4NaqbrTMpMXF2R9j92AeGRM+++a3NP4lDx8QrkLW1bodbBnKGYtcbc63sjtNHRPt
wRhDrdzH6Ps+O+NmZK68p/IhUt9+MmA5JBMyrFXd7qIqPiVL/Ai/iVtJ3c4dazun
QEo+faiW+tI95L+4rpbyHpb1wXp3Vg3pUyH0nYG2rA9dZHupX0SB/1+lwrfrzykM
07dyHEX9WPXBecD8fjp4VTyYnFyQ3c2Jq1xeO/3FzV/Dg1SeC+sEXnBL8odw9nNh
Ukhq76H3y1r5LhIYuQ31axMqnmMFxhL/xtlJi5gL6hXPzurpHspRiYMQNQARAQAB
tJN0ZXJyYWZvcm0tcHJvdmlkZXItZ2l0aHViIChodHRwczovL3d3dy50ZXJyYWZv
cm0uaW8vZG9jcy9yZWdpc3RyeS9wcm92aWRlcnMvcHVibGlzaGluZy5odG1sI3By
ZXBhcmluZy1hbmQtYWRkaW5nLWEtc2lnbmluZy1rZXkpIDxqY3VkaXRAZ2l0aHVi
LmNvbT6JAk4EEwEIADgWIQTzGSj6zlLxoTpsYOo4An+A1/1fsgUCX1BOsQIbAwUL
CQgHAgYVCgkICwIEFgIDAQIeAQIXgAAKCRA4An+A1/1fsqjED/0Uj/HEIkJOtDvk
0YJW6qUcnJcWY4xNJvskIMThdIi7jKzlUchN4N7UiuOiZDFWYCQZWf6hupvHGbIl
K7WHZ/N2U6GAGoqSWKW/WAvxbxGw2Rh+zmP78KGb6U0EdWCun9ph11XnGdyrHwWY
sSAWrT2NGOp9YW+bIvPbHU5GYdSCpbirkaEArrMroOoySwx32L0L4mEcI+B3ZgD+
TTyOWbszKCo2D/3/jBO14Pz0UBiDM9gyuPc2q88yXDq90Y+QVPjWNPRqVo6Fv7+P
NNqI0uNEl2RJT3fDaY7FUBv2p0LZJ/ptZcK661iBW8Y8WfqwQwVBDV02KwjO0iGX
+mWrbSJVt8fzVLtN7y7aYKZwSRXKxwjGLl3+5/OPmDolTJsBPYRTduqd0OOp9V+L
HTDDOcnmLpMHHO6LYK16f3mNvBGKQ5ObK+tHq/Lm5ICwqS02lHmRWv3+y4pdwybo
4z5O/RJ9oVVvNV9L/hx0XMJVbqG5N84nyWVmLQmW4ni8xNufzss3nAeQ+4k7nouq
x7R29bwnlBg767r5LyasN68RR2261Cjszip6fDxgQ1BXH3OM+JxRKY3fDazu9uVW
O3mzouU3o6I8+L1sj4v5UUAENkgaWx/EopbY8rMRY+t9z473RwgXyZgpuvJwR4OA
NF7FgxjYMZOsZLucnNeY+YeC1K7J9bkCDQRfUE6xARAAzcO03WRnLwOjFEcT0uuN
zQLYOwF1GZHggcKuioTPFiWfM+XBKpDMOOCA6Zatt2XB0jxAkm02bMz+O25+Nukd
FRYMfk/51/Y+iN3dET7B9wXq6RzbwTvqCvMZ9ZU8IAO3tQiC1QSewhzstxgFcFmq
x6EoJtC/O9iw+VcWCB2FMeIu8nBBRFcI7bVJDLqVvm0GJFzKpSNmqSBDd5nU66oz
AaDR1d7P9y9gJh8VAaelb47FBANcvGmb9IOfyHmD+4DhgVijCARqGTCEP2Xp8Zeo
Z0YUrG1/ePYPTFIs+nYCGJ1Bk9MDn5agqr5ifswxYxFsZJdQ9ybEfrgAnxuQLi8l
bluhclE5/a5nKVs8LKWFM+/MqtLOVY2HYbQxE4PVtnuMdbm7zB2D8ZxYqUCOEnXO
TQTe9byqkUqDENECOadimdp7qtfDmK2JRzUkuLX/GHvN9Fg5z9NvKkp56T3fvEsW
mS5ztWp/VCHlYl2swDl9bwEftj5ql4Oc1Bs1uKJLHy9tImeQg/RZWPC25P9NPycl
DDFC6L69iyojecJgy7UaQX9KgmZx7Lj2gHx1eBwhLPayGguP17Fmv9hGs0QY4cUz
v3caFb0/6V0puDfFc/g4ADF+c47csWeI90x++WMtlw2mKLhPK09aN2B9No4CrC4n
QeRKXhH4y/iYNHA3z3Dt4lUAEQEAAYkCNgQYAQgAIBYhBPMZKPrOUvGhOmxg6jgC
f4DX/V+yBQJfUE6xAhsMAAoJEDgCf4DX/V+yv5IP/ip8bkvIajJsgmRXOda1vXSn
bH9835jHoirRFm6zhMsVwW/VB35HkS9qOlWLn3hiGQBZ4QODnva03QNlXGEjImMj
1AAZ6vJHbml9Ger+jqZQTW4kvKhSBHyFqiZoerUiUvncHaj8ZEJHMNPNiaG61bRD
mGHJHAOqWM7ozC4ySPJqYORvjiiVSJvrIt4PPt9ggh6vnB9Ri9c/BrIg8k0+xW2Y
uXHgu5iCKdxat7P6isEkieQcRU3NAUmYri64DMeWd5TU2ZLUfuQF3WG2GearcGNi
gWmwdaLRwRVv1CRhqeOCpGz8a7f086KGUfc+wf9a3aqML8vA34TBd6zvVK7hbTMH
jjy89b6T3zqW6Kw+rViCNUHeJsF0QVjh4Pq5ks2ujzzfPmFnOlGIDAsPeqdd4Ffd
ICINUy2HuWG3KPrB0x4aG9ImVDGby7TZaV3YJ+ne85xuGRWvOwjJFYJIiqscDp+l
0QXathNPLscOlXZ6XBWvmdA4K9ebEyP2IhxSVBAFNKH9ERZTHybWuEmDGYGZJLT5
hYZDwi30zNBO++PUogv2VZwwW3ktIFzGfLOe0xnZZHTLXP9yjaaqpQqsqTD8w26/
g48c8aczj3H3lnqgP5CQNJaGxNSqkXjG9wN18JdyFKdKJtyCLjcVt2G7IDDYH/7z
t4EYTJHRpHlgcIiZ8o2e
=iEY/
-----END PGP PUBLIC KEY BLOCK-----

### DCO

- [x] I sign this project's [DCO](https://developercertificate.org/)

**Comment by kfcampbell** [comment]
Please let me know if I've submitted this incorrectly or you'd prefer it in file upload form!

**Comment by ghost** [comment]
Thank you for your submission, the key is now added and should appear in the registry within ~ an hour.
