### ISSUE TITLE
authentication signature from unknown issuer

### ISSUE THREAD

**Issue by malhussan** [opentofu/registry#677]
### Thank you for reporting an issue.

We've recently submitted a provider (https://github.com/opentofu/registry/issues/662) and provider key (https://github.com/opentofu/registry/issues/668). 

When running `terragrunt init` which uses tofu, the following error still occurs:

```
│ Error: Failed to install provider
│ 
│ Error while installing registry.opentofu.org/meshcloud/meshstack v0.2.0:
│ authentication signature from unknown issuer
╵
```

I can verify that versions are available on https://registry.opentofu.org/v1/providers/meshcloud/meshstack/versions. 

### OpenTofu Version

```shell
OpenTofu v1.7.0
on darwin_arm64
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_version = ">= 1.0"

  required_providers {
    meshstack = {
      source  = "meshcloud/meshstack"
      version = "0.2.0"
    }
  }
}

```

**Comment by cam72cam** [comment]
Are you sure that you have uploaded the right key?  OpenGPG is returning "authentication signature from unknown issuer".

**Comment by ghost** [comment]
Hi @malhussan it seems that your provider is signed with the key ID 658FD66631E2C54AEBA8DD270E79DCB6FBCB38D9, whereas the key submitted is key ID 846707B19725FD82F02098952E2917A6EC3F1B5E belonging to one H. Dettmer. Please submit the correct key to resolve this issue.

**Comment by malhussan** [comment]
Thank you for the quick feedback!

I submitted a new key https://github.com/opentofu/registry/issues/678 (658FD66631E2C54AEBA8DD270E79DCB6FBCB38D9)

**Comment by ghost** [comment]
PR merged, should be updated within an hour.
