### ISSUE TITLE
Action "Bump Provider and Module Versions" is stuck

### ISSUE THREAD

**Issue by fcuello-fudo** [opentofu/registry#685]
### Thank you for reporting an issue.

There hasn't been modules updates for a couple of days it seems.

### OpenTofu Version

```shell
OpenTofu v1.7.2
```

### OpenTofu Configuration Files

```hcl
// Snippet of HCL that can be used to help reproduce this problem
// See https://github.com/opentofu/registry/actions/runs/9619138203
```

**Comment by cam72cam** [comment]
Thanks for the heads up! I've killed the stuck action and posted the update in my open support issue with github.  There's a serious race bug we are hitting in github actions.

**Comment by cam72cam** [comment]
Updates should be out in the next 15 minutes
