### ISSUE TITLE
AWS (and maybe other) provider is not available for freebsd_amd64

### ISSUE THREAD

**Issue by scratchifoo** [opentofu/registry#686]
### Thank you for reporting an issue.

Provider registry.opentofu.org/hashicorp/aws v5.55.0 does not have a package available for your current platform, freebsd_amd64.

### OpenTofu Version

```shell
OpenTofu v1.7.2
on freebsd_amd64
```

### OpenTofu Configuration Files

```hcl
// Snippet of HCL that can be used to help reproduce this problem
```

**Comment by ghost** [comment]
Thank you for the issue @scratchifoo, the binaries are not built for this platform. I'll take a look at it and try to get the build going.

**Comment by ghost** [comment]
@scratchifoo the fix has been merged now, when the next releases of the providers are released, a FreeBSD build will be included. Please reopen the issue if that is not the case. (Typically, within 1-2 weeks.)
