### ISSUE TITLE
Provider Key: newrelic

### ISSUE THREAD

**Issue by NSSPKrishna** [opentofu/registry#691]
### Provider Namespace

newrelic

### Public Membership

- [X] I have made my membership public

### Provider GPG Key

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBF6fRNEBEADJy/fJcjsyNK7of6OdTBSzPJZh9dFBq5XgIxDV8B8fpgiD/z7M
HiBXja5d6BmkPv5T5uAagySOjT7LK3Sj4C/fWPlk07cmaJbRaISbt5eLHmVKKA3z
niHqT9CecDWpgJhFpwLoHPzqCX1t2m7/lWBBJUc9R5EEfsz4p8hJ0C9f7y5zOT6N
Y87DIn6tXxZEjGkWNAfxnqxdcnI/cdj7Z62NNifV8NcOJDL+InghBQgzVzIctGh1
0S+Ohtg1Ukz8K/2f8VEbWZ96QtUFA7b3LdggzsAUKUPGxUwzTda5PKH1FyLdyBCK
9bTp9IM/eCncK54lwVMmTXmTgtMEVb6sPQWd9WtP0WAH1kMSvWnrJ6/8Cig/28OC
w6a1+a4Faev7sks5jvnKOLDEnD70JWQb9jty705lpK2Cz6G+fiNKi2hprlOMRagF
u8mFEbsXqWV1MYwuu3x026p37OjqF2cC/ns5LD5zcO5r/dSFlZBthTO/CWyHPxn6
EZXMy4ytw7SmHeUQS0CH7fQ3YnFz20FL1wyUUaclAvdvpwr2C6xf97m7Uk8Iq1MO
KndP33Zxv2R+SCV5nACvivPMMq3W5U+ziPZorYea25FVP2m5sJ0R8Jfes1EW3uoc
vSaBSptQVSjAVrYbplzxS74vriXXqlqKMCTf7b2s/rEL1GHY0h5zLiAoIwARAQAB
tDxEZXZlbG9wZXIgVG9vbGtpdCBUZWFtIDxkZXZlbG9wZXItdG9vbGtpdC10ZWFt
QG5ld3JlbGljLmNvbT6JAlQEEwEIAD4WIQSGvgHamx2h/PgoFAncn8ax/OR5hgUC
Xp9E0QIbAwUJBaOagAULCQgHAgYVCgkICwIEFgIDAQIeAQIXgAAKCRDcn8ax/OR5
hptKD/9TSP/0ljhyAQPZVDmtHKKf4JCZrx00gp5Ceay1dIZBQxCB8bAOKcPnsxmb
Dk5PpjslsmhRJ6ypqa4jWIKeywgwv9QD2AxJRz0597W11mrLImtW8I+jEyouNOQ6
H14Pf3KTUtuptaC1RAnt0LA+SnzE4mx2Dxe647JWz83L4y8Jn5oaXhY4W/khwaDv
FVH89g+g7BM/sSMmYNdVIfQ86PeQxxpGtfUQNR29b1qGNJLSsosvFvNVJYjSqOK/
uWb8fqvP36atPYFw1drAoQtquRBBtrFaJYaoRtmx541WSaY2T1ECm8x4wVZh+tB+
4zEOs9HZDGKvEn/2cN4NrnxKk3NSZ7RbxtSmrIZ+Wn2sVUvCjOrRUbg/DfeATf4a
fwIH41yipvKDZyDwF0JFUTGy5+z/8C3cp0mqJPA+6eeoYvx9WICmyK7YEJZUe3Ps
G2rUHbKkA75fc9+k6ECZfWDTtQvswfCPbQIywVNVeCSGs8TrkLx8ZHKE1FsfKnmC
7IvVYiwMxAcVcEgOOKGMjmNRShOE9hv2Bz6AbFvgALoryWlzX4Z3IoJ2PA/XUPb9
OSFff45pVH75FGf2lhBhwi40nLzFkvc41kKTF3XZWaLceGFYDipUZl9bvUyC1cxU
HDrIBZjsn+W8bh03U2KUQw41rvPIVzfsmsp/A7hIV9Vb7/4lnQ==
=bbSP
-----END PGP PUBLIC KEY BLOCK-----

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by ghost** [comment]
@Yantrio can you please take a look at this?
