### ISSUE TITLE
Provider Key: visionone

### ISSUE THREAD

**Issue by trend-lucas-wu** [opentofu/registry#697]
### Provider Namespace

trendmicro

### Public Membership

- [X] I have made my membership public

### Provider GPG Key

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBGZqtxYBEADSx75ZuTRY6WGGOT5cPEbq9E5/M7TitIzmMC+TfRtbBmSdA1Vq
BFXLbA43QOfKNS4iLwffUnkn0L5vu/6GZf0yhE2Z79BLxdBergsbbWjAYl+bk0n2
GUnF3JI14srOxoytx5Zkq9AKH3xq00O9+8arNpWyZqRTxU7YbCOVZdt86Enhd/TP
q8b+pUOokuX5o9Dak+ltW/BkfJQtKbFmdZd3WcIPqSfgwdkYaShMnU8T6F7Bvv2j
5cccuJ/GexeCQWo0r1zVtb45rXWY7ATZILFZB6sPyE6n3BlqqRzErdwhVoKqLVIX
pyZOWUb7sXBhxbgK/IlWT3dboHaVGopfeIH3TOEtOklHDWs2F35LHQjQLZlGPQpH
76JahJLKHdQErMp8Yucso1Y8F+iieR1SiDHHUZoalf+hsICQKKm4IHSbGe/bALz0
NVTafBMvceSpryoe9ICoun77tWNJBKE4rgyJlSn58ygNE2OliZlCjibP7Y2lMLwS
psTIIb5W0sp1q3l8+qLZyQaH2NF52YZj89z4n8D50yn0aDEztpUe32VJFEAu6j2z
6GYVQruKPeQoUU2eFA8f6DeB3lzLhjmDIg74duudaJ3HEI9D1ZDDr0UutIXjiej9
D9GjNEc78u8m9xsIIW7t1aay8HqVrVWijEcqAPIKwYGYKzKQLybGVZOOpQARAQAB
tCx0ZXJyYWZvcm0tcHJvdmlkZXIgPGx1Y2FzX3d1QHRyZW5kbWljcm8uY29tPokC
VwQTAQgAQRYhBA0n6301vCLM/pixPDnySZoK9lUoBQJmarcWAhsDBQkFo5qABQsJ
CAcCAiICBhUKCQgLAgQWAgMBAh4HAheAAAoJEDnySZoK9lUo4R4P/RUfCB0HhHLY
zk5s8xbp0VE11KQ4sunBERXGwJNkdFNprXEjSJh79LvwzPm6MzrdWCU063pSyplM
uOTCpeyEhkoQB7jlV5peRLCShAOiaS64/+Jpr+2pFUMqkBRs4KRdBPZrwFoQmpAc
2yMq6aHVTCboRPc4b9QWxGRLJiPFoU9ZoxLjvwdJ5ithFACZYmkZ8inoVyKA4mLy
sACBD1SvxwR8CAzIZbb6KdDqgFKYvg6i0KeYa1eQE4Q3GTHNswenA50VNAeb3vBU
lOiLAa/dZFkBJovqXdXWgzZ6X39g1BnATPGmF2F/t7Qv0XoW4K73qJ3lSIXq5jDl
PY6znRK7f/VKE27Jj0Fmzbx1CwZw7l8qRzvl23cDXHp8Rzd4KAqhZiI1xQtCfSiJ
cWI3hWTR9BXyw3BWRZ4imTa1gzF+2HK3E0gYLNnQsbQZgEslhiBLu8cVJa2k2JkU
mVwvc5xII59uAa7H5CxuvxyMRsamR/mKcyjSYuvSHr7O635ATITMg9lCrL3Gu5UX
gPAJlO3iLga7TwsUfBsR8A00ZxanyKDiManSN6+UEgf5r/8GjcZV3LOMB0B9t8qK
Qaj+c7cDZTRQDanpfp8ZMwJrJH3ogA9kosVzpxVRaTC1lnxzCF09xyseoUoX0905
q/XNdHLPG6wyWnUHZESiSNMKkBwQrbkp
=KSME
-----END PGP PUBLIC KEY BLOCK-----

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by trend-lucas-wu** [comment]
hi team, I change my membership status, can you help re-check again? Thank you

**Comment by Yantrio** [comment]
Thanks!
