### ISSUE TITLE
Provider: dmacvicar/terraform-provider-libvirt

### ISSUE THREAD

**Issue by darpakiss** [opentofu/registry#703]
### Provider Repository

dmacvicar/terraform-provider-libvirt

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by muellert** [comment]
It would be nice if this provider were listed on the registry page. Maybe have a 3rd party section for providers you don't manage yourself there?

**Comment by ollevche** [comment]
Hey @muellert! The registry UI is still in beta and currently, it lags behind the latest version of the registry itself.
