### ISSUE TITLE
Add snowflake-labs/snowflake GPG key

### ISSUE THREAD

**Issue by metaloid2k21** [opentofu/registry#727]
### Thank you for reporting an issue.

When using snowflake-labs/snowflake provider, getting missing registry GPG key error:
``
- Installing snowflake-labs/snowflake v0.84.0...
- Installed snowflake-labs/snowflake v0.84.0. Signature validation was skipped due to the registry not containing GPG keys for this provider
``

### OpenTofu Version

```shell
OpenTofu v1.7.3
on darwin_arm64
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_version = "~> 1.7.2"
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "0.84.0"
    }
  }
}
```

**Comment by cam72cam** [comment]
Please open this issue in https://github.com/Snowflake-Labs/terraform-provider-snowflake.  We don't have access to other organization's public keys.

They can submit their provider keys here: https://github.com/opentofu/registry/issues/new/choose

**Comment by metaloid2k21** [comment]
Thanks @cam72cam will do 👌
