### ISSUE TITLE
Provider: add Lumos

### ISSUE THREAD

**Issue by emnet-crl** [opentofu/registry#735]
### Provider Repository

teamlumos/terraform-provider-lumos

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by ghost** [comment]
@emnet-crl thank you for this provider submission. If you are a user of this provider, please also submit an issue with teamlumos asking them to submit their GPG public key [here](https://github.com/opentofu/registry/issues/new/choose) so we can properly authenticate the provider.
