### ISSUE TITLE
MaaS Provider is Unmaintained

### ISSUE THREAD

**Issue by sempervictus** [opentofu/registry#739]
### Thank you for reporting an issue.

Per the TF provider maintainers, MaaS is [not maintained for OpenTofu](https://github.com/canonical/terraform-provider-maas/issues/221#issuecomment-2239442891) which has made breaking changes to the provider namespace since it was copied from the original registry.

We are pushing fixes for the logic errors in the provider as well, but they want us to sign over rights via CLA which is mildly absurd outside works for hire.

### OpenTofu Version

```shell
OpenTofu v1.7.3
on linux_amd64
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_version = ">= 0.14.0"
  required_providers {
    maas = {
      source = "maas/maas"
   }
}
```
is now
```hcl
terraform {
  required_version = ">= 0.14.0"
  required_providers {
    maas = {
      source = "canonical/maas"
   }
}
```
but that is not maintained here. We can push our code to the [sanscla repo](https://github.com/sanscla/terraform-provider-maas) but someone will need to run public builds (our CI is internal) and maintain the public provider against upstream...

**Comment by ghost** [comment]
@sempervictus thank you for this issue.

First of all, the statement in the linked issue is incorrect. We did not copy anything from the Terraform registry as this would be against their terms of service. The OpenTofu project indexed most publicly available providers from the GitHub API into the registry and the OpenTofu registry is merely an index of GitHub releases.

If you would like to add a provider to the OpenTofu registry, you can do so by submitting the provider [here](https://github.com/opentofu/registry/issues/new/choose). You do not need to be an owner of the provider to do this, but if you want to help us, please open an issue with the provider authors to add their GPG key on the same link.

**Comment by troyanov** [comment]
@janosdebugs I apologize; I didn't mean to imply that OpenTofu copied Terraform's registry or violated their terms of service.

**Comment by ghost** [comment]
The submission PR has now been merged and the provider should be available in the OpenTofu registry within the next 1-2 hours.

**Comment by troyanov** [comment]
@janosdebugs I guess in order to add a notification/warning similar to the one from Terraform registry I need to track the progress on https://github.com/opentofu/registry/issues/410?

It would be great to have something like this:
```
╷
│ Warning: Additional provider information from registry
│
│ The remote registry returned warnings for maas/maas:
│ - This provider has moved to canonical/maas. Please update your source in required_providers.
╵
```

**Comment by ghost** [comment]
@troyanov I've opened #751 to track this. We are doing some work on the registry, maybe we can fit it in.

**Comment by ghost** [comment]
@troyanov thank you for your patience, we are adding the deprecation warning in #1123.
