### ISSUE TITLE
Deprecate maas/terraform-provider-maas

### ISSUE THREAD

**Issue by ghost** [opentofu/registry#751]
As requested in #739 by @troyanov, the maas/terraform-provider-maas should be deprecated in favor of canonical/terraform-provider-maas. (Related to #410)

```
╷
│ Warning: Additional provider information from registry
│
│ The remote registry returned warnings for maas/maas:
│ - This provider has moved to canonical/maas. Please update your source in required_providers.
╵
```

_Originally posted by @troyanov in https://github.com/opentofu/registry/issues/739#issuecomment-2248341992_

**Comment by ghost** [comment]
This is now done:

![image](https://github.com/user-attachments/assets/fc471b31-7edf-4b8b-92dd-7e379e931086)

**Comment by troyanov** [comment]
Thank you @abstractionfactory
