### ISSUE TITLE
Unable to access module registry

### ISSUE THREAD

**Issue by terlar** [opentofu/registry#76]
This was working before, but when I tried this today, I got the following error:

```
│ Error: Error accessing remote module registry
│ 
│ Failed to retrieve a download URL for
│ registry.opentofu.org/terraform-google-modules/kubernetes-engine/google//modules/beta-autopilot-private-cluster
│ 29.0.0 from registry.opentofu.org: failed to get download URL for
│ "registry.opentofu.org/terraform-google-modules/kubernetes-engine/google":
│ 200 OK resp:{
│   "location": "git::https://github.com/terraform-google-modules/terraform-google-kubernetes-engine?ref=v29.0.0"
│ }
```

I believe something must have changed that made this broken?

**Comment by cam72cam** [comment]
Hello, we have deprecated an old alpha-registry protocol that was used in pre-beta releases of opentofu.  Please upgrade to the recently released 1.6.0 beta and give it a try!

**Comment by cam72cam** [comment]
@terlar I'm going to close this for now, we can re-open if upgrading does not solve your issue.

**Comment by terlar** [comment]
I can confirm that I was already using:
```
$ tofu --version
OpenTofu v1.6.0-dev
on linux_amd64
```

I still get this same error.

**Comment by cam72cam** [comment]
Brew unfortunately does not include the alpha/beta release name.  Could you try to brew upgrade that package?

**Comment by terlar** [comment]
@cam72cam Thank you and sorry for the confusion. With your clarification I made sure I had the correct version and it is indeed working with the 1.6.0-beta1.

I was using nixpkgs, just made a PR to ensure the version is propagated correctly:
https://github.com/NixOS/nixpkgs/pull/272666

**Comment by cam72cam** [comment]
Thank you!
