### ISSUE TITLE
Provider: github

### ISSUE THREAD

**Issue by sudoforge** [opentofu/registry#771]
### Provider Repository

integrations/terraform-provider-github

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by sudoforge** [comment]
:facepalm: i was lazy and only looked under `//providers/g`.

**Comment by ghost** [comment]
@sudoforge we will have a UI in a few weeks, that should make things easier.

**Comment by sudoforge** [comment]
neat! 100% lazy user error though; if i had performed a proper search, this would have been avoided :)
