### ISSUE TITLE
Deprecate: tminaorg modules

### ISSUE THREAD

**Issue by aleksasiriski** [opentofu/registry#780]
### Thank you for reporting an issue.

tminaorg has been renamed to voidsolutionsorg, their respective modules have been added to the registry and it would be good for the old tminaorg modules to be removed

### OpenTofu Version

```shell
none
```

### OpenTofu Configuration Files

```hcl
// Snippet of HCL that can be used to help reproduce this problem
```

**Comment by ghost** [comment]
Hi @aleksasiriski ~do you want them to be completely removed from the registry so people get an error message when they try to use them?~ Nevermind, the GitHub of that org no longer exists, so we'd likely have to remove it due to the repo not being present anymore.

**Comment by aleksasiriski** [comment]
Yeah, completely remove them.

**Comment by cam72cam** [comment]
It looks like these will continue to work due to github redirects, but we can remove them from the registry if that is what you want.
