### ISSUE TITLE
Provider: terraform-provider-storagegrid

### ISSUE THREAD

**Issue by rafaelgieschke** [opentofu/registry#784]
### Provider Repository

opensourcevdi/terraform-provider-storagegrid

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by ghost** [comment]
@rafaelgieschke your provider release seems to be missing the SHASUMS file.

**Comment by rafaelgieschke** [comment]
> @rafaelgieschke your provider release seems to be missing the SHASUMS file.

Thanks! Fixed I hope (tried to make this as minimal as possible, so might need some more iterations :smiley:)
