### ISSUE TITLE
Do you have geo restrictions on registry.opentofu.org?

### ISSUE THREAD

**Issue by amkartashov** [opentofu/registry#823]
Subj

I didn't find any announcements about this.

If you have any, please add it clearly to opentofu.org.

If you don't, please check why it returns 403 from some locations:

```
$ curl ifconfig.io
37.192.49.16
$ curl https://registry.opentofu.org/.well-known/terraform.json
Forbidden
```

**Comment by DicsyDel** [comment]
https://github.com/opentofu/opentofu/blob/main/README.md#registry-access

**Comment by MaxOinRU** [comment]
> https://github.com/opentofu/opentofu/blob/main/README.md#registry-access

Why Russia was blocked yesterday?

**Comment by DicsyDel** [comment]
It was blocked as soon as TSC discussed and approved this decision here: https://github.com/opentofu/opentofu/blob/main/TSC_SUMMARY.md#sanctions-russia-vs-registry-access

**Comment by amkartashov** [comment]
> It was blocked as soon as TSC discussed and approved this decision here: https://github.com/opentofu/opentofu/blob/main/TSC_SUMMARY.md#sanctions-russia-vs-registry-access

Thanks for clarification. Do you have to comply with sanctions? Or is it just personal decision?

**Comment by DicsyDel** [comment]
Registry is hosted in the US, by US company. OpenTofu is an open source project and everyone from any country can do whatever they want within boundaries of MPL license. Code of the registry is also under opensource license so can be hosted by anyone. However access to services like registry.opentofu.org or what is being hosted there is under TSC discretion and it was deemed appropriate to block access from certain territories to avoid any legal issues. For instance, Sberbank provider was in the registry, while entity is under wide sanctions: https://sanctionssearch.ofac.treas.gov/Details.aspx?id=18715 .

**Comment by amkartashov** [comment]
> to avoid any legal issues

Sounds reasonable

**Comment by kvendingoldo** [comment]
@DicsyDel why can't we host registry elsewhere?

**Comment by gecube** [comment]
@DicsyDel 

> For instance, Sberbank provider was in the registry, while entity is under wide sanctions:

and what? You can not prove that tf provider for sbercloud is done solely by sberbank developers. Also as I know it is not Sberbank itself who is developing SberCloud, but rather another legal entity (but who cares?)

> However access to services like registry.opentofu.org or what is being hosted there is under TSC discretion and it was deemed appropriate to block access from certain territories to avoid any legal issues.

Totally agree with this and honour this decision, but it should be explicitly stated that some territories are blocked by GeoIP principle.

**Comment by povisenko** [comment]
welcome to the russian world
