### ISSUE TITLE
Private OpenTofu registry 

### ISSUE THREAD

**Issue by MaxOinRU** [opentofu/registry#913]
### Description of the feature you are looking for.

We'd like to make our private registry based on opentofu. So have some questions. 🤔

1) Is there any options to close registry by some authentication, like `terraform login` or `token` in `.tofurc`?
2) Will `tofu init` work if we host our registry in private/public aws-like s3?

**Comment by cam72cam** [comment]
Hi @MaxOinRU, in the future please do not close and and open new issues with the same content (https://github.com/opentofu/registry/issues/854).

1. Not to my knowledge
2. See https://opentofu.org/docs/cli/private_registry/

**Comment by MaxOinRU** [comment]
@cam72cam, thanks for the response.

Sorry, I was thought that issues created without using template will be ignored 😅

Okay, I'll try to explore docs link.
