### ISSUE TITLE
Provider Key: terraform-provider-azapi public key

### ISSUE THREAD

**Issue by ms-henglu** [opentofu/registry#920]
### Provider Namespace

Azure

### Public Membership

- [X] I have made my membership public

### Provider GPG Key

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BSN Pgp v1.1.0.0

mQENBF9hII8BCADEOCDl3/1tAZQp/1BCVJN+tqIRCd3ywzhOXTC38XWC0zVbFtiA
vbBFL1e78aoDIyUFDZcphCyYDqBkweXeYyYVCojZFVniyKklc2xZ15LDwlMBhneU
yEPSzDCltFn67wMPQMKa4+TujZJ3TIs1OUnUTsCPrjavGgmrfAdxAF/EjCDrnVp9
XmRWJii/9elAnMqWLDkMDfPaWkv3lWuyYCBHc7avOJE9oWypmWoEPOujwmtika/i
FhmvZbojZN6huf7pykXGRl1wEpu0MMEFvm4UsfEOv8JHVBZEu2w6glQugT6a+IZ6
atH3zyy+i1mmgsJPlMF1soHNEufeK1CabMklABEBAAG0Q1RlcnJhZm9ybSBBRE8g
cHJvdmlkZXIgcmVsZWFzZSA8dGVycmFmb3JtYWRvcHJvdmlkZXJAbWljcm9zb2Z0
LmNvbT6JATgEEwEIACIFAl9hII8CGwMGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheA
AAoJEG8Lkb3phHjPT+YH/3aksw2yhoqVl+Dxkrpsq9LIsXBHmHfbk8/nwbZ7F6o6
fZetwozQzS/v5IriE42NFdk2omilDa/Iumk5soPrCamIIToYMbGvZJ9MJzCflXzp
H3crqEgoCwu/93FVot4hhNOGmS2ra538zDQ3JsSbsVSc2TyPeBCF08+qJrr9VSML
LceuEvCKUN8P8LH+PXN4kKM1xNlSVw4RfH6mNJKdUG1Klvh2nbq0kuw8jiHITn2F
ALGvKXPLwggdNA86RIQc9tc3z/uJrBGSA2n6UkJbV1gFZDETjHzVtgDqqEQwap7D
/i9e5KqIAEIf14OPm3h+e6kCdWXRG0RJWWVWeOHIEfQ=
=KwXd
-----END PGP PUBLIC KEY BLOCK-----

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by ms-henglu** [comment]
I just made my organization membership public, please rerun the checks.

**Comment by ghost** [comment]
@ms-henglu a user reported an issue with another provider in the `azure` namespace not returning as signed because this is the only key for this namespace: opentofu/opentofu#2033

We will be reverting this key until we can get all the keys for Azure or we have a solution to sign individual providers.

**Comment by cam72cam** [comment]
Merged the fix and deployed:
```
tofu init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of azure/modtm...
- Finding latest version of azure/azapi...
- Finding latest version of azure/alz...
- Installing azure/modtm v0.3.2...
- Installed azure/modtm v0.3.2. Signature validation was skipped due to the registry not containing GPG keys for this provider
- Installing azure/azapi v1.15.0...
- Installed azure/azapi v1.15.0 (signed, key ID 6F0B91BDE98478CF)
- Installing azure/alz v0.15.1...
- Installed azure/alz v0.15.1 (signed, key ID A3E2A92EBB326B85)
```
