### ISSUE TITLE
Module: Env0 Maps

### ISSUE THREAD

**Issue by Cipher-08** [opentofu/registry#928]
### Module Repository

Cipher-08/env0-maps-T01

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by ghost** [comment]
Hey @Cipher-08 your repository is named incorrectly, it should be named `Cipher-08/terraform-env0-maps-T01` to be recognized as a module repository. Please rename your repository and resubmit the module.
