### ISSUE TITLE
Sentry provider is missing in opentofu

### ISSUE THREAD

**Issue by esulzickis** [opentofu/registry#938]
### Description of the feature you are looking for.

When I try to add [sentry](https://registry.terraform.io/providers/jianyuan/sentry/latest/docs) provider I am getting the error:

 Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ hashicorp/sentry: provider registry registry.opentofu.org does not have a
│ provider named registry.opentofu.org/hashicorp/sentry
│ 
│ Did you intend to use jianyuan/sentry? If so, you must specify that source
│ address in each module which requires that provider. To see which modules
│ are currently depending on hashicorp/sentry, run the following command:
│     tofu providers
│ 
│ If you believe this provider is missing from the registry, please submit a
│ issue on the OpenTofu Registry
│ https://github.com/opentofu/registry/issues/new/choose

Could you please add this provider to opentofu?

**Comment by Yantrio** [comment]
Hi, it seems you tried to use the provider by its short name of just `"sentry"` instead of using `"jianyuan/sentry"` 

as per the error message, did you attempt to use `jianyuan/sentry` ?

**Comment by esulzickis** [comment]
My bad. I see that there is a provider already in tofu https://library.tf/providers/jianyuan/sentry/latest
