### ISSUE TITLE
[opentofu-ls] 429 Too Many Requests Error When Initializing Providers in parallel/loop

### ISSUE THREAD

**Issue by gamunu** [opentofu/registry#940]
When attempting to initialise providers using `tofu init` for schema generation for [OpenTofu ls](https://github.com/gamunu/opentofu-ls), I'm encountering a "429 Too Many Requests" error.

```log
Error: Failed to resolve provider packages
Could not resolve provider hashicorp/netlify: could not connect to
registry.opentofu.org: failed to request discovery document: 429 Too Many
Requests
```

This issue occurs during an automated process to generate schemas for multiple providers. The current rate limiting on the registry/GitHub seems too restrictive for this kind of bulk operation.

#### Steps to Reproduce

2. Set up a script or process to generate schemas for multiple providers
3. Run tofu init for each provider in succession
4. Observe that after a certain number of requests, the 429 error occurs

##### Expected behaviour

The initialization process should be able to handle provider initialisation in a loop/in parallel without triggering rate-limiting errors.

#### Possible Solution

1. Provide guidance/advice on handling provider initialisations in a loop without triggering rate limits; if the registry is not mature enough to handle that type of load, a way to pass a personal access token or a GitHub token would be ideal so that I can use it in the GitHub CI workflows.

### OpenTofu Version

```shell
OpenTofu v1.8.2
on darwin_arm64
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_version = "~> 1.0"
  required_providers {
    provider = {
      source  = "hashicorp/netlify"
      version = "1.0.0"  # Replace with actual version
    }
  }
}
```

**Comment by Yantrio** [comment]
Hi @gamunu I can see we have something in place to ensure that nobody does a certain amount of requests per minute against the registry. I'll bump this value now as most of our registry is heavily cached and serving this information should be fine. This should work for you now, please try again and let us know

**Comment by gamunu** [comment]
@Yantrio Thank you. I still noticed the issue locally, but it disappeared in the GitHub actions. It seems that the limits are not applied to GitHub itself. Having it work on actions would be sufficient for me to continue with my work.

https://github.com/gamunu/opentofu-ls/actions/runs/10827917285/job/30042115292?pr=17

**Comment by Yantrio** [comment]
Aha! I can see that you hit another rule and were rate limited there too. I've upped those limits there also and you should be fine now.

For reference we were limiting you due to the number of 404s you've had hitting the registry.

**Comment by wyardley** [comment]
If you're initializing them in succession vs. in parallel (parallel may also partly work, but you may run into issues like [this](https://github.com/hashicorp/terraform/issues/25849), may want to consider caching in your CI run, which should also speed things up.

to start with, could set the following env vars (IIRC, you may need to make sure the plugin cache directory you define is created before running)
```
CHECKPOINT_DISABLE: "true"
TF_IN_AUTOMATION: "true"
TF_PLUGIN_CACHE_DIR: "/tmp/.terraform.d/plugin-cache"
```

**Comment by gamunu** [comment]
@Yantrio  yes the issue is now gone; thank you for the support

**Comment by gamunu** [comment]
@wyardley, thanks for the tip. I will try it out as well.

**Comment by cam72cam** [comment]
@gamunu sounds like this is closed, let me know if it needs to be re-opened
