### ISSUE TITLE
Provider Key: ably

### ISSUE THREAD

**Issue by graham-russell** [opentofu/registry#950]
### Provider Namespace

ably

### Public Membership

- [X] I have made my membership public

### Provider GPG Key

-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 3B26 C031 F3A8 037D DEDA  CA13 B58D 0B76 42B4 DEC8

xsFNBGMQjEoBEAChC/XR8A/wiAN0NRp8bGGBWBoqFeW6YT33ufah0VyzIIUGWn1Y
k1oNNDRWqK1hkRkL8omOnw5y/RWo3MqMAs5TjK6gFUbnp0S50Q8nfXDYTPKCTTod
8X7T7jLmM/Rk2z1Aptv7naMAgvgq7CUUH1q9bsPd/H3X3ACJZSi6gDkPIFMe9IJu
QzsjT4TUI5IaB17D9+AOlgRRmvH1pvlKeMdrewB1UyUzn5p0JoU8wg2IG57QPUCa
iD4BeXeevRs7hAqj/FqKG79h0KfiRHQOFSs/cLukCSRpXfqTW0L3VxX/pyO1eEC2
8VgSp8dyghIP91NNOgD0NhDrz6xXrMtUKxVRjFbdqe0supF4vj0JjVCvT49Zsmkd
V8YFmsRhqHZMjE/C2Q0vvGKiqxZMcQmGpSWjAGl0Hh/WNQi7LvnjcHilhuWafF2R
6+9d/BYD85NwR+FS8r2VEdHbsq+m6pvoSfwOBRxdd7foD7/eOpnSWX6VGP7MeCEu
5XXCSLOa316aGT9mCF0r5eF7gvqpVJciHgWbcpsSh9pmvAsJvBZRqd4O0qPB8eiL
M6JHMRy11G17oHkVANAsb/5a+dcm6llR4npv5+ivkLLDQhaWEwxlhiTCoJLR6O9W
qmPt2eDO7a0cHNAXN8KR48+SuY8limDa3Kn0RALaw2KaokR85FlDpPbvRQARAQAB
zsFNBGMQjEoBEACwmVlUPGxdMWPNF8bx9fWJQDOPtlryqKrcJswohneMMxpkNUqo
R9nBtbS4lFwmbl8t+QJk9n0I0AxP+tJ79aEKb/gOy+8SDW6IhrrDU5o5AslHcswN
zyM01Yf0s7iBFg9rfQ65vHoYKDewHTWXPLQ+mY1Aj73YLOm57CbW77YHv2Q8w5eu
Aux5lsqYso2PyRMXVED1Faap/H1X9q4SlLtROasrMn4UIcoigzxpT1/Np1pxjDPP
z1Fm4OQEBYAqNYXhsG+/pH+UMeZSqIFarMvXj53T4T6ZplASJCwGi/SSOjXl0fNa
N5wTdZ99Sb+DKoioMQXQPRyhzlyz5eSJPYtFMFofTkPLyl6ZDr/GmP/i3crq8ySu
YEOA+ujFFinPE+z0YzljZfVj1K8vhlfHERrdrj0vgm0F3ixoVBObqKxFwF+Zw8Lv
nNLa/BHMqvZq4TwyD+xWiq0KjdJcEhvZC8numYH8Bcn3MLSuIO3vSlBdWK8z6W1G
QhF2dpTe2zWJUl/lpzIs/fO2YYN3RCCpc/SW6TutzDhVAL6svTcjpUbrdnFtGq16
WRyk9GBsy+z4+AUO828zcBx9d3MhRAJ4Vjg3TtPhW6UkcSpRRYMm1OzVOjG/jnGh
R7rLCz1WDt0e73WBhRx/nPNc0A7LhfEd40R3lXHgOzFxXGDVQa7qVzhwxQARAQAB
wsF8BBgBCAAmFiEEOybAMfOoA33e2soTtY0LdkK03sgFAmMQjEoCGwwFCQlmAYAA
CgkQtY0LdkK03sjipw/+I8cWWwwYpe5D73zJKijsQiCvV4JtpkSUkofCXIYD2qJu
iuW4w8ngLyON724L6EZL6YUt8OC4Gx8zXicFbiKcloPL50EICQaxTbUWRnrnXIDt
PjziP6j4EXcaqFf/GK2eoSSZIU7TTezC3JPoCdcgSQtsID5WuPrOmwb7CfK+HPV9
szHm8PwaBfBOFiUSfmrRGhNyq/7MBNQB0vX03npjZCJmNwWKeog/+ANX7MYaCXJC
k/n5XZWr8WvLpaT+htRNPPST8lqgYKi8rgfnn3/T1DZTyD0E8hJvWi4cJkEm1hre
5VMDHnjzmX2bCu8hfEmyzWAwgyXs/MbSFm6GcN9RjKrPWusN1boWMRrBuqha6HwH
ASIVdpNYAkUZMxEsEkUbwRRouVbuV53xbFoN3XPt6y1kVADCoKX/tnuDSGk3Hm7y
eDj9vciJSQwAigqy2xzkRUwqX0VIktCK1bFs+FbU4NgFH/bqT6zL0p/sXbzLYhBD
v0ICufEhUQjD87igLvlMqdKuQ5M2DpjUY9nhtvLDCIoM0Jd3rWijWWrqDRjuQfWu
UzMc2vf3vpFDWSZhR08beBsssbm/FeQclYzvQBJuHCH2KXLbR49zsZ4Ai5TYoLIb
JIOU8hPD1q5s78jmybDCNp6S7Mc/SsYjJHCdGckaCrkI5h2m64581cjR/TWF7yg=
=+x4b
-----END PGP PUBLIC KEY BLOCK-----

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by ghost** [comment]
@graham-russell thank you for this key. Unfortunately, this key does not have a user ID associated with it. Please edit the key to include a user ID.

Additionally, we require users to publish their organization membership to verify they are authorized to submit GPG keys. I'm going to close this issue, please re-submit the key as a new issue once these are addressed so the automated workflow can correctly process the key.

Thanks for your help! If you need additional help with any of these, let us know.

**Comment by graham-russell** [comment]
Thanks @abstractionfactory . I'll resubmit shortly. I've just made my organisation membership public and will provide the key with a user ID.
