### ISSUE TITLE
Provider: terraform-provider-gpg/terraform-provider-gpg

### ISSUE THREAD

**Issue by pascal-hofmann** [opentofu/registry#951]
### Provider Repository

https://github.com/terraform-provider-gpg/terraform-provider-gpg

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by ghost** [comment]
@pascal-hofmann there seems to have something gone wrong with the submission. Can you please resubmit this provider as a new issue to trigger the workflow correctly?
