### ISSUE TITLE
Provider: terraform-provider-gpg/terraform-provider-gpg

### ISSUE THREAD

**Issue by pascal-hofmann** [opentofu/registry#952]
### Provider Repository

terraform-provider-gpg/terraform-provider-gpg

### DCO

- [X] I sign this project's [DCO](https://developercertificate.org/)

**Comment by pascal-hofmann** [comment]
Thanks for the fix @abstractionfactory. :)

**Comment by ghost** [comment]
@pascal-hofmann thanks for this, we should support submitting links :)
