### ISSUE TITLE
hashicorp/google 6.3.0 not getting picked up

### ISSUE THREAD

**Issue by wyardley** [opentofu/registry#984]
### Thank you for reporting an issue.

I'm not seeing `hashicorp/google` again after the release of 6.3.0, despite the sync job having apparently run multiple times. It was released ~ 11 hours ago.

https://github.com/hashicorp/terraform-provider-google/releases/tag/v6.3.0

See #939 and #659

### OpenTofu Version

```shell
OpenTofu v1.8.2
on darwin_arm64
+ provider registry.opentofu.org/hashicorp/google v6.2.0
```

### OpenTofu Configuration Files

n/a

**Comment by ghost** [comment]
@Yantrio it looks like we are having issues with this again?

**Comment by ghost** [comment]
Thanks @wyardley it seems we have to apply a more permanent fix to this. :(

**Comment by terlar** [comment]
I also noticed the `hashicorp/null` not updating. They released a fix last week, applying some patches to fix upstream CVE:s. I presume it is the same issue?

**Comment by Grmiade** [comment]
Same for `hashicorp/aws` 👍

**Comment by cam72cam** [comment]
Traced it back to https://github.com/opentofu/terraform-provider-google/actions/runs/10899310470/job/30244620581

**Comment by Yantrio** [comment]
Hi, Thanks for reporting this! We had an issue with our build process that caused builds for new versions of providers to not be working. I've just resolved this now and the new versions should be available shortly!

Thanks for your patience on this one.

**Comment by Yantrio** [comment]
I can confirm that all of the missed versions are now in the registry and available to download! 🎉

**Comment by wyardley** [comment]
Will there be some kind of fix to make sure these are idempotent / eventually consistent?

it seems concerning that a single failed run can cause the issue to seemingly persist indefinitely until someone intervenes.

**Comment by Yantrio** [comment]
Yes, I'll be writing up an issue in the next day or so to avoid hitting this again in the future.
