### ISSUE TITLE
Provider request: hashicorp/terraform-provider-assert

### ISSUE THREAD

**Issue by wyardley** [opentofu/registry#994]
I don't think I fall into any of the categories to sign the DCO myself, but I think https://github.com/hashicorp/terraform-provider-assert should be allowed since it's MPL, right? Would it be possible to get it added?

I can fill out the request form directly if it's allowed.

**Comment by ghost** [comment]
Hey @wyardley thank you for the issue. HashiCorp does not publish provider binaries, so we will need to fork this provider and build binaries. I've added it to the agenda of the core team to discuss.

**Comment by cam72cam** [comment]
Done last week.
